### ISSUE TITLE
Use PEP 8 for Python code

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#104]
I hardly ever see the style 'functionName ()' being used in Python and it would be cool if this library could follow the PEP8 standard for python code. So it becomes 'functionName()'. There is a library called `flake8` that can lint the code and run during a Travis build to catch mistakes.

If you like this idea, I can work on a pull request.

**Comment by kroitor** [comment]
Hi, @thijstriemstra ! I think it would be awesome if it could show us mistakes. So, if you can do it – go ahead, please ) I will then alter the transpiler to include all missed cases. Thx!

**Comment by thijstriemstra** [comment]
Cool, started working on it in #106, will let you known when it's ready.
