### ISSUE TITLE
Liqui -- missing ask/bids should be NaN, not a zero

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#11]
```
                ask       bid
LTC/BTC    0.019752  0.019598
STEEM/BTC  0.000000  0.000000
SBD/BTC    0.000000  0.000000
DASH/BTC   0.079651  0.078987
ANS/BTC    0.000000  0.000000
Liqui
```

It's unexpected to get a number 0, where there shouldn't be any. I'd expect nan or an error if there were no bids (nan is nicer a bit IMO). And here is similar ro #10  with ask greater than bid.

**Comment by kroitor** [comment]
Fixing this already )

**Comment by kroitor** [comment]
Ok, I think I found the source of the bug with liqui. It returns 0.0 in JSON.

https://api.liqui.io/api/3/ticker/sbd_btc
```
{"sbd_btc":{"high":0.00114,"low":0.00114,"avg":0.00114,"vol":0.0,"vol_cur":0.0,"last":0.00114,"buy":0.0,"sell":0.0,"updated":1499634319}}
```

Do you think I should convert those zeroes to NaNs explicitly in such cases ?

**Comment by nmiculinic** [comment]
Yeah, 0 is a number. What you're getting back shouldn't be a number since it doesn't exist.

**Comment by nmiculinic** [comment]
If I'm searching for a max, NaNs are usually ignored...0 less so.
Or finding a mean, summing NaNs you get a NaN, clear indicator something went wrong. With 0 it fails silently

**Comment by kroitor** [comment]
Got it, will upload the fix asap.

**Comment by kroitor** [comment]
It should be NaN (None, undefined, null) now.
