### ISSUE TITLE
kraken unknown asset pair

### ISSUE THREAD

**Issue by sinplea** [kroitor/ccxt#110]
I am trying to do a market sell order on the Kraken marketplace via the unified api method: 
`
createMarketSellOrder()`

I've tried the pairs:
```
BTC/BCH
XBT/BCH
ETH/BCH
```

And none have worked. Each time the `createMarketSellOrder()` method returns an error like: 
`{ error: [ 'Equery:Unkown asset pair' ] }`

Any way around this?

**Comment by kroitor** [comment]
```
mbp:ccxt igorkroitor$ node examples/js/symbols.js kraken | grep BCH
kraken has 67 symbols: BCH/EUR, BCH/USD, BCH/BTC, DASH/EUR, DASH/USD, DASH/BTC, EOS/ETH, EOS/EUR, EOS/USD, EOS/BTC, GNO/ETH, GNO/EUR, GNO/USD, GNO/BTC, USDT/USD, ETC/ETH, ETC/BTC, ETC/EUR, ETC/USD, ETH/BTC, ETHXBT.d, ETH/CAD, ETHCAD.d, ETH/EUR, ETHEUR.d, ETH/GBP, ETHGBP.d, ETH/JPY, ETHJPY.d, ETH/USD, ETHUSD.d, ICN/ETH, ICN/BTC, LTC/BTC, LTC/EUR, LTC/USD, MLN/ETH, MLN/BTC, REP/ETH, REP/BTC, REP/EUR, REP/USD, BTC/CAD, XBTCAD.d, BTC/EUR, XBTEUR.d, BTC/GBP, XBTGBP.d, BTC/JPY, XBTJPY.d, BTC/USD, XBTUSD.d, XDG/BTC, XLM/BTC, XLM/EUR, XLM/USD, XMR/BTC, XMR/EUR, XMR/USD, XRP/BTC, XRP/CAD, XRP/EUR, XRP/JPY, XRP/USD, ZEC/BTC, ZEC/EUR, ZEC/USD (printSymbols @ symbols.js:33)
BCHEUR     | BCH/EUR  | BCH  | EUR   | false    | [object Object]
BCHUSD     | BCH/USD  | BCH  | USD   | false    | [object Object]
BCHXBT     | BCH/BTC  | BCH  | BTC   | false    | [object Object]
```

Did you read [The Manual](https://github.com/kroitor/ccxt/wiki) at all?

**Comment by kroitor** [comment]
You can check Kraken symbols like so:

```JavaScript
// JavaScript
async function test () {
    let kraken = new ccxt.kraken ()
    await kraken.loadMarkets ()
    console.log (kraken.symbols)
}

test ()
```

```Python
# Python
kraken = ccxt.kraken()
kraken.load_markets()
print(kraken.symbols)
```

**Comment by Tsuihao** [comment]
Hi,

Did any one know why 'LTC/EUR' or 'LTCEUR' both display error: [ 'Equery:Unkown asset pair' ]?

**Comment by kroitor** [comment]
@Tsuihao without seeing your code, it's hard to tell. The correct symbol to use with the unified API is `'LTC/EUR'`.

**Comment by Tsuihao** [comment]
Hi kroitor,

Here is the screen image.

![image](https://user-images.githubusercontent.com/16992390/34628564-0c613076-f265-11e7-868f-416baf58bb0b.png)

**Comment by kroitor** [comment]
@Tsuihao you don't use ccxt in your code. You use some wrapper over the JS version of ccxt (don't know why would you do that instead of using the python version of ccxt directly). I'm sorry, but I can't help you on the usage of `pykrakenapi` package – I'm not the author of it. If you want to use ccxt for the same, check out this example: https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-ohlcv-kraken.py

<img width="652" alt="screen shot 2018-01-06 at 00 33 57" src="https://user-images.githubusercontent.com/1294454/34629479-52c7def2-f279-11e7-8ad1-da01bca9324c.png">

**Comment by Tsuihao** [comment]
Hi Kroitor,

Thanks for your explanation. I am switching to ccxt now.
It works fine.

Regards,
Hao

**Comment by Tsuihao** [comment]
Hi @kroitor ,

FYI:
The Kraken output log is in "time-increasing" order.
However, the GDAX output log is in "time-decreasing" order
![image](https://user-images.githubusercontent.com/16992390/34639409-2eb027ec-f2e0-11e7-9c7e-c7d3e481c7f4.png)


![image](https://user-images.githubusercontent.com/16992390/34639418-4d7875f8-f2e0-11e7-9ec3-496f7be26e8f.png)

**Comment by kroitor** [comment]
Thanks for reporting, @Tsuihao ! We will fix this asap.
