### ISSUE TITLE
issue in either .npmignore or package.json

### ISSUE THREAD

**Issue by nated0g** [kroitor/ccxt#114]
broken when installed from npm currently:

in package.json 
`{...
 "main": "build/ccxt.es5.js"
...}`

in .npmignore

`
build/
`

**Comment by kroitor** [comment]
Will be ready in a new build very soon.

**Comment by kroitor** [comment]
Fixed in v.1.3.101

**Comment by kroitor** [comment]
Lol, broken again in 1.3.102 and will be fixed once again in 1.3.103 %) Sorry for the inconvenience.
