### ISSUE TITLE
Cryptopia exchange support

### ISSUE THREAD

**Issue by dhingra** [kroitor/ccxt#119]
Is anyone else working on Cryptopia(https://www.cryptopia.co.nz/) exchange integration ?

**Comment by kroitor** [comment]
If you can make a template for it (in the same way other exchanges are implemented), we will merge it of course. If you don't, we will integrate it very soon (may be a couple of days). Would you do it yourself, or should we do it on our own? )

**Comment by kroitor** [comment]
Just let us know if you're going to implement it, so that we don't work on the same functionality. If you don't we will start integrating it tomorrow.

**Comment by dhingra** [comment]
Let me kick off with template and start with Market Data API.

**Comment by kroitor** [comment]
Cool! Don't hesitate to ask if you have any questions ) Thx!

**Comment by kroitor** [comment]
Hi, @dhingra ! How are we on this? Do you need help or have any questions?

**Comment by dhingra** [comment]
Hey @kroitor , Just did PR for public API Cryptopia support.

**Comment by kroitor** [comment]
@dhingra thx! Working on it already! ) Merging very soon! )

**Comment by kroitor** [comment]
Ok, mostly done, just a few private methods left, createOrder, etc...

**Comment by kroitor** [comment]
Cryptopia exchange is available in 1.4.26+! Thanks for your help!
