### ISSUE TITLE
Bitstamp added Ethereum

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#120]
As we all know  Bitstamp's API doesn't provide a method for obtaining the markets without scraping their website so they are hard coded right into the ccxt.Which is great because Bitstamp adds new markets on a yearly basis and even that is a big if.
But the moment has arrived.

As of yesterday Bitstamp allows trading in ETH/USD, ETH/EUR and ETH/BTC.
Thank's a lot.

**Comment by kroitor** [comment]
Adding this very soon! Thank you again!

**Comment by kroitor** [comment]
Fixed in 1.4.14+, thx!
