### ISSUE TITLE
suggest to use pycurl instead of requests in  'fetch' methond

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#124]
I have two problems:
1) I always get error as follows:
ExchangeNotAvailable ('bittrex GET https://bittrex.com/api/v1.1/public/getmarkets <urlopen error _ssl.c:733: The handshake operation timed out>'

but everytime I use  "$ curl https://bittrex.com/api/v1.1/public/getmarkets" in shell, it will return the right response.

2) I tried to make two orders on two exchanges, but they will run one by one, not simultaneously.  

So, I suggest to add two features in 'fetch' method  of exchange:
1) asynchronously communicate to exchange server
2) considering use pycurl or other wrappers instead of requests module, as most of the communication need to be fast without many data. 

here is some performance test between requests and pycurl: 
https://stackoverflow.com/questions/15461995/python-requests-vs-pycurl-performance

**Comment by kroitor** [comment]
Hi, @HaoH ! We're not using the requests library ) And we are already working on async modes in Python, as written here: https://github.com/kroitor/ccxt/issues/7
The JS version of ccxt is already asyncronous. We will let you know whenever this is available, in the meantime, if you don't mind, I'm closing this issue as a duplicate. Thx! Keep in touch for updates!

**Comment by kroitor** [comment]
Also, if you want, we can help debugging your bittrex communication, but in order to do that, we need your output in verbose mode.

**Comment by HaoH** [comment]
ok, please close it.

btw, ccxt is using 'urllib' now (not requests, I made mistake before) . it has more space to promote than requests.

**Comment by HaoH** [comment]
OK, I'll paste the info in verbose mode when I face the same problem next time. bittrex server is working right this moment.

**Comment by kroitor** [comment]
@HaoH still wanted to thank you for your proposal and for your involvement! We're on this, hope to deliver soon.

**Comment by HaoH** [comment]
@kroitor hi, here is the error info of bittrex server on my console

https://bittrex.com/api/v1.1/public/getmarketsummary?market=ETH-PAY GET https://bittrex.com/api/v1.1/public/getmarketsummary?market=ETH-PAY
Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0', 'Accept-Encoding': 'gzip, deflate'} None
2017-08-20 01:06:05 INFO  ExchangeNotAvailable ('bittrex GET https://bittrex.com/api/v1.1/public/getmarketsummary?market=ETH-PAY <urlopen error _ssl.c:733: The handshake operation timed out>',)

**Comment by kroitor** [comment]
Hi! Can you please post the same output in verbose mode? We need to see the HTTP log which is shown in verbose mode.

**Comment by HaoH** [comment]
ok，I'll post the info next time.

**Comment by kroitor** [comment]
This might help: 
https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
