### ISSUE TITLE
unable to get exchange bittrex orderbook

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#127]
my code snip:

> id='bittrex'
> exchange = getattr(ccxt, id)()
> exchange.userAgent = {
>     "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0",}
> exchange.verbose = True
> exchange.loadMarkets()
> market='ETH/BTC'
> try:
>     ticker = exchange.fetch_ticker(market)
>     order_book = exchange.fetch_order_book(market)
> except Exception as e:
>     dump(yellow(type(e).__name__), e.args)
> 

result:

> https://bittrex.com/api/v1.1/public/getmarkets GET https://bittrex.com/api/v1.1/public/getmarkets
> Request: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0', 'Accept-Encoding': 'gzip, deflate'} None
> `2017-08-20 23:04:34 INFO  ExchangeNotAvailable ('bittrex GET https://bittrex.com/api/v1.1/public/getmarkets <urlopen error _ssl.c:733: The handshake operation timed out>',)
`
versions:

> ccxt-->1.4.29
> python--> Python 3.6.1 :: Continuum Analytics, Inc.
>

**Comment by kroitor** [comment]
Hi! Thanks for this report! Can you try the same without overriding the user-agent? We need to eliminate this as a possible cause of failure here. Will be waiting to hear from you!

**Comment by HaoH** [comment]
country: China

the result is the same, without overriding the user-agent. 

> `2017-08-21 00:10:47 INFO  ExchangeNotAvailable ('bittrex GET https://bittrex.com/api/v1.1/public/getmarkets <urlopen error _ssl.c:733: The handshake operation timed out>',)`

**Comment by kroitor** [comment]
Ok, can you please try adding one of the following two CORS proxies:

```Python
# before loading markets
exchange.proxy = 'https://crossorigin.me/'
# or
exchange.proxy = 'https://cors-anywhere.herokuapp.com/'
```

Please try any of the two, or both and report if that works. If it does, then it will mean that Bittrex is shaping traffic incoming from China.

**Comment by HaoH** [comment]
'https://crossorigin.me/' proxy has get the same error as follows:

> https://crossorigin.me/https://bittrex.com/api/v1.1/public/getmarkets GET https://crossorigin.me/https://bittrex.com/api/v1.1/public/getmarkets
> Request: {'User-Agent': 'ccxt/1.4.29 (+https://github.com/kroitor/ccxt) Python/3.6.1', 'Origin': '*', 'Accept-Encoding': 'gzip, deflate'} None
> 2017-08-21 00:23:45 INFO  RequestTimeout ('bittrex GET https://crossorigin.me/https://bittrex.com/api/v1.1/public/getmarkets request timeout',)
> 2017-08-21 00:23:45 INFO  bittrex markets loaded
> https://crossorigin.me/http://api.hitbtc.com/api/1/public/symbols GET https://crossorigin.me/http://api.hitbtc.com/api/1/public/symbols
> Request: {'User-Agent': 'ccxt/1.4.29 (+https://github.com/kroitor/ccxt) Python/3.6.1', 'Origin': '*', 'Accept-Encoding': 'gzip, deflate'} None
> 2017-08-21 00:23:55 INFO  ExchangeNotAvailable ('hitbtc GET https://crossorigin.me/http://api.hitbtc.com/api/1/public/symbols <urlopen error _ssl.c:733: The handshake operation timed out>',)


but the 'https://cors-anywhere.herokuapp.com/' works! 

Thanks!

**Comment by HaoH** [comment]
on my shell, I use "$ curl https://bittrex.com/api/v1.1/public/getmarkets" will get result as follows:                             
`curl: (35) Server aborted the SSL handshake`

but when I use "$ curl -v https://bittrex.com/api/v1.1/public/getmarkets",  sometimes it will fail, but other times it will get the right results as follows:

curl -v  https://bittrex.com/api/v1.1/public/getmarkets                           huhao@Huhao-Air
*   Trying 104.17.152.108...
* TCP_NODELAY set
*   Trying 2400:cb00:2048:1::6811:9b6c...
* TCP_NODELAY set
* Immediate connect fail for 2400:cb00:2048:1::6811:9b6c: No route to host
*   Trying 2400:cb00:2048:1::6811:9a6c...
* TCP_NODELAY set
* Immediate connect fail for 2400:cb00:2048:1::6811:9a6c: No route to host
*   Trying 2400:cb00:2048:1::6811:9c6c...
* TCP_NODELAY set
* Immediate connect fail for 2400:cb00:2048:1::6811:9c6c: No route to host
*   Trying 2400:cb00:2048:1::6811:996c...
* TCP_NODELAY set
* Immediate connect fail for 2400:cb00:2048:1::6811:996c: No route to host
*   Trying 2400:cb00:2048:1::6811:986c...
* TCP_NODELAY set
* Immediate connect fail for 2400:cb00:2048:1::6811:986c: No route to host
* Connected to bittrex.com (104.17.152.108) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: ssl763792.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
> GET /api/v1.1/public/getmarkets HTTP/1.1
> Host: bittrex.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 20 Aug 2017 16:15:59 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d6929343872f6fedf6d88916abc299f7c1503245759; expires=Mon, 20-Aug-18 16:15:59 GMT; path=/; domain=.bittrex.com; HttpOnly
< Cache-Control: public, max-age=43
< Expires: Sun, 20 Aug 2017 16:16:01 GMT
< Last-Modified: Sun, 20 Aug 2017 16:15:01 GMT
< Vary: *
< Strict-Transport-Security: max-age=15768000
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< CF-Cache-Status: HIT
< Server: cloudflare-nginx
< CF-RAY: 3916a78db85e7706-LAX
<
{"success":true,"message":"","result":[{"MarketCurrency":"LTC","BaseCurrency":"BTC","MarketCurrencyLong":"Litecoin","BaseCurrencyLong":"Bitcoin","MinTradeSize":0.00000001,"MarketName":"BTC-LTC","IsActive":true,"Created":"2014-02-13T00:00:00","Notice":null,"IsSponsored":null,"LogoUrl":"https://i.imgur.com/R29q3dD.png"},{"MarketCurrency":"DOGE","BaseCurrency":"BTC","MarketCurrencyLong":"Dogecoin","BaseCurrencyLong":"Bitcoin","MinTradeSize":0.00000001,"MarketName":"BTC-DOGE","IsActive":true,"Created":"2014-02-13T00:00:00","Notice":null,"IsSponsored":null,"LogoUrl":"https://i.imgur.com/e1RS4Hn.png"},{"MarketCurrency":"VTC","BaseCurrency":"BTC","MarketCurrencyLong":"Vertcoin","BaseCurrencyLong":"Bitcoin","MinTradeSize":0.00000001,"MarketName":"BTC-VTC","IsActive":true,"Created":"2014-02-13T00:00:00","Notice":null,"IsSponsored":null,"LogoUrl":"https://i.imgur.com/8GLoaDg.png"},

**Comment by kroitor** [comment]
Ok, the problem is explained like this: Bittrex is DDoS-protected by Cloudflare and cloudflare doesn't like traffic from China, so they restrict or throttle it occasionally. 

This is described in detail in the Manual [here](https://github.com/kroitor/ccxt/wiki/Manual#rate-limit) and [here](https://github.com/kroitor/ccxt/wiki/Manual#ddos-protection-by-cloudflare--incapsula). 

The other reason may be due to very frequent requests (they impose a rate-limit and if you're trying to call them more frequently than once per second (exchange.rateLimit in milliseconds), they will not like it also.

If you want to workaround this problem, you probably need to use a proxy, but note, that a proxy will add to your network lag, and you'll get prices slower than you could. If you really want best speed and availability – you probably want to lease an Amazon Web Service VDS/VPS somewhere close to US/Bittrex (that is cheap, a few cents per day). Unfortunately, the ccxt library cannot override your networking conditions, because these are the factors that we cannot control. 

Sorry for that. If you still need further help with this, feel free to ask your questions, or, if everything is now clear, please close it.

**Comment by HaoH** [comment]
@kroitor thank you very much! you are right, I was banned for rate limit reason.  

I used  'https://cors-anywhere.herokuapp.com/' and get error info 
> "Too Many Requests The origin "*" has sent too many requests.\nThe number of requests is limited to 600 per 60 minutes. Please self-host CORS Anywhere if you need more quota"

how about self-host CORS on AWS EC2? does "Amazon Web Service VDS/VPS"  means aws _lightsail_  service?

**Comment by kroitor** [comment]
> how about self-host CORS on AWS EC2?

This will work. You can get a basic CORS-script from our docs here: [CORS for Python](https://github.com/kroitor/ccxt/wiki/Install#cors-access-control-allow-origin). AWS cloud servers should be fine, never had problems with them.

**Comment by kroitor** [comment]
@HaoH though, if you have a server, it's better to run your main script there, than to run a proxy for forwarding your requests from another place. If there's a server, use it for your main application, not for a proxy-purpose )

**Comment by HaoH** [comment]
> This will work. You can get a basic CORS-script from our docs here: CORS for Python. AWS cloud servers should be fine, never had problems with them.

great design for ccxt 👍 

> @HaoH though, if you have a server, it's better to run your main script there, than to run a proxy for forwarding your requests from another place. If there's a server, use it for your main application, not for a proxy-purpose )

Thank you very much ! to run the main application on EC2 is simple and effective, my application is working on EC2 now :)

**Comment by kroitor** [comment]
@HaoH good to know everything is ok now ) thx! )
