### ISSUE TITLE
bittrex bcc vs. bch

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#129]
Bittrex does not have a BCH market, it's called [BCC](https://bittrex.com/Market/Index?MarketName=BTC-BCC) there. When I load my deposits I get a BCC record but the symbol BCC does not exist so it fails to look up the associated ticker. Is this a known issue, should I handle the special case for BCC on bittrex? Hm

**Comment by kroitor** [comment]
Hi again! This is covered here: https://github.com/kroitor/ccxt/issues/83.
On bittrex we explicitly convert BCC to BCH.
If you still find a problem with it after reading that post, feel free to ask your questions here. If there are no questions left, close it please. Thx!

**Comment by thijstriemstra** [comment]
In that case, loading deposits from bittrex contain BCC, it's not being converted.

**Comment by kroitor** [comment]
How do you 'load deposits' ?

**Comment by thijstriemstra** [comment]
```python
deposits = exc.account_get_deposithistory().get('result')
```

**Comment by kroitor** [comment]
That's a custom Bittrex API method, not a unified method and for custom methods we don't do the BCC → BCH substitution and return results as is. The unified fetchDeposists method is on the way, as written in [Pending Tasks](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#pending-tasks).

So, basically, if you use custom API methods (which are unique for each exchange) you will get a non-parsed non-modified reply, and if you use the unified ccxt API, you will have symbols and currencies standardized.

The only thing here is that we still don't have the unified fetchDesposits method, didn't have enough time to do it yet. So, if you feel like doing it, you're welcome ) Or wait until we implement that. Until then, if you want to get deposits with custom API methods, you need to account for symbol inconsistencies yourself, the ccxt library only does that in the unified API (which is being under development / being implemented right now).

If that answers your request, please close it and we will notify you when the deposits are unified. Otherwise, I will be happy to answer your further questions.

**Comment by thijstriemstra** [comment]
thanks for the detailed feedback!

**Comment by thijstriemstra** [comment]
@kroitor I also notice I get only a part of my deposit history back using that method. Bittrex also has a full history option that returns a CSV file. Any plans to support retrieving the full history, is this possible with their API?

**Comment by kroitor** [comment]
@thijstriemstra well, we plan to support everything they have, but we are not sure yet what they have ) there are also some undocumented methods, we will try to workaround everything they miss in their API, of course.

**Comment by thijstriemstra** [comment]
@kroitor created a parse script for the full history csv, see https://gist.github.com/thijstriemstra/835821d98f325225e81352ea828cf521 The API order history only goes back 20 days it seems.

**Comment by kroitor** [comment]
@thijstriemstra , yep, exchanges return history how they want... Some of them only return last 100-200 entries, the other return history for the last 24 hours, etc... We will fetch everything possibly fetchable.

**Comment by thijstriemstra** [comment]
It means I'll have to manually upload and parse the .csv once and use API after that.

**Comment by kroitor** [comment]
@thijstriemstra sorry, didn't quite understand this last one:

> It means I'll have to manually upload and parse the .csv once and use API after that.

That sentence about csv - upload and parse csv from where/to where/when/why/for what? ) The details of your project/task/runtime environment are unknown to me, but it would be interesting if you share with us here what you're trying to do in general.

Btw, we already have fetch_trades() for some exchanges implemented and unified, but not all of them yet. Also working on this.

**Comment by thijstriemstra** [comment]
Basically I want to have an overview of all my orders at any time. My app uses ccxt to load the order history but with the API the history is only limited to 20 days. Since this is something that Bittrex is not going to change any time soon, but I want to have the full history, I download the fullOrder.csv from my bittrex account once (it's even behind a captcha) and then upload it to my app, parse it and store the records in a database, and from then on I use the ccxt API again to get the most recent 20 days. This means I'll have to use the app at least once every 20 days, or I'll have a hole in my order history again. But since I'll be using it to trade daily that shouldn't be a problem..

**Comment by kroitor** [comment]
@thijstriemstra btw, there's big news on async/await. We support asynchronous modes in Python 3.5+ as of today ) Just uploaded it, didn't even have time to document it properly yet )

Check this issue about it: https://github.com/kroitor/ccxt/issues/7

You can use all unified ccxt methods asynchronously now )

As for your task, yep, that's the way it is with Bittrex (and for some other exchanges as well), so we have to deal with it by emulating full order history persistence on our side. But I think running it in a client app is prone to 'holes' in history, if you are not doing it regularly, a normal human can forget or don't have time or have some other reasons for not doing it. I think, these kinds of tasks are better automated with servers/hosts online 24/7 that do the thing for you, probably once every 5 minutes, and you just connect to your server and download latest full updates when you need them.

**Comment by thijstriemstra** [comment]
> I think, these kinds of tasks are better automated with servers/hosts online 24/7 that do the thing for you, probably once every 5 minutes, and you just connect to your server and download latest full updates when you need them.

I agree but good luck getting that csv from your Bittrex account (behind 2FA and captcha) programmatically :)

**Comment by kroitor** [comment]
@thijstriemstra 

> good luck getting that csv from your Bittrex account (behind 2FA and captcha) programmatically :)

Well, if spammers can do that with the Google captcha, why can't we do the same? ) After all, there are solutions for automated mouse-clicking in a real browser window in a virtual machine with  xfree86 / rendering support, no big deal ) Also, I've seen huge offices packed full with people solving captchas, so, it depends on your budget basically )

**Comment by thijstriemstra** [comment]
Yeah but I'm just a oneman show at the moment.

**Comment by kroitor** [comment]
@thijstriemstra sure, the best way to do it is to implement it quickly and have it working with csv, and then you can take time to scale up having a working fallback-solution.

**Comment by kroitor** [comment]
@thijstriemstra sorry, there was a typo up there, I was talking about fetchMyTrades method of course. That one we have implemented for a few exchanges, but not fully unified for all of them yet. Still on this, hope to deliver it soon.

**Comment by kroitor** [comment]
Also relevant to this issue: http://fork.lol/pow/hashrate

**Comment by thijstriemstra** [comment]
Why?

**Comment by kroitor** [comment]
> Why?

Just for the sake of discussion ) Isn't it interesting to you how these two tokens compete? ) If it's not, unvisit that link, please %)

**Comment by thijstriemstra** [comment]
Hehe, sure true, but from a technical perspective it's just another (alt)coin vs bitcoin.
