### ISSUE TITLE
Bitfinex margin orders

### ISSUE THREAD

**Issue by danmaz74** [kroitor/ccxt#130]
I noticed that for Bitfinex you do this to "type":
```
let order = {
            'symbol': this.marketId (market),
            'amount': amount.toString (),
            'side': side,
            'type': 'exchange ' + type,
            'ocoorder': false,
            'buy_price_oco': 0,
            'sell_price_oco': 0,
        };
```
thus allowing only exchange orders (and not margin orders). Is there a reason for this? I didn't check, but I think that "type" is exchange-specific anyway, so why not just let use margin types or exchange types using the corresponding string?

**Comment by kroitor** [comment]
Hi, @danmaz74 ! 

Thanks for your question!

Here's the answer: we use that by default, but we allow you to override the type and trade with margin orders as well. Notice, there's the last argument to the createOrder named `params = {}`. Also notice, that below that code you copied here, there's a line doing `this.extend (order, params)`:

```JavaScript
    async createOrder (market, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets ();
        let order = {
            'symbol': this.marketId (market),
            'amount': amount.toString (),
            'side': side,
            'type': 'exchange ' + type,
            'ocoorder': false,
            'buy_price_oco': 0,
            'sell_price_oco': 0,
        };
        if (type == 'market') {
            order['price'] = this.nonce ().toString ();
        } else {
            order['price'] = price.toString ();
        }
        //                                             ↓↓↓↓ THIS LINE ↓↓↓↓
        let result = await this.privatePostOrderNew (this.extend (order, params));
        return {
            'info': result,
            'id': result['order_id'].toString (),
        };
    },

```

The `params` object is empty by default, but you can use it to set the type as you want it, like so:

```JavaScript
bitfinex.createOrder('BTC/USD', 'limit', 'sell', 1, 4100, { 'type': 'marginOrderOrAnyOtherType' })
```

The `params` argument is supported by all methods for order placement, including, createMarketSellOrder, createLimitBuyOrder, etc...

Is that ok for an answer? ) If so, please, close this issue, and if not, I'm waiting for your further questions )

**Comment by danmaz74** [comment]
HI @kroitor 
Thanks for the answer, it's clear now, but I would have NEVER have guessed it. I just created a pull request with a suggestion to document this feature (didn't test it though...)

**Comment by kroitor** [comment]
@danmaz74 will merge it as soon as you submit! Thx!

**Comment by danmaz74** [comment]
Well check it first ;)

**Comment by kroitor** [comment]
@danmaz74 though, for the docs, you probably would want to fork the ccxt.wiki repository, I don't know if it's possible with GitHub...
