### ISSUE TITLE
Use triple doublequotes for python docstrings

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#132]
Can you use this:

```python
"""
Docstring.
"""
```

Instead of:

```python
'''
Docstring
'''
```
It's also not picked up in github's syntax highlighting if you use single quotes, e.g. https://github.com/kroitor/ccxt/blob/master/ccxt/__init__.py#L3 it seems.

**Comment by kroitor** [comment]
Hi! Thx, once again! Will fix this asap.

**Comment by thijstriemstra** [comment]
@kroitor also this is not the correct way to define utf8: https://github.com/kroitor/ccxt/blob/master/ccxt/__init__.py#L1

I think you should use:

```
# -*- coding: utf-8 -*-
```

**Comment by kroitor** [comment]
Thx! ) Will fix this now as well)
