### ISSUE TITLE
Publish Python wheel files

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#133]
Currently only a tar.gz is published [on pypi](https://pypi.python.org/pypi/ccxt) but since the code is both py2 and 3 compatible a .whl file should be uploaded as well, which is only a fraction of the size of the tarball.

**Comment by kroitor** [comment]
@thijstriemstra Can you help with configuring the .travis.yml for that?

**Comment by thijstriemstra** [comment]
Yea, I'll first have to understand it (and maybe document it). Can you add a release document somewhere that describes the current process?

**Comment by kroitor** [comment]
Currently, we only have the [Contributing](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md) document and the plain configs. It will probably take a day or two among other tasks to write a decent doc for the publishing process... But, basically, we didn't configure the pypi publishing in any way (except the keys), and it worked out of the box in travis (almost everything is left default). 

At the very top level, it does:
1. patch next version number
2. single-source version to all files
3. build with nodejs (transpiles JS → Python/PHP)
4. test with tox qa
5. test with nodejs
6. publish to nodejs npmjs
7. publish to pypi
8. upload back to git

**Comment by thijstriemstra** [comment]
Also, what about moving the wiki documentation into a [Sphinx](http://sphinx-doc.org) rst format?

**Comment by kroitor** [comment]
> Also, what about moving the wiki documentation into a Sphinx rst format?

We already have pandoc installed via travis config, and we convert README.md to README.rst upon build, and strip some tags that are not understood by PyPI.

As for rst itself, I think markdown is much more clear. But we can still convert all of that automatically, I suppose.

**Comment by kroitor** [comment]
> I can make a PR for that to get us started. It can then be published on https://readthedocs.org/.

@thijstriemstra , that would be awesome!

**Comment by thijstriemstra** [comment]
Contributing to the wiki is just harder on github vs. something in the repository that can also be read/compiled offline.

**Comment by kroitor** [comment]
> Contributing to the wiki is just harder on github vs. something in the repository that can also be read/compiled offline.

Agreed! We were thinking of moving it inside the repo anyways.

**Comment by thijstriemstra** [comment]
Ok, I'll get that going tomorrow.

**Comment by kroitor** [comment]
Thx! Feel free to ask all your questions if any!

**Comment by kroitor** [comment]
Btw, note that the recently-added asyncio support may not allow to generate universal wheel anymore. I don't have too much experience with publishing in PyPI, especially when it comes to configuring proper setup.py/setup.cfg/.travis.yml/tox.ini because Python doesn't just work for me, it always demands some setup )) I'm mostly used to publishing with npmjs )

**Comment by thijstriemstra** [comment]
I can work on some decent Python installation instructions..

**Comment by kroitor** [comment]
> I can work on some decent Python installation instructions..

We will really appreciate it!

**Comment by kroitor** [comment]
I mean, I already have both Python installed and working, but that's not the hardest part here. The hardest part is to make travis build proper versions of proper files into proper packaged wheels and publish them to PyPI.

**Comment by kroitor** [comment]
This one did not work as expected, unfortunately...
See https://github.com/kroitor/ccxt/pull/136#issuecomment-323718075
