### ISSUE TITLE
Support OKEX: OKCoin futures exchange

### ISSUE THREAD

**Issue by materemias** [kroitor/ccxt#141]
could you please add support to okex exchange?
https://www.okex.com/rest_getStarted.html

**Comment by kroitor** [comment]
Sure!

**Comment by materemias** [comment]
thanks, is it so that it is only a matter of subclassing okcoin class? I could do that if you accept pull requests

**Comment by kroitor** [comment]
@materemias It would be awesome! And yes, the task is to subclass okcoin base class. But please read the [wiki/manual](https://github.com/kroitor/ccxt/wiki) and the [CONTRIBUTING](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md) document carefully (very important). If you can follow the guidelines precisely, we welcome all your pull requests!) Thank you!

**Comment by kroitor** [comment]
You probably want to start with something like:
```
var okex = extend (okcoin, {
    'id': 'okex',
    'name': 'OKEX',
    'countries': [ 'CN', 'US' ],
    'urls': {
        'logo': 'https://user-images.githubusercontent.com/1294454/29562593-9038a9bc-8742-11e7-91cc-8201f845bfc1.jpg',
        'api': 'https://www.okex.com',
        'www': 'https://www.okex.com',
        'doc': 'https://www.okex.com/rest_getStarted.html',
    },
    'markets': {
        'LTC/BTC': { 'id': 'ltc_btc', 'symbol': 'LTC/BTC', 'base': 'LTC', 'quote': 'BTC' },
        'ETH/BTC': { 'id': 'eth_btc', 'symbol': 'ETH/BTC', 'base': 'ETH', 'quote': 'BTC' },
        'ETC/BTC': { 'id': 'etc_btc', 'symbol': 'ETC/BTC', 'base': 'ETC', 'quote': 'BTC' },
        'BCH/BTC': { 'id': 'bcc_btc', 'symbol': 'BCH/BTC', 'base': 'BCH', 'quote': 'BTC' },
    },
})
```

**Comment by kroitor** [comment]
Also, feel free to ask your questions, if any, we will try our best to help you with this.

**Comment by kroitor** [comment]
P.S. Search for 'okcoin' in entire source to see how it's done for cny/usd okcoins. All methods and endpoints are already there, you can already use them right away right now (in current version) if you simply redefine the api url to okex... But if you want to unify them, that's a little harder. You will need to define which futures-endpoint corresponds to which unified method.

**Comment by kroitor** [comment]
The code could look something like:

```Python
import ccxt
okex = ccxt.okcoinusd ({'urls': {'api': 'https://www.okex.com'}}) # redefine API base url
# call custom method
okex.public_get_future_ticker({
    'symbol': 'btc_usd',
    'contract_type': 'this_week'
}) 
```

**Comment by kroitor** [comment]
The URL of this logo is already in the template above:

![okex](https://user-images.githubusercontent.com/1294454/29565436-95831202-874e-11e7-96b4-838dd8b9f558.jpg)

**Comment by kroitor** [comment]
Hi, @materemias! What's your progress on this? Do you need any help?

**Comment by materemias** [comment]
hi @kroitor I did not have time yesterday, will check it today or tomorrow

**Comment by materemias** [comment]
bcc-bch redundancy is handled in the framework?

**Comment by kroitor** [comment]
> bcc-bch redundancy is handled in the framework?

Yes, see here: [Naming Consistency](https://github.com/kroitor/ccxt/wiki/Manual#naming-consistency).

Also, see this base class method:

```JavaScript
    // JavaScript
    this.commonCurrencyCode = function (currency) {
        if (!this.substituteCommonCurrencyCodes)
            return currency
        if (currency == 'XBT')
            return 'BTC'
        if (currency == 'BCC')
            return 'BCH'
        if (currency == 'DRK')
            return 'DASH'
        return currency
    }
```

```Python
    # Python
    def commonCurrencyCode(self, currency):
        if not self.substituteCommonCurrencyCodes:
            return currency
        if currency == 'XBT':
            return 'BTC'
        if currency == 'BCC':
            return 'BCH'
        if currency == 'DRK':
            return 'DASH'
        return currency
```

**Comment by kroitor** [comment]
```JavaScript
    async fetchMarkets () {
        let markets = await this.publicGetTickers ();
        let result = [];
        for (let p = 0; p < markets['tickers'].length; p++) {
            let market = markets['tickers'][p];
            let id = market['pair'];
            let base = id.slice (0, 3);
            let quote = id.slice (3, 6);
            base = this.commonCurrencyCode (base);    // ← here
            quote = this.commonCurrencyCode (quote);  // ← here
            let symbol = base + '/' + quote;
            result.push ({
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'info': market,
            });
        }
        return result;
    },
```

**Comment by kroitor** [comment]
@materemias you should probably hardcode those symbols as I wrote earlier in [this comment](https://github.com/kroitor/ccxt/issues/141#issuecomment-324003958)

**Comment by materemias** [comment]
#146

**Comment by materemias** [comment]
seems like api has changed on all ok exchanges, pls check
https://www.okex.com/rest_api.html
https://www.okcoin.com/rest_api.html
https://www.okcoin.cn/rest_api.html

**Comment by kroitor** [comment]
@materemias do you see any specific difference between v1 in okcoin and v1 in ccxt (or do you think so because of that red `new` label)? If you do see a difference, please write it here and we will update it.
Also, most of the 'new-red-labelled'-endpoints form here don't work: https://www.okex.com/rest_api.html
Check it out: 
- https://www.okex.com/api/v1/future_estimated_price.do?symbol=btc_usd
- https://www.okex.com/api/v1/ticker.do?symbol=ltc_btc
- https://www.okex.com/api/v1/depth.do?symbol=ltc_btc
- ...
I'm getting a 404 or an error. Basically, only"old" methods work (those without the "new" red label).

**Comment by materemias** [comment]
have you found any order history endpoint?

**Comment by kroitor** [comment]
<img width="237" alt="screen shot 2017-08-23 at 18 26 31" src="https://user-images.githubusercontent.com/1294454/29623964-a2ee6dbe-8830-11e7-88b8-b4e18fb14540.png">

Nothing apart from these, but they should do fine, or is there a problem with them?

**Comment by materemias** [comment]
can i call the api endpoints directly with a cctx instance? did you find wallet balance?

**Comment by kroitor** [comment]
> can i call the api endpoints directly with a cctx instance?

Sure! Just use the custom public/private API, as I wrote a few posts above, [here](https://github.com/kroitor/ccxt/issues/141#issuecomment-324006091).

> did you find wallet balance?

We found all of them from the very start of this project )

**Comment by kroitor** [comment]
```Python
# Python
import ccxt
okex = ccxt.okcoinusd ({
    'urls': {'api': 'https://www.okex.com'}, # redefine API base url
    'apiKey': YOUR_API_KEY,
    'secret': YOUR_SECRET_KEY,
}) 

# call custom method from public API
okex.public_get_future_ticker({
    'symbol': 'btc_usd',
    'contract_type': 'this_week'
})

# fetch balance with a method of the unified API
balance = okex.fetch_balance()
print(balance['USD'])
```

**Comment by helldragonx** [comment]
how to get the future position information?  use  private_post_future_userinfo returns:
{'btc': {'risk_rate': 10000, 'account_rights': 0.0321817, 'profit_unreal': 0, 'profit_real': -5.285e-05, 'bond_type': 1, 'keep_deposit': 0}, 

no long or short position indicator, so it keeps in order?

**Comment by helldragonx** [comment]
@kroitor thanks for your great efforts, and whether this api support future position query?
https://www.okex.com/docs/en/#futures-README

**Comment by kroitor** [comment]
> whether this api support future position query?

Yes, but, currently, only for v1 keys, more about it here: https://github.com/ccxt/ccxt/issues/4063
