### ISSUE TITLE
Check if exchange.hasFetchTickers (for all symbols)

### ISSUE THREAD

**Issue by talvasconcelos** [kroitor/ccxt#144]
I've been trying this package and it's awesome, thank you for your effort. 
I'm running into an error when trying to get all tickers from all pairs from every exchange. Some exchanges don't allow that. 
Do you have a list of the ones that allow or not, oe is it possible to get the info from the markets call?
I'm running a .map with the exchanges, if there was a way to catch the error and keep processing it would be some help.
i tried a filter first to discard the ones that don't allow fetchTickers() but keep getting the error and filter halts.

thanks,
Tiago Vasconcelos

**Comment by kroitor** [comment]
Hi! Thanks for checking it out! We will add an exchange flag to determine if it supports the fetchTickers operation or not. Will update you on this soon!

**Comment by kroitor** [comment]
Ok, we have added a new exchange property `hasFetchTickers` for this (true or false), so you can check it prior to calling the fetchTickers() method. Also, the method itself will throw a specific `NotSupported` exception to indicate it is unavailable (described in [The Manual: Error Handling](https://github.com/kroitor/ccxt/wiki/Manual#error-handling) section). If that satisfies your needs, let us know. If you still have any other questions, feel free to ask! Thx!

**Comment by kroitor** [comment]
This is available as of 1.4.86+

**Comment by kroitor** [comment]
This is also related to (Batch Fetch Operations) #7

**Comment by kroitor** [comment]
This is how to use it to filter out the exchanges that don't support `fetchTickers ()` method:

```JavaScript
await Promise.all (
    ccxt.exchanges
        .filter (id => id != 'xbtce') // some exchanges require the apiKey even for public tickers
        .map (id => ccxt[id]())
        .filter (exchange => exchange.hasFetchTickers)
        .map (exchange => exchange.fetchTickers ()))
```

**Comment by talvasconcelos** [comment]
Thanks man. This is great, i'll try it out later and get back to you but i guess this solves my problem.

**Comment by kroitor** [comment]
@talvasconcelos If you don't mind, I'm closing this, and if this does not solve your problem, feel free to reopen it please. We will be very thankful for your report! Thanks!
