### ISSUE TITLE
Milestone: Websocket API

### ISSUE THREAD

**Issue by kfeeeeee** [kroitor/ccxt#145]
First of all: This is an exceptionally great work and by far the cleanest written and best suitable code for an easy communication with the vast amount of different eexchanges! Thank you!

You wrote that you plan to adopt to the websocket api, which I think will be of great benefit for those of use who are interested in mining multiple pairs per exchanges and, thus, are limites by api rate limits. 

So my simple question would be: Have you already scheduled your work on the websocket api ?

**Comment by kroitor** [comment]
Hi! Thanks for your interest in our work! We appreciate your feedback!

> So my simple question would be: Have you already scheduled your work on the websocket api ?

We hope to deliver WebSocket support for all major exchanges this September ) We will update you on that, keep in touch ;) In the meantime, if I answered your question, then please close this issue as a being a somewhat-duplicate of #56, if you don't mind. Thx a lot! Cheers!

**Comment by kfeeeeee** [comment]
Thanks for your fast reply! 
I am looking forward for your work on the websocket api!

Keep up the good work !

**Comment by mmehrle** [comment]
Hey guys - just wondering what happened to the websocket support. Any updates?

**Comment by kroitor** [comment]
@mmehrle hi! See here: https://github.com/ccxt/ccxt/issues/56

**Comment by mmehrle** [comment]
Wow that was fast!! Thanks mate!
