### ISSUE TITLE
bitmex, Nonce is not increasing

### ISSUE THREAD

**Issue by devcon14** [kroitor/ccxt#147]
Been trying to use the python api.
Some works nicely, but bitmex authenticated api seems to have an issue with the nonce generation.

```python
bitmex = ccxt.bitmex({
        "apiKey": BITMEX_API_KEY,
        "secret": BITMEX_API_SECRET
    })
balance = bitmex.privateGetUserWalletHistory()
```
This is the error:

ExchangeNotAvailable: bitmex GET https://www.bitmex.com/api/v1/user/walletHistory 400 Bad Request  (possible reasons: invalid API keys,
bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, {"error":{"message":"Nonce is not increasing. This nonce: 1503497932, last nonce: 1502567277932","name":"HTTPError"}})

**Comment by kroitor** [comment]
devcon14: Please, read the following: https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce
Basically, Bitmex is telling you, that your keys have already been used with a bigger nonce previously. So you need an even bigger one. By default the nonce is 32 bit (1503497932) and the last nonce you used with bitmex was 1502567277932. To fix it, use a fresh new keypair, or if you want to continue with this keypair, override the nonce for milliseconds or microseconds, as in the Manual.

**Comment by kroitor** [comment]
@devcon14 If that answers your question and solves your problem, please close this issue as being documented in the Manual. If not, feel free to ask your further questions. Thx!

**Comment by kroitor** [comment]
Related: #21, #39

**Comment by kroitor** [comment]
```Python
# Python
import ccxt
import time
    bitmex = ccxt.bitmex({
        "apiKey": BITMEX_API_KEY,
        "secret": BITMEX_API_SECRET,
        "nonce": lambda: time.time() * 1000, #  ← milliseconds nonce
    })
    balance = bitmex.privateGetUserWalletHistory()
```

```JavaScript
    bitmex = ccxt.bitmex({
        "apiKey": BITMEX_API_KEY,
        "secret": BITMEX_API_SECRET,
        "nonce": Date.now, // ← milliseconds nonce
    })
    balance = bitmex.privateGetUserWalletHistory()
```

**Comment by kroitor** [comment]
More on this here: https://github.com/kroitor/ccxt/wiki/Manual#authentication

**Comment by devcon14** [comment]
Missed the doc on overriding, thanks!

**Comment by terol1982** [comment]
seems like bitmex need 16-bit nonce and ccxt generates 13-bit nonce.
so in bitmex.js I did next changes:
nonce () {
        return this.milliseconds ().toString ()+'000';  //old version vas: return this.milliseconds ()
    }

sign (path, api = 'public', method = 'GET', params = {}, headers = undefined, body = undefined) {
...
let nonce = this.milliseconds ().toString ()+'000';
...
}
