### ISSUE TITLE
Create git tags when releasing a new (major) version

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#151]
Can you create a new tag whenever a new version released?

**Comment by cleivson** [comment]
@kroitor, do we follow Semantic Versioning (http://semver.org/)? Could be interesting.

**Comment by kroitor** [comment]
Ok, but there has been only one major version for now. We will do that for 2.0.x. Or did you mean the minor version (the digit in the middle) ?

**Comment by thijstriemstra** [comment]
Whatever suits you :+1:

**Comment by kroitor** [comment]
No problem, thanks for the hint!
