### ISSUE TITLE
Can you add BitYep's API?

### ISSUE THREAD

**Issue by algorithmcode** [kroitor/ccxt#152]
This exchange have nice price. Thanks!

**Comment by kroitor** [comment]
Of course we could, the only thing we need to do that, is a link to their API doc from you. Will be waiting to receive it from you here. Because, when I open https://bityep.top, I don't see them to have any API.

**Comment by kroitor** [comment]
Also, this one does not seem to have a normal exchange API either: https://bityep.com

They don't have adequate docs (no endpoint to place an order with their API, not mentioning other things needed for normal trading):

<img width="1184" alt="screen shot 2017-08-25 at 10 58 22" src="https://user-images.githubusercontent.com/1294454/29704981-bc3e3862-8984-11e7-8432-05e8c818f428.png">

If that is their entire API, we will not integrate it.
