### ISSUE TITLE
Bitfinex API update on Thursday, 2017-Aug-31

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#154]
See http://blog.bitfinex.com/api/api-improvements/

**Comment by kroitor** [comment]
Thanks you for this! We will get ready )

**Comment by kroitor** [comment]
We have reviewed all announced improvements and we've added new endpoints. So now we are compatible with the upcoming update (as we implement Bitfinex API v1). We have plans for adding Bitfinex API v2 support as well. Have everything prepared for the update, I'm closing this for now. Feel free to reopen it or ask your questions if any. 

Thank you!
