### ISSUE TITLE
Zaif Cannot Get BCH Balance Correctly

### ISSUE THREAD

**Issue by imcoddy** [kroitor/ccxt#156]
Looks like the Zaif exchange cannot get balance correctly due to UPPERCASE. The original info contains the balance for BCH

```
{ info:
   { funds:
      { jpy: 314793.229,
        btc: 0.22660636,
        xem: 0,
        mona: 0,
        BCH: 4.0957344 },
     deposit:
      { jpy: 339795.229,
        btc: 0.42660636,
        xem: 0,
        mona: 0,
        BCH: 4.0957344 },
  }
}
```

While the result for BCH is all undefined, and others free and total is not equal to info of ```deposit``` 
```
  BCH: { free: undefined, used: undefined, total: undefined },
  BTC: { free: 0.22660636, used: undefined, total: undefined },
  JPY: { free: 314793.229, used: undefined, total: undefined } 
```

Not quite sure why they use ```BCH``` instead of ```bch``` though, can cctx do some adaption to this?

**Comment by kroitor** [comment]
Sure! We will fix for that! Will update you on this very soon!

**Comment by kroitor** [comment]
Ok, we fixed it, and it should be working normalli in version 1.5.20+. Please update to a most recent version in a couple of minutes (building now). Thanks a lot for you participation!

**Comment by kroitor** [comment]
The fix is ready and available in 1.5.20+ 
We will be thankful if you report, whether it helped you or not! And if it didn't let us know too ) Thx!

**Comment by imcoddy** [comment]
Awesome, I confirm it is fixed. Thanks for the help 👍

**Comment by kroitor** [comment]
Thx a lot for your feedback!
