### ISSUE TITLE
is it possible to create "margin sell" order with bitfinex?

### ISSUE THREAD

**Issue by newbdez33** [kroitor/ccxt#157]
It seems not when I looked into the code. it's always add 'exchange' before order type 

> async createOrder (market, type, side, amount, price = undefined, params = {}) {
>         await this.loadMarkets ();
>         let order = {
>             'symbol': this.marketId (market),
>             'amount': amount.toString (),
>             'side': side,
>             'type': 'exchange ' + type,       <<<<<----- here
>             'ocoorder': false,
>             'buy_price_oco': 0,
>             'sell_price_oco': 0,
>         };

**Comment by kroitor** [comment]
@newbdez33 yes!

Please, see this issue about how to create margin orders with Bitfinex:

https://github.com/kroitor/ccxt/issues/130

If it doesn't work for you, please feel free to reopen this issue, in the meantime I am closing this as a duplicate if you don't mind.

**Comment by kroitor** [comment]
Here's the answer: we use "exchange" type by default, but we allow you to override the type and trade with margin orders as well. Notice, there's the last argument to the createOrder named `params = {}`. Also notice, that below that code you copied here, there's a line doing `this.extend (order, params)`:

```JavaScript
    async createOrder (market, type, side, amount, price = undefined, params = {}) {
        await this.loadMarkets ();
        let order = {
            'symbol': this.marketId (market),
            'amount': amount.toString (),
            'side': side,
            'type': 'exchange ' + type,
            'ocoorder': false,
            'buy_price_oco': 0,
            'sell_price_oco': 0,
        };
        if (type == 'market') {
            order['price'] = this.nonce ().toString ();
        } else {
            order['price'] = price.toString ();
        }
        //                                             ↓↓↓↓ THIS LINE ↓↓↓↓
        let result = await this.privatePostOrderNew (this.extend (order, params));
        return {
            'info': result,
            'id': result['order_id'].toString (),
        };
    },

```

The `params` object is empty by default, but you can use it to set the type as you want it, like so:

```JavaScript
bitfinex.createOrder('BTC/USD', 'limit', 'sell', 1, 4100, { 'type': 'marginOrderOrAnyOtherType' })
```

The `params` argument is supported by all methods for order placement, including, createMarketSellOrder, createLimitBuyOrder, etc...

Hope this answers your question! Thx!

**Comment by newbdez33** [comment]
Got it, Thanks!
