### ISSUE TITLE
Would you like me to help you refactor the js code?

### ISSUE THREAD

**Issue by selaromi** [kroitor/ccxt#16]
Hello! I'm checking your library and I like it a lot, I would like to help you refactor the js code if you think that's ok.

**Comment by selaromi** [comment]
Hello! I'm checking your library and I like it a lot, I would like to help you refactor the js code if you think that's ok.

**Comment by kroitor** [comment]
Yes, of course, thank you so much! But bear in mind, that JS code is transpiled into Python/PHP upon each build, so I have to keep certain things there for other languages.

**Comment by kroitor** [comment]
The transpilation is hardcoded with some criminal regexps in transpile.js (see build.sh/package.json for details)... It also recompiles the docs upon each build.

**Comment by selaromi** [comment]
Perfecto, I'll check it out and let you know!

**Comment by kroitor** [comment]
I'll close this down if you don't mind. Please open more issues, if you find anything suspicious ) Thanks again!

**Comment by slidenerd** [comment]
so what is the original code? the PHP one or JS one or Python one?

**Comment by kroitor** [comment]
@slidenerd, base exchange classes in JS, Python and PHP, derived exchange class implementations in JS, transpiled into Python and PHP.

**Comment by kroitor** [comment]
@slidenerd more about it: https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
