### ISSUE TITLE
Naming convention and directory structure 

### ISSUE THREAD

**Issue by hzmbeyond80** [kroitor/ccxt#160]
I found the following code in exchange.py.  I think the parseOrders is not necessary.  why not let the caller call parse_orders directly?  if it's overridden, then the overridden version will be called.  it applies to other similar situations as well.  Also,  would it be cleaner to let each exchange have its own file, rather than all in one exchanges.py?   it's getting quite large now ... 

    def parse_orders(self, orders, market=None):
        result = []
        for t in range(0, len(orders)):
            result.append(self.parse_order(orders[t], market))
        return result

    def parseOrders(self, orders, market=None):
        return self.parse_orders(orders, market)

**Comment by kroitor** [comment]
Hi, @hzmbeyond80 !

> I found the following code in exchange.py. I think the parseOrders is not necessary. why not let the caller call parse_orders directly? if it's overridden, then the overridden version will be called. it applies to other similar situations as well.

This is explained in the Manual, in the section on [Naming Conventions](https://github.com/kroitor/ccxt/wiki/Manual#api-method-naming-conventions). The short answer to this: we support both camelCase and underscore_notation. The user is free to use any notation he wants. This is needed for code cross-compatibility which is also covered in [Multilanguage Support](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support) section of our [Contributing](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md) document.

> Also, would it be cleaner to let each exchange have its own file, rather than all in one exchanges.py? it's getting quite large now ...

This has also been answered in [Decoupling python/php code from transpiler](https://github.com/kroitor/ccxt/issues/17):

There are two points for having the whole thing in a single source file:
- The ccxt library offers a web-version (in JS) for browsers, for developing web-/mobile-apps that communicate with exchanges. This is the reason to avoid disk access inside the library at all costs. Having all files separated would make the library hard to link against, in some environments.
- Also, a significant time will be wasted for switching between contexts of work. When you are dealing with several files, it's ok, but when you have to work with tens and hundreds of exchanges, it's an overkill. It may not seem to be a problem at first, but in the long term (say, a year) that wasted time sums up to hours and days just for navigating among separate files. I would rather spend that time developing the functionality ) Did you know that an average person spends several days on blinking accumulated throughout a lifetime? ) This is the same as having your eyes closed for a long continuous period ) I would rather not blink at all if I could, I miss that wasted time very much )

We will still consider the raised issue once again, as the library is being under development, in the meantime I'm closing this as a duplicate if you don't mind. If you still have other questions, we will be happy to answer! Thanks for your feedback!
