### ISSUE TITLE
Livecoin "Service is under maintenance"

### ISSUE THREAD

**Issue by npomfret** [kroitor/ccxt#161]
Anyone getting "Service is under maintenance" from livecoin?

**Comment by kroitor** [comment]
@npomfret yeah, that is usual with livecoin. Some exchanges can be unavailable occasionally, it's all documented in the Manual. But, why do you ask? Do you have any difficulty handling it?

**Comment by npomfret** [comment]
No, its just this is the 1st time I've tried to connect.  Was wondering if I'm doing something wrong.  Can't see any mention of downtime on their twitter or website.

**Comment by kroitor** [comment]
@npomfret Yeah, it looks livecoin returns "on maintenance", when it is busy with too many requests/for some locations or regions. I suppose this is due to their rate limits and throttling. We will investigate into it and we will update you on this later, if we find something. In the meantime, If you don't mind, I'm closing this, feel free to reopen it or ask your questions if any.
Thx for your feedback!

**Comment by kroitor** [comment]
P.S. It works and responds normally right now, as seen from my side. You should probably try a cors-proxy (see [Proxy section](https://github.com/kroitor/ccxt/wiki/Install#proxy) in the Manual) to check if your local network / provider is affected, or if it's a global issue with livecoin itself.

**Comment by npomfret** [comment]
You're getting valid responses from the API?

**Comment by kroitor** [comment]
@npomfret currently - yes. But we also receive their "maintenance" replies occasionally.

**Comment by kroitor** [comment]
@npomfret don't know which language you're using, here's a snippet in JS / Python:

```JS
//JavaScript

async function test () {
    let livecoin = new ccxt.livecoin ({
        // last slash critical
        proxy: 'https://cors-anywhere.herokuapp.com/', // or 'https://crossorigin.me/'
    })
    console.log (await livecoin.load_markets ())
}

test ()
```

```Python
# Python

livecoin = ccxt.livecoin ({
    # last slash critical
    'proxy': 'https://cors-anywhere.herokuapp.com/', # or 'https://crossorigin.me/', 
})

print(livecoin.load_markets())
```

**Comment by npomfret** [comment]
Thanks.  Hadn't even got that far.  Was just testing with curl.  But even a basic get (https://api.livecoin.net/exchange/restrictions ) fails for me and has done for a few hours now.

**Comment by kroitor** [comment]
@npomfret try testing it with a basic proxy, running just one line from your python console:

```
import ccxt
# will test it via another route
ccxt.livecoin({'proxy': 'https://cors-anywhere.herokuapp.com/'}).load_markets()
```

Here's a sample of my console output: 

```
mbp:ccxt igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> ccxt.livecoin({'proxy': 'https://cors-anywhere.herokuapp.com/'}).load_markets()
{u'RLT/BTC': {'info': {u'volume': 5250.36534218, u'best_bid': 8.11e-06, u'last': 8.12e-06, u'cur': u'RLT', u'symbol': u'RLT/BTC', u'best_ask': 8.12e-06, u'vwap': 8.46e-06, u'min_ask': 8.1e-06, u'high': 9.56e-06, u'low': 8.1e-06, u'max_bid': 9.56e-06}, 'quote': u'BTC', 'symbol': u'RLT/BTC', 'base': u'RLT', 'id': u'RLT/BTC'}, u'CLOAK/EUR': {'info': {u'volume': 0, u'best_bid': 2.00238, u'last': 0, u'cur': u'CLOAK', u'symbol': u'CLOAK/EUR', u'best_ask': 5.44444, u'vwap': 0, u'min_ask': 0, u'high': 0, u'low': 0, u'max_bid': 0}, 'quote': u'EUR', 'symbol': u'CLOAK/EUR', 'base': u'CLOAK', 'id': u'CLOAK/EUR'}, u'DIME/BTC': {'info': {u'volume': 2782595.11838688, u'best_bid': 0, u'last': 1e-08, u'cur': u'DIME', u'symbol': u'DIME/BTC', u'best_ask': 1e-08, u'vwap': 1e-08, u'min_ask': 1e-08, u'high': 1e-08, u'low': 1e-08, u'max_bid': 1e-08}, 'quote': u'BTC', 'symbol': u'DIME/BTC', 'base': u'DIME', 'id': u'DIME/BTC'}, u'XSPEC/BTC': {'info': {u'volume': 13913.09196038, u'best_bid': 0.0001557, u'last': 0.00015591, u'cur': u'XSPEC', u'symbol': u'XSPEC/BTC', u'best_ask': 0.000156, u'vwap': 0.00016533, u'min_ask': 0.00015569, u'high': 0.00017589, u'low': 0.00015569, u'max_bid': 0.000175}, 'quote': u'BTC', 'symbol': u'XSPEC/BTC', 'base': u'XSPEC', 'id': u'XSPEC/BTC'}, u'BLU/USD': {'info': {u'volume': 9196....
```
