### ISSUE TITLE
Issues with used balance

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#163]
I was testing method `fetch_balance()` and looking if parameter `used` is correct.

In Kraken the method `fetch_balance()` always puts `used` to `None`.
I know, I've seen their API.
It's a mess.
I have literally no idea why Kraken is so popular when their API and their website are competing against each other which one of them is worse.
But if we would go and write the code for it.
Method `private_post_openorders()` returns open orders.
We could go through it and parse which market is in question and if its buy or sell order.
If it's sell the volume is indicating used part of base.
If it's buy the volume * price is indicating used part of qoute.
Base and qoute could be parsed from parametar pair.Which looks like this 'ETHXBT'
So a for loop would be added to the kraken's fetch_balance() and it would just sum all this. 

Liqui.
Same thing.
It could be parsed from open orders.

What's your opinion? Is it worth it.
Looking forward to hearing from you.

**Comment by kroitor** [comment]
As for the solution – that could work, though it's will not work in all cases, but in a simple case it will. The problem with that approach is that it will make at least two requests instead of one for fetching the balance, and it will make that implicitly for that exchange only. So we would rather implement that functionality on top of fetchBalance/fetchOpenOrders in a separate method. But we will consider doing this anyway. In the meantime, I will close it for now. We will get back to you later with our proposal of how we would solve this.

**Comment by kroitor** [comment]
We think used = total - free. We will add that for Kraken.

**Comment by marinsokol5** [comment]
But there is no other way than combining two rest endpoint.
They simply don't offer it as one request.
If you are busy maybe I can try to write that code.

**Comment by kroitor** [comment]
> But there is no other way than combining two rest endpoint.

Yes, but if you do those two requests everytime on fetch_balance (and not when the user actually wants it), it's worse for the utilitarian nature of any library. We would prefer to give a user a separate method for that, which will basically do the same, but having it as a separate method ensures that this behaviour is explicit and is enabled when the user wants it, not when the library wants it. As for the calculation method – you're right, there' no other way to do it for Kraken and we will do it anyway with your help. It's only a lib interface design issue, not an implementation issue.

> If you are busy maybe I can try to write that code.

Your pull requests are always welcome and we really value the feedback we're getting from you! Thx!

**Comment by kroitor** [comment]
Here's an issue that answers why it is bad to make sequential requests within a single call:
https://github.com/kroitor/ccxt/pull/102

You can compare current code for fetchOrder/fetchOpenOrders/fetchOrderStatus on poloniex with their initial implementations to see how it evolved.
