### ISSUE TITLE
HITBTC market buy order issue 

### ISSUE THREAD

**Issue by g666nz** [kroitor/ccxt#164]
So i'm using the bitfinex object and it's working just fine. Both market buy's and sell's but when i try it with hitbtc i get an error 'orderExceedsLimit'. I'm trying to purchase ethereum with bitcoin, so when i fill in the amount 0.012, in the error it shows 'quantity: 12'. I just wanted to know if the problem was from my side. or possibly a bug in hitbtc's object methods. 

Hope to hear from you soon,
br g666nz

**Comment by kroitor** [comment]
Hi!

For us to be able able to help:

- Can you show some code?
- What's your language?
- Which versions ... ?
- Can you show verbose output?
- Blablabla + other boring questions ))

**Comment by g666nz** [comment]
Using node.js
{ orderId: 'N/A',
     latestOrderId: 'N/A',
     clientOrderId: '1504120582',
     orderStatus: 'rejected',
     userId: 'user_432432',
     symbol: 'ETHBTC',
     side: 'buy',
     quantity: 12,
     type: 'market',
     timeInForce: 'FOK',
     lastQuantity: 0,
     lastPrice: '',
     leavesQuantity: 0,
     cumQuantity: 0,
     averagePrice: '0',
     created: 1504120583517,
     execReportType: 'rejected',
     orderRejectReason: 'orderExceedsLimit' } } 'N/A' undefined undefined

**Comment by g666nz** [comment]
var amount = 0.012

hitbtc.createMarketBuyOrder(cuPa, amount).then (ob => {
              console.log(ob, ob.info, ob.id, ob.info.price, ob.info.exchange);
              self.json({status:ob});
            });

**Comment by g666nz** [comment]
var cupa = "ETH/BTC"

**Comment by kroitor** [comment]
![hitbtcprices](https://user-images.githubusercontent.com/1294454/29891046-676fdd3e-8dd2-11e7-9681-5645bc6dcf90.jpg)

From the above screenshot you can see, that they demand quantity in lots. So the ccxt library converts your amount (order quantity) to lot units. For ETH/BTC HitBTC has lot size of 0.001. So, 0.0012 / 0.001 = 12. The library calculates the quantity correctly. Now, the problem is that HitBTC still rejects the order. Can you try a slightly greater amount to see if it may be a floating point issue on their side? I mean an amount of, say, 0.0013 or 0.0015?

**Comment by kroitor** [comment]
Nope, forget about the quantity. It is large enough for it to be a precision issue.
Looking at your order, I can see it's FOK (Fill-Or-Kill), whereas HitBTC's default is GTC (Good-Til-Canceled). In your code I don't see you setting the execution type, so it may be a different piece of code. Can you try the default order execution type?

**Comment by kroitor** [comment]
Ok, latest findings show that HitBTC returns "orderExceedsLimit" when you don't have sufficient funds. Can you check your balance?

**Comment by g666nz** [comment]
Hi thanks for the quick response(s). Just checked have sufficient funds in hitbtc trading account.

**Comment by g666nz** [comment]
what is the default order execution. Without the callback??

**Comment by kroitor** [comment]
> HitBTC's default is GTC (Good-Til-Canceled).

Can you try it this way?

```JavaScript
hitbtc.createMarketBuyOrder(cuPa, amount, { 'timeInForce': 'IOC' }).then (ob => {
    console.log(ob, ob.info, ob.id, ob.info.price, ob.info.exchange);
    self.json({status:ob});
});
```

This will try to execute the order with IOC type (Immediate Or Cancel instead of FOK type).
Don't really see a reason for rejecting the order. Waiting for your report.

**Comment by kroitor** [comment]
You can also try this:

```JavaScript
hitbtc.createMarketBuyOrder(cuPa, amount, { 'timeInForce': 'GTC' }).then (ob => {
    console.log(ob, ob.info, ob.id, ob.info.price, ob.info.exchange);
    self.json({status:ob});
});
```

One of the above two snippets should work. Standing by to hear from you.

**Comment by g666nz** [comment]
ioc failed. Trying GTC :(
order type 'buy'
our input = 0.012 ETH/BTC
{ info: 
   { ExecutionReport: 
      { orderId: 'N/A',
        latestOrderId: 'N/A',
        clientOrderId: '1504123179',
        orderStatus: 'rejected',
        userId: 'user_432432',
        symbol: 'ETHBTC',
        side: 'buy',
        quantity: 12,
        type: 'market',
        timeInForce: 'IOC',
        lastQuantity: 0,
        lastPrice: '',
        leavesQuantity: 0,
        cumQuantity: 0,
        averagePrice: '0',
        created: 1504123180154,
        execReportType: 'rejected',
        orderRejectReason: 'orderExceedsLimit' } },

**Comment by kroitor** [comment]
Maybe you used a wrong keypair / keys for a different account? Because it really replies with *orderExceedsLimit* only when you don't have enough funds. Maybe you used a testing keypair?

**Comment by g666nz** [comment]
Really sorry for wasting your time. It was the wrong key pairs. So embarrassed. Thank you though, you helped with the TIME of FORCE suggestion

**Comment by kroitor** [comment]
Thx for reporting anyway! This can still be helpful to others as well.
