### ISSUE TITLE
$cryptopia->fetch_order_book() doesn't work in PHP

### ISSUE THREAD

**Issue by axis80** [kroitor/ccxt#165]
Calling $cryptopia->fetch_order_book() returns a timeout error.  The problem is related to how the URL is constructed.  Ccxt is calling this url:

https://www.cryptopia.co.nz/api/GetMarketOrders/{id}?market=9999

Whereas it is supposed to be calling this one:

https://www.cryptopia.co.nz/api/GetMarketOrders/9999

I would try to submit a fix but I don't entirely understand how parameters are supposed to be handled inside the $cryptopia->request method.

**Comment by kroitor** [comment]
Hi! Can you please show your code?
Because when I do this it works for me:

```PHP
include 'build/ccxt.php';
$id = '\\ccxt\\cryptopia';
$cryptopia = new $id ();
var_dump ($cryptopia->fetch_order_book ('ETH/BTC'));
```

**Comment by axis80** [comment]
Weird.  I did not save my previous code, but I rebuilt it as best as I could remember and now it is working for me also.  I must have done something wrong previously.  Thanks for your fast reply and apologies for submitting an incorrect issue report.  Thanks for a great piece of software!

**Comment by kroitor** [comment]
Thx for reporting back, anyway!
