### ISSUE TITLE
Формат данных

### ISSUE THREAD

**Issue by achievement008** [kroitor/ccxt#166]
Я верю, вы знаете русский. Во-первых, спасибо, очень нужную штуку делаете.
Некоторые проблемы доставляет разный формат возвращаемых данных с бирж, в частности балансы - c Poloniex {'used': 0.0, 'total': 0.0, 'free': 0.0}, c Bittrex {'used': None, 'total': None, 'free': None}. Использую библиотеку для python.

**Comment by kroitor** [comment]
Привет! 

Формат иногда разный, но ведь это документировано в мануале... None иногда нужно сохранять и не заменять на 0.0 принудительно, т.к. это дополнительный индикатор того, использовался ли баланс когда-либо ранее или ещё нет. 

А в чём проблема проверить None перед чтением? Ну, то есть, другими словами, зачем конвертировать это в библиотеке, если в Python-сообществе принято, чтобы всё было explicit? Не исключено, что в конце концов мы приведём всё к единому float-формату (возможно даже сейчас), но тогда ты должен привести какие-то весомые аргументы, почему эту проверку надо вносить внутрь библиотеки.

**Comment by achievement008** [comment]
Моё упущение - не прочитал до конца документацию, сразу начал использовать. Но хорошо отложилась в памяти строчка - "an out-of-the box unified all-in-one API extremely easy to integrate", в которой написано про унификацию, а по факту получается, что необходимо добавлять дополнительные проверки данных при подключении ещё одной биржи.

**Comment by kroitor** [comment]
Да нет, зачем же проверки, сделаем такой отдельный метод для получения нулевых балансов, не вижу в этом большой сложности, просто вопрос времени. Там ещё где-то написано было, что эта библиотека still under development, постараемся сделать этот метод быстрее.
Но по умолчанию строго для всех подряд обнулять не будем, т.к. всё зависит от того, кто зачем библиотеку использует. 

И да, формат данных общий, который подразумевает два типа значений в этом поле — одно другому не противоречит и тщательно документировано, не вижу здесь ничего скрытого. Вообще я не очень понимаю, как можно доверять деньги софту, не прочитав к нему мануал очень тщательно до конца. Видимо, все воспринимают риск по-своему ;)

Другое дело если лень самому конвертировать — это весомый для нас аргумент, т.к. мы делаем библиотеку, такое я вполне понимаю, и поэтому мы сделаем метод для получения с конверсией внутри, который всегда будет возвращать float, не проблема. Думаю, что сегодня.

**Comment by kroitor** [comment]
Решили не делать отдельный метод, привели все балансы к float'ам ) Теперь fetchBalance всегда возвращает float numbers. Достаточно обновиться до версии 1.5.55+, изменений в коде не требуется. Спасибо за фидбэк!
