### ISSUE TITLE
HITBTC and BITFINEX withdraw function errors

### ISSUE THREAD

**Issue by g666nz** [kroitor/ccxt#167]
Hi again, 
I'm trying to get the payment payout (withdraws api) of hitbtc to work. 

The api endpoint is:
Request: POST /api/1/payment/payout

my code:

hitbtc.privatePostPaymentpayout(amt, curr, add, function(data){
      console.log(data);
      cb(data);
    });
tried Payment/Payout/PaymentPayout none worked. 

the ERROR i get above is function does not exist. 

BITFINEX

bitfinex.privatePostWithdraw('bitcoin', 'exchange', 0.01, 'efqwef684fw18df1fyj8', function(data){
      console.log(data);
      cb(data);
    });

the function doesn't seem to be the problem. 
The error message i get is :
 {"message":"Key withdraw_type was not present."}

Any help would be appreciated. 
Br g666nz

**Comment by kroitor** [comment]
Hi! You're not using the API correctly, you should pass an associative dictionary of params to private calls, like so:
```JavaScript
bitfinex.privatePostWithdraw ({
    // your withdrawal key-value params
}).then (response => console.log (response))
```

<img width="971" alt="screen shot 2017-09-01 at 23 15 15" src="https://user-images.githubusercontent.com/1294454/29986294-79cd72f8-8f6b-11e7-8356-dec3919e8f85.png">

Same with HitBTC.

**Comment by kroitor** [comment]
https://bitfinex.readme.io/v1/reference#rest-auth-withdrawal
https://hitbtc.com/api#payout

**Comment by kroitor** [comment]
```JavaScript
bitfinex.privatePostWithdraw ({
    // your withdrawal key-value params
    'withdraw_type': 'bitcoin',
    'wallet_selected': 'exchange',
    'amount': 0.01,
    'address': 'efqwef684fw18df1fyj8',
}).then (response => console.log (response))
```

Same story for HitBTC...

Does that answer your question?

**Comment by g666nz** [comment]
yes i executed it wrong. bitfinex worked just checking hitbtc.

**Comment by kroitor** [comment]
For HitBTC you need a different set of params, but you should pass them in the same way, just make sure your param names and values correspond to their API docs (until we unify deposit/withdrawal methods, hopefully this month).

**Comment by g666nz** [comment]
yes that would be very helpful for idiots like me who make silly mistakes :D. one last question.

bitfinex.privatePostWithdraw 
what do i put instead of privatePostWithdraw

**Comment by kroitor** [comment]
The method you should be calling for HitBTC is paymentPostPayout:
```JavaScript
hitbtc.paymentPostPayout ({
    'amount': 0.01,
    'address': '... YOUR ADDRESS ...',
    'currency_code': 'HITBTC_CURRENCY_CODE',
})
```

**Comment by g666nz** [comment]
thank you good sir. Much appreciate the time you've taken out to help me. 

Br, 
g666nz

**Comment by kroitor** [comment]
For you future needs: you can see the full list of methods, properties and their names by simple doing this:

```JavaScript
console.log (hitbtc)
console.log (bitfinex)
```

**Comment by g666nz** [comment]
Sorry, But i'm still getting an error with hitbtc, i use the same api to get balance and it works. And i do have enough balance. Do you know what the problem could be?

Error: hitbtc POST http://api.hitbtc.com/api/1/payment/payout?nonce=1504298884&apikey=662d9186aafad907b8&amount=0.001&currency_code=BTC&address=1M4WLswbvabcT2E6qfAs8Tuknb3S9vSYWH 409 Conflict {"code":"InvalidArgument","message":"Balance not enough"}
(node:25692) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by g666nz** [comment]
I think it may be a wallet issue. I'm moving it from the trading to the main.

**Comment by g666nz** [comment]
yup that was the problem. Thank you again.

**Comment by kroitor** [comment]
To transfer between accounts within HitBTC use `hitbtc.paymentPostTransferToTrading ()` or `hitbtc.paymentPostTransferToMain ()`.

**Comment by g666nz** [comment]
yup found that usefull little tool using. 
`console.log (hitbtc)`

**Comment by pciavald** [comment]
Hi @kroitor, 
regarding the 2 commits added early september, can we use directly withdraw() on hitbtc's main account after using the following : 
```
  hitbtc.private_post_account_transfer({
   'currency': tx[0],
   'amount': tx[1],
   'type': 'exchangeToBank'
  }).then(res => {
    let timeout = 30;
    setTimeout(() => {
      hitbtc.withdraw(tx[0], tx[1], tx[2]).then(res => {
        log.log(JSON.stringify(res));
      }).catch(err => {
        log.log(err);
      });
    }, timeout * 1000);
  }).catch(err => {
    log.log(err);
  });
```
and I got the error : 
```
ReferenceError: InsufficientFunds is not defined
    at hitbtc2.handleErrors (node_modules/ccxt/js/hitbtc2.js:584:29)
    at response.text.then.text (node_modules/ccxt/js/base/Exchange.js:413:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kroitor** [comment]
@pciavald this is now fixed, please update ccxt to most recent version. Let us know if you still have difficulties with it after upgrading.

> IMHO the withdraw function should automagically transfer to main.

Thanks for the feedback! I'd say the transfer upon withdrawal should be optional (user-controlled).

**Comment by pciavald** [comment]
you're a crypto-divinity. Thank you very much.

About the option to transfer funds, the problem is that say you're working with 4 markets in an array, it's good to be able to iterate on the markets to withdraw with a single form of function. Because what makes the most sense is to trade (from trading) and withdraw (from main), i think the manual option should be to NOT transfer before withdrawing, and default to be like other exchanges.
Just my opinion though :)

**Comment by kroitor** [comment]
@pciavald thx for the feedback, we will reconsider this very carefully!

**Comment by pciavald** [comment]
Now I have this error : 

```javascript
hitbtc2.fetchBalance({ type: 'account' }).
```

```
privateGetAccountBalance
{ Error: hitbtc2 {"error":{"code":600,"message":"Action is not allowed","description":""}}
    at hitbtc2.handleErrors (/home/pciavald/Documents/cryptoforce/node_modules/ccxt/js/hitbtc2.js:1049:19)
    at response.text.then.text (/home/pciavald/Documents/cryptoforce/node_modules/ccxt/js/base/Exchange.js:424:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```

**Comment by kroitor** [comment]
@pciavald can you check permissions for that API key on HitBTC?

**Comment by pciavald** [comment]
actually it seems to be a problem currently with that exchange.
doing it manually is also refused in the interface.

**Comment by kroitor** [comment]
@pciavald they've introduced v2 recently and it may still be unstable... however, that particular call works normally on my side. Did you succeed to verify permissions on that key?

**Comment by pciavald** [comment]
createOrders, trading -> margin and withdraw from main work, only main -> trading doesn't

**Comment by pciavald** [comment]
and it used to work :P

**Comment by pciavald** [comment]
website says `Please note that ETH withdrawals are temporarily unavailable due to technical maintenance. Please accept our apologies for the inconvenience.`

**Comment by kroitor** [comment]
@pciavald no, I mean permissions ))

![permissions](https://user-images.githubusercontent.com/1294454/33965177-046c20c0-e06c-11e7-9f59-9f5d90cf5583.jpg)

However, if you say it used to work and then stopped, it may be caused by their maintenance indeed. Yet still, in your code above I don't see any rate limiting, you're doing transfer then withdraw almost immediately, do you use the built-in rate-limiter?

**Comment by pciavald** [comment]
all good on that side :)
![screenshot_20171213_231557](https://user-images.githubusercontent.com/3384097/33965292-a3a0e66e-e05b-11e7-837e-8d23bc767ab0.png)

**Comment by kroitor** [comment]
@pciavald can you reach it with a cors proxy?

```Javascript
let ccxt = new ccxt.hitbtc2 ({
    apiKey: '...',
    secret: '...',
    proxy: 'https://cors-anywhere.herokuapp.com/', // last slash critical
})
```

?

Also, is the issue with that call repeating consistently on your side if you try it several times consecutively?

**Comment by pciavald** [comment]
same result with proxy. where can I log all calls made to hitbtc2, maybe in hitbtc2.js ?

**Comment by pciavald** [comment]
do you have a slack ? :P

**Comment by kroitor** [comment]
> where can I log all calls made to hitbtc2, maybe in hitbtc2.js ?

Yep... you can also take a look at base/journal.js, however, that is not integrated yet (undocumented).

> do you have a slack ? :P

Nope, but we have a gitter )

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by kroitor** [comment]
@pciavald you ca also turn on verbose logging:

```
hitbtc.verbose = true
```

or

```
let hitbtc = ccxt.hitbtc2 ({ verbose: true, ... })
```

This will output all requests and responses in console.

**Comment by pciavald** [comment]
Yes so it really seems the exchange doesnt work at the moment.
```
hitbtc2 POST https://cors-anywhere.herokuapp.com/https://api.hitbtc.com/api/2/account/transfer 
Request:
 { Origin: '*',
  Authorization: 'Basic XXXX',
  'Content-Type': 'application/json' } {"currency":"ETH","amount":7.8236616,"type":"bankToExchange"}
{ Error: hitbtc2 {"error":{"code":600,"message":"Action is not allowed","description":""}}
    at hitbtc2.handleErrors (/home/pciavald/Documents/cryptoforce/node_modules/ccxt/js/hitbtc2.js:1046:19)
    at response.text.then.text (/home/pciavald/Documents/cryptoforce/node_modules/ccxt/js/base/Exchange.js:424:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) constructor: [Function: ExchangeError] }
```
