### ISSUE TITLE
Unified API: fetchOHLCV

### ISSUE THREAD

**Issue by 5an1ty** [kroitor/ccxt#169]
What's the status on fetchOLHCV, what exchanges are supported? I have experimented with Kraken and that works as expected but poloniex for example doesn't.

Even for exchanges that do not support an OHLC method, you could do the aggregation yourself based on the last X trades.

**Comment by kroitor** [comment]
Hi!

> What's the status on fetchOLHCV, what exchanges are supported?

Currently, it's under heavy development. We don't have the full support for OHLCVs, the work on this is in progress. We've added several experimental implementations of fetchOHLCV (for Kraken, OKCoin and some others), but we haven't implemented all of them yet. We will be happy if you could help us implement it where possible. Your PRs are welcome.

> Even for exchanges that do not support an OHLC method, you could do the aggregation yourself based on the last X trades.

Will do that, of course, after we have it fully implemented where it's supported.

If that answers your question, please close this issue. We hope to announce full support for OHLCV in 1.6+ (this month) and we will update you on our further progress here. 

Thanks!

**Comment by kroitor** [comment]
P.S. https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

**Comment by 5an1ty** [comment]
That's great to hear, thank you so much for your feedback. Unfortunately a bit too busy myself to actually help out developing, but looking forward to it!

Would be nice if you could also pass the amount of OHLC candles you would like to receive in a format like this:

kraken.fetchOLHCV(300, 200);

200 5 minute candles. This is especially interesting for indicators like macd, where you need to full history in order to create a correct macd signal.

Long periods 200, you would need at least 200 candles.

**Comment by kroitor** [comment]
> Would be nice if you could also pass the amount of OHLC candles you would like to receive

The unified signature of the fetchOHLCV method is as follows:
`async fetchOHLCV (market, timeframe = 60, since = undefined, limit = undefined, params = {})`
You can pass the `since` and `limit` params to fetchOHLCV already. But Kraken doesn't support the limit parameter within its API, so we will implement it over their API inside the library as well.

**Comment by kroitor** [comment]
We are now reworking the fetchOHLCV to accept timeframes as '1m', '5m', '1h', '1d' strings instead of interval duration in seconds. The method signature will soon change to:
`async fetchOHLCV (market, timeframe = '1m', since = undefined, limit = undefined, params = {})`

**Comment by kroitor** [comment]
https://github.com/kroitor/ccxt/search?p=1&q=fetchOHLCV&type=Commits&utf8=%E2%9C%93

**Comment by slidenerd** [comment]
Thanks!! Judging by a small test performed, it seems fetchOHLCV is also subject to exchange rate limits and cannot get the OHLC data for say 2 candles of all the pairs on an exchange, is there any method that can do this, trying to fetch ohlc of all pairs on any exchange
