### ISSUE TITLE
How to calculate VWAP for Bittrex

### ISSUE THREAD

**Issue by momostafa** [kroitor/ccxt#170]
Hello,

I hope someone help me giving a PHP example how to calculate VWAP for Bittrex and other exchanges that doesn't publish the VWAP within their API.

I have already tried many ways but I can't get it to work.

Thanks a lot

**Comment by kroitor** [comment]
Hi! For how far in past you want to calculate it? Bittrex only returns a few past trades, so there's no easy way to do that with Bittrex. 

You cannot calculate VWAP for 24h or for a longer period, unless you:
1. Set up a poller or many pollers to fetch Bittrex trades on frequently-regular basis
2. Store the data in a database
3. Run calculations over the stored data

For that you will need a system that is too big to be designed in a single GitHub issue. Basically, we cannot teach you how to code financial algorithms, we can only help to solve problems with using the library itself. If you can show your problematic code regarding the library (and you can minimize your problem case to a short snippet), we can help with that, but if you're asking "How to calculate VWAP?", I'm afraid, we cannot do technical-financial consulting or educational services for free. Sorry for that, closing this for now.

If you still have questions feel free to ask. Or if you post some code according to [this](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue) then, maybe we can work it out somehow.

**Comment by momostafa** [comment]
Dear Kroitor,

Thank you very much for your prompt and extensive reply I appreciate it. 
I already know the formula to calculate VWAP, I though that I am missing something around the library or Bitttrex API and didn't know that  Bittrex VWAP can only be achieved by setting up a poller which is an overkill for the application that I am building right now.

For now till Bittrex add this information or if I find an online API that can provide the VWAP I will relay on Typical price to determine the trend (High + Low + Last + PrevDay) / 4

Thanks again and have a nice day
