### ISSUE TITLE
HitBTC v2 API 

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#172]
hi, I found that version 1 api of hitbtc seems to be invalid.  maybe it's time support version 2 api. 

https://api.hitbtc.com/api/2/explore/

**Comment by kroitor** [comment]
Hi! Thanks! We will add this!

**Comment by HaoH** [comment]
hi, I was confused by hitbtc too. The official website link is pointing to v1, but it's invalid in my terminal and my aws (us-west)

![image](https://user-images.githubusercontent.com/2209077/30088828-68e8f2be-92db-11e7-8bd0-c10e4f55ee95.png)

but v2 is ok at the same time:
![image](https://user-images.githubusercontent.com/2209077/30088847-89106504-92db-11e7-9c9f-7cab61744469.png)

**Comment by kroitor** [comment]
@HaoH yep, and v1 works normally from our side and for most of ccxt users... 
And here they say, that v2 is in alpha-stage: https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md (as of Jun 6).
But don't worry, we almost have it done already. Hope to release soon.

**Comment by kroitor** [comment]
Ok, HitBTC v2 is available as of version 1.6.34+. So, I'm closing this for now.

@HaoH can you please try this short python snippet and report if it's working for you?

```Python
import ccxt
hitbtc = ccxt.hitbtc ()

def try_proxy(exchange, symbol, proxy=''):
    try:
        print('Trying', proxy if proxy else 'without proxy')
        hitbtc.proxy = proxy
        print(exchange.id, proxy, symbol, hitbtc.fetch_ticker(symbol), 'succeeded')
    except Exception as e:
        print(exchange.id, proxy, symbol, 'failed')

try_proxy(hitbtc, 'BTC/USD')
try_proxy(hitbtc, 'BTC/EUR', 'https://crossorigin.me/')
try_proxy(hitbtc, 'ETH/BTC', 'https://cors-anywhere.herokuapp.com/')
```

If I recall correctly, you are from China (and you're using Python afaik), so we need to know whether HitBTC blocks certain regions of China. It would be very helpful us and very important to other users of ccxt from your country if you do the proxy-test and report back here. Thx in advance!

**Comment by HaoH** [comment]
ok, thank you very much!  here is my test results:

python 3.6  + ccxt 1.4.83

![image](https://user-images.githubusercontent.com/2209077/30095706-d178ca90-9306-11e7-90bc-3f28d63afefe.png)

**Comment by kroitor** [comment]
Thx! As we thought, they really block some Chinese regions. Sorry for that, we cannot work around it unless you use a proxy or another server.

**Comment by HaoH** [comment]
@kroitor ok, I got it. Thank you very much!
