### ISSUE TITLE
Fatal error: Uncaught Error: Class 'cxxt\Exchange'

### ISSUE THREAD

**Issue by smatiush** [kroitor/ccxt#173]
my code is:
```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL | E_STRICT);
include "ccxt.php";
var_dump (\cxxt\Exchange::$exchanges); 
?>
```
but my server give me an error:
Fatal error: Uncaught Error: Class 'cxxt\Exchange' not found in /var/www/html/trading bot/prova.php:6 Stack trace: #0 {main} thrown in /var/www/html/trading bot/prova.php on line `6```

**Comment by kroitor** [comment]
See: https://github.com/kroitor/ccxt/tree/master/examples/php

There's only one simplest PHP example there, but we hope to extend PHP examples with your help )

If this does not work...

```PHP
<?php
include 'ccxt.php';
$exchanges = \ccxt\Exchange::$exchanges;
echo 'Supported exchanges: ' . implode (', ', $exchanges);
?>
```

... then let us know your PHP version and your ccxt version )

**Comment by kroitor** [comment]
Also, check your path to ccxt.php, you should link against ccxt_folder/build/ccxt.php not against ccxt_folder/ccxt.php.

**Comment by kroitor** [comment]
Here's my output:

```shell
mbp:ccxt igorkroitor$ php --version
PHP 5.6.30 (cli) (built: Feb  7 2017 16:18:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
mbp:ccxt igorkroitor$ php -a
Interactive shell

php > include 'build/ccxt.php';
php > $exchanges = \ccxt\Exchange::$exchanges;
php > echo 'Supported exchanges: ' . implode (', ', $exchanges);
Supported exchanges: _1broker, _1btcxe, anxpro, binance, bit2c, bitbay, bitbays, bitcoincoid, bitfinex, bitfinex2, bitflyer, bitlish, bitmarket, bitmex, bitso, bitstamp, bittrex, bl3p, btcchina, btce, btcexchange, btcmarkets, btctradeua, btcturk, btcx, bter, bxinth, ccex, cex, chbtc, chilebit, coincheck, coinfloor, coingi, coinmarketcap, coinmate, coinsecure, coinspot, cryptopia, dsx, exmo, flowbtc, foxbit, fybse, fybsg, gatecoin, gdax, gemini, hitbtc, hitbtc2, huobi, itbit, jubi, kraken, lakebtc, livecoin, liqui, luno, mercado, okcoincny, okcoinusd, okex, paymium, poloniex, quadrigacx, quoine, southxchange, surbitcoin, therock, urdubit, vaultoro, vbtc, virwox, xbtce, yobit, yunbi, zaif
php > exit
mbp:ccxt igorkroitor$ 
```

**Comment by smatiush** [comment]
i do not know if it can help you but this is my php version
`coin@coin-pc:~$ php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
 with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
`
now all work fine thank you!

**Comment by smatiush** [comment]
ccxt version = 1.6.42

**Comment by kroitor** [comment]
Thx for reporting back!

**Comment by jjhesk** [comment]
huobi has a new logo
<img width="173" alt="2018-04-06 4 34 14" src="https://user-images.githubusercontent.com/629338/38410936-7ab417ce-39b8-11e8-9404-bcb33b058058.png">

**Comment by kroitor** [comment]
Will update shortly, thx!
