### ISSUE TITLE
is there any GUI version of this project?

### ISSUE THREAD

**Issue by yanbosmu** [kroitor/ccxt#177]
is there any GUI version of this project?

**Comment by kroitor** [comment]
No, this is not a standalone tool for end-user trading, it's a library for programming the trading, but it doesn't offer a GUI interface on its own, it only has programmatic and command-line interfaces for developers and coders.

**Comment by xpl** [comment]
But the good news are: we're working on it! Coming this fall. Will be available as mobile app / [PWA](https://en.wikipedia.org/wiki/Progressive_web_app).

Stay tuned.

![slack-imgs](https://user-images.githubusercontent.com/1707/30171658-4353cdb4-93fb-11e7-8bcc-19dfb072a62f.jpg)
