### ISSUE TITLE
BUG : Bitfinex wallet balance Dash

### ISSUE THREAD

**Issue by g666nz** [kroitor/ccxt#178]
So there is a slight problem. From bitfinex info side the currency value comes as 'dsh' for 'Dash' and the aggregated part at the bottom dash is marked as DASH. And not showing the user dash amount. You can see below in the image.

![ccxt](https://user-images.githubusercontent.com/11820270/30169975-73dd5c56-940b-11e7-8d15-e1571c08c154.png)

**Comment by g666nz** [comment]
i updated ccxt, the undefined issue has been resolved but, Dash is still causing a problem.

**Comment by kroitor** [comment]
Thx for posting this, will fix very soon!

**Comment by kroitor** [comment]
Ok, this bug should be fixed as of 1.6.53+. Let us know if you still have any problems with bitfinex balance, though, it should be working normally as far as we tested it... Thx for reporting!

**Comment by g666nz** [comment]
Yup just tested, all working well. No thank you for your help.
