### ISSUE TITLE
From/to unified pair name/exchange specific name

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#18]
I'd like in unified API having two functions which map from unified names (e.g. BTC/EUR) to market specific name and back (e.g. BTCEUR for kraken IIRC). 

This will help me test your library further and detect subtle errors.

I recommend names:
```
to_market_api_name(self, symbol)
to_unified_name(self, symbol)
```

They should throw exception of not found in the exchange load products. It should use cached ```load_products()```

This functionality is implemented somewhere anyhow, it's only about exposing it.

**Comment by nmiculinic** [comment]
Furthemore, this should simplify unit tests for pair name conversion (since I think there are still issues with this)

**Comment by kroitor** [comment]
Hey! Thanks again for feedback, it's very constructive. Sure, I will expose the mapping.
In fact one half of that mapping (symbol → product id → symbol) is already there:

```Python
symbol = 'BTC/USD'
print (market.products[symbol]['id']) # print product id by symbol
print (market.productId (symbol)) # same as previous line
product = market.product (symbol) get a full product dictionary by symbol
print (product['id']) # same as previous output
```

I will expose the other half, sure! Will upload this soon.

**Comment by kroitor** [comment]
Though, the existing mapping does not throw errors, but returns the input string untouched. I will update that part of the interface anyway.

**Comment by kroitor** [comment]
This feature will soon be ready, btw, [Product Ids And Symbols](https://github.com/kroitor/ccxt/wiki/Manual#product-ids-and-symbols). The Manual is frequently updated, I'm adding more and more details into it, so it's worth revisiting from time to time. I will also update it and add the two methods proposed here very soon.

**Comment by kroitor** [comment]
I've uploaded the interface to products, product symbols and product ids.
Here's how to use it:
```Python
import ccxt
k = ccxt.kraken ()
k.load_products ()

# symbol → product
k.products['BTC/USD']

# id → product
k.products_by_id['XXRPZUSD']

# symbol → id
k.products['BTC/USD']['id']

# id → symbol
k.products_by_id['XXRPZUSD']['symbol']
```

No functions, basic dictionaries indexed by appropriate fields. The are cached and can be force-reloaded if necessary.

You will get a user-land exception if you access non-existent keys in these dicts.
I hope the above solution simplifies the usage, closing this issue down now. Will soon add that to the Manual.

**Comment by kroitor** [comment]
Update: It's in [The Manual](https://github.com/kroitor/ccxt/wiki/Manual#product-ids-and-symbols) now.
