### ISSUE TITLE
liqui: symbols are not unified

### ISSUE THREAD

**Issue by mkutny** [kroitor/ccxt#182]
Hi, guys, this library is awesome!

Playing with different exchanges have found that `ccxt` doesn't unify symbols for Liqui:
```
> liqui.fetchOrderBook('BTC/USD');
> (node:13656) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: liqui {"success":0,"error":"Invalid pair name: undefined"}
```

Fetching 'BTC/USDT' works.

**Comment by kroitor** [comment]
Hi! Are you sure? Because we can't find BTC/USD on Liqui at all. Their API endpoint that returns the list of currently active markets with Liqui returns this: https://api.liqui.io/api/3/info.
And there's no such pair as BTC/USD at all.
Here's the full list: https://gist.github.com/kroitor/b377871705dec4d9f301e4aaf18d6da1

**Comment by kroitor** [comment]
We mean, Tether USD is not the same as USD, or is it?

**Comment by mkutny** [comment]
Hmm...
I just assumed that if an exchange trades only USDT (e.g. w/o USD) it would be convenient to abstract it to plain USD.

But now I think that such abstraction will leak on exchanges with USDT/USD pairs.

Thanks!

**Comment by kroitor** [comment]
Thx for posting this issue anyway! Feel free to ask if you have any other questions, we will be happy to help!

**Comment by ManuelSchneid3r** [comment]
> We mean, Tether USD is not the same as USD (to us BTC/USD and BTC/USDT are different pairs that should not be unified), or is it the same?

Sure they are not the same, technically, but in theory they have the same value. Some exchanges report USD although they are using USDT. Its only different when it comes to withdrawals. Best example: Bitfinex. It shows my dust dollars as USD in the wallets. The markets are USD, in the withdrawal section as USDT.

Please unify the names to either USD or USDT.

**Comment by kroitor** [comment]
@ManuelSchneid3r Kraken has both USD and USDT for withdrawal and trading.
