### ISSUE TITLE
Fetch open orders-Bittrex

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#183]
When calling Bittrex's `fetch_open_orders()` method I get this:
```
[{'amount': 0.15798328,
    'datetime': '2017-09-05T01:59:32.000Z',
    'id': '***',
    'info': ...,
    'price': 0.0,
    'remaining': 0.15798328,
    'side': 'buy',
    'status': 'open',
    'symbol': ['symbol'],
    'timestamp': 1504576772000,
    'type': 'limit'}]
```
So there seems to be a typo when searching for `symbol` in order.

**Comment by marinsokol5** [comment]
One more thing actually.
Poloniex in `fetch_open_orders()` for key `amount` returns string and I guess we should be expecting a float.

And while we are at it.
It says in the wiki `amount = amount of base currency`.
Is that the remaining volume or the initial?

All the best.

**Comment by kroitor** [comment]
@marinsokol5 , hi!

Thx as always for your feedback! 
The bittrex symbol typo is now fixed, and the amount in poloniex is also fixed as float as well.
As for your question, it's the initial amount, we will clarify this in the Manual.
We will probably also add the remaining amount to orders, these methods are not fully unified yet (working on it).

Thx again, let us know if you have any other questions!

**Comment by marinsokol5** [comment]
Could you turn Poloniex's `price` into float too.
Sorry i somehow missed it the first time.

Also thank you for the answer.
My suggestion would be to use the `'amount'` key for current volume of the order.
Becouse some exchanges only send you the current volume of the order not the initial amount(Bitstamp that i've seen) and becouse it is the one that is the most important .
It doesn't matter that much what was the initial volume of the open order.
If some exchanges do provide that info than that's where i would put it.
As one the keys under `'info'`.

**Comment by kroitor** [comment]
@marinsokol5 , ok, poloniex is also forced to float now )

> My suggestion would be to use the 'amount' key for current volume of the order.
> Becouse some exchanges only send you the current volume of the order not the initial amount(Bitstamp that i've seen) and becouse it is the one that is the most important .
It doesn't matter that much what was the initial volume of the open order.
If some exchanges do provide that info than that's where i would put it.
As one the keys under 'info'.

We think we will have three fields in the order structure:
```
amount    // initial amount
filled    // how much was partially or fully closed
remaining // remaining unsettled amount
```

These will be always present in the order, so we will provide all of them, and you will then choose whatever amount you want of these three. As for the naming of these fields – we are still thinking about it, but to us naming them as `amount, filled, remaining` makes sense and looks consistent with other usages of the `amount`-word throughout the library. If you don't mind that naming scheme and you just want to have the remaining amount under whatever name it is – you will have it )
