### ISSUE TITLE
'side' may become empty string on bitFlyer

### ISSUE THREAD

**Issue by hrtshu** [kroitor/ccxt#184]
'side' of trade may become empty string on bitFlyer. For example,
https://api.bitflyer.jp/v1/executions?product_code=FX_BTC_JPY&count=1&before=182898
returns:
```json
[
  {
    "id": 182897,
    "side": "",
    "price": 51365,
    "size": 0.001,
    "exec_date": "2015-12-12T16:01:12.643",
    "buy_child_order_acceptance_id": "JRF20151213-004335-411320",
    "sell_child_order_acceptance_id": "JRF20151212-040106-913565"
  }
]
```

bitFlyer somtimes do [itayose](http://www.investopedia.com/terms/i/itayose.asp) (peculiar to Japan?) after bitFlyer maintains the system. So the trades completed by itayose have no any sides. This is explaind in bitFlyer's [Japanese](https://lightning.bitflyer.jp/docs?lang=ja#約定履歴) API documentation, but not in [English version](https://lightning.bitflyer.jp/docs?lang=en#execution-history).

So `ccxt.bitflyer().fetch_trades(symbol='FX_BTC_JPY', params={'before': 182898, 'count': 1})` fails with exception. In current commit (12283cb2964349db780afc502eb52cb8a29a3c4c), this wrong point is line 2536 of [ccxt/exchanges.py](https://github.com/kroitor/ccxt/blob/12283cb2964349db780afc502eb52cb8a29a3c4c/ccxt/exchanges.py). I think line 2536 should be deleted.

**Comment by kroitor** [comment]
Hi! Thx for your feedback! This is fixed and should be working in new version 1.6.71+.
Please upgrade to latest ccxt version and report please if the problem still persists. Thx again!
