### ISSUE TITLE
Hitbtc limit order problem

### ISSUE THREAD

**Issue by g666nz** [kroitor/ccxt#185]
Hi again,
So i'm trying to place a limit order with hitbtc. But i keep getting this error

THE ERROR:
TypeError: "%.10f".sprintf is not a function
    at /home/g666nz/Desktop/currycoinsV/currycoin0 .5/Applications/userServer/node_modules/ccxt/build/ccxt.es5.js:15536:46
    at process._tickCallback (internal/process/next_tick.js:103:7)

THE CODE:

`try{
                    let ob = await newOrder[exc].createLimitBuyOrder ("ETH/BTC", 0.141, 0.071, { 'timeInForce': 'FOK' });
                    console.log(ob, ob.info, ob.id, ob.info.price, ob.info.exchange);
                    self.json({status:ob});
                }catch(err){
                    console.log(err);
                    self.json({status:'fail'});
                }`

Any idea what i'm doing wrong??

**Comment by kroitor** [comment]
Hi! Thx for reporting this! It's a formatting bug and it it now fixed in version 1.6.72+.
Sorry for the inconvenience and, as always, thx for your feedback! We really appreciate it!
