### ISSUE TITLE
Simple error

### ISSUE THREAD

**Issue by dservais** [kroitor/ccxt#188]
Hi Igor, thanks for the great dev you are managing.

On Python, I have this little error I do not understand why it dosen't work

# -*- coding: utf-8 -*-
import ccxt  # noqa: E402

def print_ticker(exchange, symbol):
    ticker = exchange.fetch_ticker(symbol)

thelist = ccxt.exchanges
i = 0

while i < len(thelist):
    print_ticker(thelist[i],'BTC/ETH')

causing error:
 File "C:/Users/serva/Google Drive/Crypto/CCXT/testtick.py", line 11, in <module>
    print_ticker(thelist[i],'BTC/ETH')
  File "C:/Users/serva/Google Drive/Crypto/CCXT/testtick.py", line 5, in print_ticker
    ticker = exchange.fetch_ticker(symbol)
AttributeError: 'str' object has no attribute 'fetch_ticker'

Process finished with exit code 1

Can you please help
Best regards
Didier

**Comment by xpl** [comment]
This is because that `ccxt.exchanges` property contains exchange IDs, not exchanges themselves.

To connect to an exchange and start trading you need to instantiate an exchange class, as shown in the manual here: [Instantiation](https://github.com/kroitor/ccxt/wiki/Manual#instantiation)

Also, please see this example here: [`exchanges.py`](https://github.com/kroitor/ccxt/blob/master/examples/py/exchanges.py)

**Comment by kroitor** [comment]
@dservais, the answer by @xpl is correct, you should instantiate from ccxt each exchange class you want to connect with:

```Python
# -*- coding: utf-8 -*-

import ccxt  # noqa: E402

exchanges = {}
symbol = 'BTC/USD'

for id in ccxt.exchanges:
    print('---------------------------------------------------------------')
    print(id)
    try:
        exchange = getattr (ccxt, id) () # instantiate
        exchange.load_markets () # preload all symbols for this exchange
        if symbol in exchange.symbols:
            print (exchange.fetch_ticker (symbol))
        else:
            print (id, 'does not offer', symbol, 'pair')
    except Exception as e:
        print(type(e).__name__, e.args)

```

Please, note, that not all exchanges (only some of them) support BTC/USD pair, other exchanges just don't have/offer it.
