### ISSUE TITLE
How to view real-time last price data in Python

### ISSUE THREAD

**Issue by gregsifr** [kroitor/ccxt#189]
How to view last price data (using websockets) in Python? I wasn't able to find any python websocket examples here: https://github.com/kroitor/ccxt/tree/master/examples/py

The library looks fantastic btw, great stuff

**Comment by kroitor** [comment]
Hi!

Thx for your feedback!

According to the [Manual](https://github.com/kroitor/ccxt/wiki/Manual):
> Full public and private HTTP REST APIs for all exchanges are implemented. WebSocket and FIX implementations in JavaScript, PHP, Python and other languages coming soon.

Streaming is a very wanted feature, of course. We have announced the work on WebSocket support already) We will update you when this is available, in the meantime I'm closing this issue as a duplicate. Hope to deliver this September. Stay tuned )
