### ISSUE TITLE
Bitfinex private api 

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#19]
Im using python 3.6 and im using your latest version.

https://pastebin.com/VkNzP8s5

`print(bitfinex.get_transaction_fee())`

you can initialize a bitfinex variable with this 
 'apiKey' : '3dnKaqxXEx7ETa83d2vnOeJRtrQcpPx8N5JomCYTmoS',
    'secret' : '3Ab5LGcSXGUlMSMtBcWsdgFyPoG5VTZasv9rmyVYEYP'

When I try to call method request in class bitfinex for a private post method it fails with an error:
TypeError: a bytes-like object is required, not 'str' in line
1705 :           ` payload = base64.b64encode (self.json (query))` 

I hvae tried encoding it and then in 
  `  'X-BFX-SIGNATURE':` self.hmac (payload.decode(), self.secret, hashlib.sha384),` 
putting decode in payload and it works.

**Comment by kroitor** [comment]
Thank you for reporting this! I will fix it very soon!

**Comment by Jircs1** [comment]
👍
