### ISSUE TITLE
API to fetch supported currencies

### ISSUE THREAD

**Issue by millette** [kroitor/ccxt#190]
For the exchanges that provide it (I'm guessing most should). For example <https://bittrex.com/api/v1.1/public/getcurrencies>

It should also be possible to obtain the list of currencies as tickers, although this would mean more bandwidth is used.

**Comment by kroitor** [comment]
Hm... Sorry? Can you explain, please?
https://github.com/kroitor/ccxt/wiki
https://github.com/kroitor/ccxt/wiki/Manual#exchange-properties
https://github.com/kroitor/ccxt/wiki/Manual#markets

**Comment by millette** [comment]
I'm just starting to learn about the project, didn't notice a list of currencies. If it's already available, no need to duplicate it - a list of pairs is just as good.

Perhaps as I start to use ccxt, I'll have more appropriate requests. Thanks for the quick response and feel free to reopen this ticket if that's preferable.

**Comment by kroitor** [comment]
Thx for your feedback anyway, we will be happy to help if you have any other questions )
