### ISSUE TITLE
huobi need to add BCH/ETH/ETC markets

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#195]

**Comment by kroitor** [comment]
Working on it! )

**Comment by kroitor** [comment]
To fix this, we will have to add Huobi v1 support, so current implementation (v3) will be renamed to huobi3, and huobi will be v1. It so happens that Huobi v1 is newer than Huobi v3. )

**Comment by 86chenjie** [comment]
test all 7 markets. all works. 👍
