### ISSUE TITLE
okcoincny need to add BCH/ETH/ETC markets

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#196]

**Comment by kroitor** [comment]
It's so sad they don't have an API for fetching all markets at once... All developers have to hardcode it... We'll put a watchdog on chinese exchanges to check when their markets are updated.
I'll add missing symbols to okcoin as well, of course.

**Comment by 86chenjie** [comment]
thanks!  👍

**Comment by kroitor** [comment]
Ok, these markets have been added to OKCoin CNY in version 1.6.100+. Thanks for updating us on this. Let us know if you have any difficulty with it.

**Comment by 86chenjie** [comment]
test BCH/ETH/ETC, all work fine. 👍
