### ISSUE TITLE
chbtc need to add BCH/QTUM/HSR markets, remove EOS market

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#197]

**Comment by kroitor** [comment]
Will do, thx a lot!

**Comment by kroitor** [comment]
I added missing markets to CHBTC, and they should be working in 1.6.101+.

But I have a question... Are you sure about deleting EOS? Because, when we fetch it, it still works normally. Other users might still need it ) Will be waiting for your reply on this.

**Comment by 86chenjie** [comment]
chbtc remove EOS from trading. Can you check the orderbook timestamp  of EOS? i think it should be days ago. Keep EOS is fine for me.

**Comment by 86chenjie** [comment]
the timestamp do change, but the asks/bids data stay the same.

**Comment by 86chenjie** [comment]
http://api.chbtc.com/data/v1/depth?currency=eos_cny&size=3&merge=0.1

**Comment by kroitor** [comment]
Ok, I see. We will remove it then, thanks for the info.

**Comment by 86chenjie** [comment]
test BCH/QTUM/HSR. work fine. 👍
