### ISSUE TITLE
Unable to cancel order on bitfinex

### ISSUE THREAD

**Issue by maayank** [kroitor/ccxt#199]
Unable to cancel order on Bitfinex. Canceling consistently results in:
bitfinex POST https://api.bitfinex.com/v1/order/cancel 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting

Other commands instead of the canceling work fine.

**Comment by kroitor** [comment]
Hi! Can you please turn on [verbose mode](https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting) and paste your entire output here?

**Comment by maayank** [comment]
I'm not sure which fields contain sensitive information behind the API key, so if you need one of them and it's not sensitive say so and I'll post.

('https://api.bitfinex.com/v1/order/cancel', 'POST', 'https://api.bitfinex.com/v1/order/cancel', '\nRequest:', {'User-Agent': 'ccxt/1.6.102 (+https://github.com/kroitor/ccxt) Python/2.7.13', 'X-BFX-PAYLOAD': u'...', 'X-BFX-APIKEY': '...', 'Accept-Encoding': 'gzip, deflate', 'X-BFX-SIGNATURE': '...'}, None)

And the full call stack:

Traceback (most recent call last):
  File "local_arbit.py", line 193, in <module>
    done = execute_until_done('buy', buy_price, volume, TIMEOUT)
  File "local_arbit.py", line 126, in execute_until_done
    res = exchange.cancel_order(txid)
  File "build/bdist.macosx-10.12-x86_64/egg/ccxt/exchanges.py", line 2149, in cancel_order
  File "build/bdist.macosx-10.12-x86_64/egg/ccxt/exchanges.py", line 2262, in request
  File "build/bdist.macosx-10.12-x86_64/egg/ccxt/exchange.py", line 258, in fetch
  File "build/bdist.macosx-10.12-x86_64/egg/ccxt/exchange.py", line 193, in raise_error
ccxt.errors.ExchangeNotAvailable: bitfinex POST https://api.bitfinex.com/v1/order/cancel 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting,UYVM-.NLOURNT/JI-LQ(/IQHJUHS+IMO-S}/0)

**Comment by kroitor** [comment]
Ok, this should be fixed in version 1.6.105+. It will be available for downloading in a couple of minutes. Please update and check if it all works normally for you. We will be happy if you report back whether it's ok or not. Thanks again!

**Comment by maayank** [comment]
Works great! Many thanks!

**Comment by kroitor** [comment]
@maayank awesome, respect!

**Comment by PhinixPhire** [comment]
I'm getting a similar error when withdrawing...

ccxt.errors.ExchangeNotAvailable: bitfinex POST https://api.bitfinex.com/v1/withdraw 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, 

Is this related?

**Comment by kroitor** [comment]
@PhinixPhire hi! It's hard to tell without some more details form you. Can you post a code snippet showing how you call withdraw and the output of it in verbose mode?

**Comment by PhinixPhire** [comment]
Hi Igor!

That portion of the code looks like this:

    print "Suggested withdrawals: "
    for x in distribution:
        print "Send " + str(x[0]) + " BTC from " + x[1] + " to " + x[2]
        for y in exchange_list: #Tuple of exchanges called from ccxt
            time.sleep(10)
            if y.id == x[1]: #Checking for .id match with distribution
recommendations
                print "y.withdraw('BTC', '" + str(x[0]) + "', " + "'" +
x[3] + "')"
                #proceed = raw_input("Pausing for safety. Proceed?")
                #y.withdraw('BTC', x[0], x[3])
                y.withdraw('BTC', 0.001, x[3])  #Lowered withdrawal from
suggestion for sake of safety

My verbose output has this to add:

('https://api.bitfinex.com/v1/withdraw', 'POST', '
https://api.bitfinex.com/v1/withdraw', '\nRequest:', {'User-Agent':
'ccxt/1.9.37 (+https://github.com/kroitor/ccxt) Python/2.7.14',
'X-BFX-PAYLOAD': [REMOVED]', 'X-BFX-APIKEY': '[REMOVED]',
'Accept-Encoding': 'gzip, deflate', 'X-BFX-SIGNATURE': '[REMOVED]'}, None)
Traceback (most recent call last):
  File "[REMOVED].py", line 108, in <module>
    distributeFunds()
  File "[REMOVED].py", line 102, in distributeFunds
    distributeBTC()
  File "[REMOVED].py", line 99, in distributeBTC
    y.withdraw('BTC', 0.001, x[3])
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 2389, in
withdraw
    }, params))
  File "C:\Python27\lib\site-packages\ccxt\exchanges.py", line 2424, in
request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 225, in fetch2
    return self.fetch(request['url'], request['method'],
request['headers'], request['body'])
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 263, in fetch
    self.handle_rest_errors(e, e.code, text, url, method)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 311, in
handle_rest_errors
    self.raise_error(error, url, method, exception if exception else
str(http_status_code), details)
  File "C:\Python27\lib\site-packages\ccxt\exchange.py", line 210, in
raise_error
    details,
ccxt.errors.ExchangeNotAvailable: bitfinex POST
https://api.bitfinex.com/v1/withdraw 400 Bad Request  (possible reasons:
invalid API keys, bad or old nonce, exchange is down or offline, on
maintenance, DDoS protection, rate-limiting,



Let me know if I "[REMOVED]" any pertinent information to troubleshooting.

Thanks!

Phinix

**Comment by PhinixPhire** [comment]
Oh, and I've tried setting the nonce on the offending exchange:

bitfinex = ccxt.bitfinex({
    'apiKey': '[REMOVED]', 
    'secret': '[REMOVED]',
    'password': '[REMOVED]', #Might not be needed...
    'nonce': ccxt.Exchange.milliseconds,
    'verbose': True
    })

The code seems to work on other exchanges so far... 

Thanks again!

**Comment by kroitor** [comment]
@PhinixPhire you sure you can withdraw 0.001 BTC from Bitfinex manually? Exchanges usually have a higher boundary on minimal withdraw... Can you withdraw the same amount with Bitfinex website? Would be nice if you report on that. I don't have a balance with Bitfinex right now, but I will put something there to test it again soon. Or maybe we could resolve it quicker with more info from you.

**Comment by PhinixPhire** [comment]
Yep, it seems I can withdraw 0.001. I just executed one from the site. They charge 0.0005, so it's not exactly smart to withdraw that amount... but it works. Earlier I was having trouble with 0.01 BTC as well, for the record. Same error.

**Comment by kroitor** [comment]
@PhinixPhire ok, thx, I'll take a deeper look into it asap.

**Comment by kroitor** [comment]
@PhinixPhire oh, btw, there are multiple types of accounts with Bitfinex, what type of account do you want to withdraw from? Is it “trading”, “exchange”, or “deposit”?

**Comment by PhinixPhire** [comment]
On the site it's Exchange, Margin and Funding. I would like to use
exchange.

I'm en route to a Gorillaz concert, so I'll be checking emails but possibly
delayed in response. Excuse me in advance if so.

**Comment by kroitor** [comment]
Can you please try this line instead and report: `y.withdraw('BTC', 0.001, x[3], {'walletselected': 'trading'})`?

**Comment by kroitor** [comment]
where x[3] is the destination address... have you checked the value in it? can you hardcode an address as a string just to see if that is the case? also, does your keypair have a withdraw permission? It's disabled on their website by default when new keys are created, can you check for that as well?

**Comment by PhinixPhire** [comment]
Yes, it's a valid address. I've tried hardcoded in a test script too.
Withdrawal is definitely enabled on the keypair. I issued a new pair to
check that my key was functional too.

I expect your suggestion above of specifying the wallet will work. I'll let
you know as soon as I get home.

Thanks so much!

**Comment by kroitor** [comment]
@PhinixPhire if it works for you, I'll make it a default for Bitfinex v1. Will be waiting to hear from you. Thx!

**Comment by PhinixPhire** [comment]
@kroitor 

Well I'll be... I'm still getting the error even when including {'walletselected': 'trading'} ... 

This: 

print bitfinex.withdraw('BTC', 0.001, '19qAGRERXqa9Pe3QvKvKZbRjiSxEyXFvkz', {'walletselected': 'trading'})

Results in:

ccxt.errors.ExchangeNotAvailable: bitfinex POST https://api.bitfinex.com/v1/withdraw 400 Bad Request  (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting, 

I get the same experience when testing with 0.01 BTC as well.

**Comment by kroitor** [comment]
@PhinixPhire ok, thanks for letting me know, I'll check it further and retest it with my own depo/withdraw to see what's going on. I'll get back to you on this, hopefully, soon.

**Comment by PhinixPhire** [comment]
Thanks, @kroitor! I look forward to your findings. In the meantime I'll have to work around Bitfinex withdrawals.

**Comment by kroitor** [comment]
In case someone stumbles upon this issue with HitBTC withdraw - it has been resolved in #286.
