### ISSUE TITLE
Bitfinex parse_order incorrectly assumes timestamp is float

### ISSUE THREAD

**Issue by maayank** [kroitor/ccxt#200]
I've encountered this when using fetch_order.
Casting order['timestamp'] to float before multiplying by 1000 and assigning to timestamp solves the issue.

**Comment by kroitor** [comment]
Thanks for opening this issue and for reporting, we will fix that asap!

**Comment by kroitor** [comment]
This is now fixed in version 1.6.104+. Thanks a lot for your feedback!
