### ISSUE TITLE
Nonce on Poloniex

### ISSUE THREAD

**Issue by Carlo-C** [kroitor/ccxt#203]
I testing follow line:
print (poloniex.fetch_order('BTC/USD'))
and Poloniex always return me:
 {"error":"Nonce must be greater than 1505453523869. You provided 1505455845."}

**Comment by kroitor** [comment]
Hello, @Carlo-C ! Did you set up your API keys for Poloniex according to [the Manual](https://github.com/kroitor/ccxt/wiki)? If you don't want to make a new keypair and you want to use old keys, you will have to redefine the nonce to use milliseconds.

https://github.com/kroitor/ccxt/wiki/Manual#authentication
https://github.com/kroitor/ccxt/wiki/Manual#api-keys-setup
https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce
https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

I hope that answers your question. If you don't mind I'm closing this issue as a duplicate, feel free to reopen it if you still have questions left, we will be happy to answer.

**Comment by kroitor** [comment]
P.S. Also, you're not using fetchOrder correctly, it accepts an order id, not a symbol. See the manual for details.

**Comment by Carlo-C** [comment]
ok Igor,
I made a new API Key and now work fine.
Thanks!
Carlo

2017-09-15 8:54 GMT+02:00 Igor Kroitor <notifications@github.com>:
