### ISSUE TITLE
Kraken: how to sell short (choose leverage) and cancel orders?

### ISSUE THREAD

**Issue by ThomasDolso** [kroitor/ccxt#204]
Hi,
thanks for your great project! I know it's possible to execute short orders but I can't figure out exactly how to do it. So could you please provide a quick example of i.e. short selling on Kraken? For example, using Python, is the following command working?

kraken.create_market_sell_order('BTC/USD', 1, {'leverage': 2})

So is it all about additional parameters? Also it's not clear to me how to close the order so even in this case an example would be really appreciated.

Thanks,
T

**Comment by kroitor** [comment]
Hi, @ThomasDolso ! 

Thanks for your feedback! We appreciate it!

As for your questions:

> I know it's possible to execute short orders but I can't figure out exactly how to do it. So could you please provide a quick example of i.e. short selling on Kraken? For example, using Python, is the following command working?
> kraken.create_market_sell_order('BTC/USD', 1, {'leverage': 2})

Yep, that should work.

The example:

```Python
import ccxt
kraken = ccxt.kraken({ 'apiKey': 'YOURKEY', 'secret': 'YOURSECRET')
order = kraken.create_market_sell_order('BTC/USD, 1, {'leverage': 2})
print(order) # should have an id
```

How to close the order later:

```Python
kraken.cancelOrder(order['id']) 
```

We would recommend to read [the Manual](https://github.com/kroitor/ccxt/wiki), it's all there )
So, if you don't mind, I'm closing this for now, feel free to ask if you have any other questions.

**Comment by ThomasDolso** [comment]
Thanks for your super-fast reply! So it seems it's all about additional parameters. 
Just in case someone else could be interested for Kraken (I know, it's more about Kraken rather than ccxt) I've just read that to close a short (or leveraged) position you have to user the 

ordertype = settle-position

parameter. So I guess you have to place another order (a BUY one if you're short) and not call the cancelOrder method.

Yes, please close this post. Thanks again!
Tom

**Comment by ThomasDolso** [comment]
Sorry, just tried the following command

order = kraken.create_market_sell_order('BTC/LTC', 0.01, {'leverage': '2:1'})

I'm getting the following error:

Traceback (most recent call last):
  File "test.py", line 39, in <module>
    order = kraken.create_market_sell_order('BTC/LTC', 0.01, {'leverage': '2:1'})
  File "/Users/tommy/py/_tests/tf/lib/python3.6/site-packages/ccxt/exchange.py", line 730, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
  File "/Users/tommy/py/_tests/tf/lib/python3.6/site-packages/ccxt/exchanges.py", line 12201, in create_order
    response = self.privatePostAddOrder(self.extend(order, params))
  File "/Users/tommy/py/_tests/tf/lib/python3.6/site-packages/ccxt/exchanges.py", line 12308, in request
    secret = base64.b64decode(self.secret)
  File "/Users/tommy/py/_tests/tf/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

Thanks,
T

**Comment by kroitor** [comment]
It says, that it's unable to decode your secret key. Did you copy it correctly?

**Comment by ThomasDolso** [comment]
Yes, my fault, sorry. Thanks a lot
T

**Comment by elgailhouste** [comment]
Is it possible to place or cancel multiple orders in one go?

**Comment by cgwebjunk** [comment]
Is it possible to place or cancel multiple orders in one go?

**Comment by samgermain** [comment]
@kroitor There actually nothing in the manual that shows how to trade with leverage. The word leverage shows up 3 times, and the one time it's within some code, is when the manual is talking about a structure for a response by the exchange

**Comment by kroitor** [comment]
@samgermain it's documented here:
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://docs.kraken.com/rest/#operation/addOrder
