### ISSUE TITLE
Poloniex and Kraken Private API

### ISSUE THREAD

**Issue by poogoo** [kroitor/ccxt#21]
Error when calling private methods for Poloniex and Kraken exchanges.
(Using Python 3.6.0 with latest ccxt commit)

When calling Poloniex private api getting an error:

"poloniex POST https://poloniex.com/tradingApi 422  b'{"error":"Nonce must be greater than 15001320050000. You provided 1500132345."}'"

No problems after editing ccxt   __init__.py to increase nonce value:
`query['nonce'] = self.nonce () * 10000`
(in request function for poloniex)

When calling Kraken private api getting an error:

`  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 7178, in fetch_balance
    return self.privatePostBalance ()
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 7203, in request
    query = url + self.hash (nonce + body, hashlib.sha256, 'binary')
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 344, in hash
    h = hashlib.new (hash, request)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\hashlib.py", line 149, in __hash_new
    return _hashlib.new(name, data)
TypeError: name must be a string`

Tried fixing it but no luck. Hopefully these are actually issues, not just on my end.

**Comment by marinsokol5** [comment]
Yea i had the same problem with kraken

**Comment by kroitor** [comment]
Thanks for reporting this!

> When calling Poloniex private api getting an error:

> "poloniex POST https://poloniex.com/tradingApi 422 b'{"error":"Nonce must be greater than 15001320050000. You provided 1500132345."}'"

This is the problem on your end. You should not edit the nonce inside __init__.py. You are using old apiKeys, which had a greater nonce. To continue using your old apiKeys, you should redefine the nonce function, like it is written in the Manual, see section [Overriding The Nonce](https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce) for details.

Redefine the nonce for you kraken account this way:
```Python
# B: milliseconds nonce
class MyKraken (ccxt.kraken):
    def nonce (self):
        return self.milliseconds ()

kraken = MyKraken ()
```

The other way to fix it is to generate new kraken apiKeys (see the link to the Manual above).

-----------

> When calling Kraken private api getting an error:
> File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 7178, in fetch_balance return self.privatePostBalance () File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 7203, in request query = url + self.hash (nonce + body, hashlib.sha256, 'binary') File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\__init__.py", line 344, in hash h = hashlib.new (hash, request) File "C:\Users\username\AppData\Local\Programs\Python\Python36-32\lib\hashlib.py", line 149, in __hash_new return _hashlib.new(name, data) TypeError: name must be a string

This is not a problem on your end, I will investigate and fix it asap.

**Comment by kroitor** [comment]
This problem is fixed now. I am closing this issue. If you have any problems further down the road, let me know, I will fix them.
