### ISSUE TITLE
How to get ohlcv of a period?

### ISSUE THREAD

**Issue by vonpupp** [kroitor/ccxt#215]
Hi,

Congrats on ccxt, even I am new to it, I think it is amazing!

I would like to know if it is possible using the fetch_ohlcv to get the 1m (or any other) ticks of the last 6 months or 1 year (or an arbitrary range of dates). I guess there is probably a limitation due to the amount of data.

Could you please post an example?

Thank you very much.

**Comment by kroitor** [comment]
Hi! 

Thanks for your feedback! Really appreciate it!)

As for your question: Coinigy takes $700 for one month of tick history for one exchange and one traded pair and you want me to do a simple example of fetching high loads of data without even saying what exchange it is, which pair it is and which language it is? )

Basically you will have to write a loop that would cycle through "since" parameter of fetch_ohlcv and fetch all data in batches. But it's very hard to do in general for all exchanges and all pairs at once as there are many caveats like rate-limiting and other factors.

From the underscore notation I would guess you're using Python. Though this is not always the case... So, we need more info from you on the above questions and then I'll do a simple example of how to fetch OHLCVs sequentially )

**Comment by vonpupp** [comment]
Hi @kroitor,

Ops, sorry for the missing info. I should have been more specific.

Yes, I am using python. I am interested in the data of mainly BTC/USD or BTC/EUR (this will be a parameter on my script), on kraken or bittrex (also a parameter). If possible 1m ticks would be great, if not, the lower the ticks freq the better. To be honest I thought it would be very easy with your lib. I am new to this kind of stuff, so no clue.

How it is possible to handle the range? I mean, that must be manually controlled on my side or it is possible to use `since` and some sort of `until` param?

What I would like to accomplish at the end is either fetch that data within a jupyter/ipython notebook or connect that to some sort of grafana dashboard to try to learn a bit about algorithmic trading for the sake of curiosity. The historical data would be helpful to try to validate anything historically (if anything more or less interesting comes out of this experiment).

Thank you very much for any guidance.

**Comment by kroitor** [comment]
I'll post an example snippet for Kraken, and you can then follow from there ) It will be ready in several hours, after I finish my current other task. Cheers.

**Comment by vonpupp** [comment]
Thank you very much @kroitor!

If I can make something useful with your example and my idea using jupyter/ipython I will happily PR into the examples in case you are interested.

**Comment by kroitor** [comment]
@vonpupp that would be awesome! Stay tuned, I'll update you on this.

**Comment by vonpupp** [comment]
Sure! Thx man.

**Comment by kroitor** [comment]
Ok, I've added an example of how you would do it with ccxt for Kraken, check it out here:
https://github.com/kroitor/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py

```Python
# -*- coding: utf-8 -*-

import os
import sys
import time

# -----------------------------------------------------------------------------

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root)

# -----------------------------------------------------------------------------

import ccxt  # noqa: E402

# -----------------------------------------------------------------------------
# common constants

msec = 1000
minute = 60 * msec

# -----------------------------------------------------------------------------

kraken = ccxt.kraken()

# -----------------------------------------------------------------------------

from_date = '2017-09-01 00:00:00'
from_timestamp = kraken.parse8601(from_date)

# -----------------------------------------------------------------------------

now = kraken.milliseconds()

# -----------------------------------------------------------------------------

while from_timestamp < now:

    print('Fetching candles starting from', kraken.iso8601(from_timestamp))

    ohlcvs = kraken.fetch_ohlcv('BTC/USD', '1m', from_timestamp)

    # don't hit the rateLimit or you will be banned
    time.sleep(kraken.rateLimit / 1000)

    # Kraken returns 720 candles for 1m timeframe at once
    from_timestamp += len(ohlcvs) * minute

    # do whatever you need with the list of OHLCVs...
    # ...
```

Let us know if you have any difficulty with it. In the meantime, I'm closing this if you don't mind. Thx!

**Comment by kroitor** [comment]
P.S. Don't forget to update to the latest version of ccxt in a couple of minutes.

**Comment by vonpupp** [comment]
Thanks man! I opened #218 due to a `ccxt.errors.ExchangeError: kraken {"error":["EAPI:Rate limit exceeded"]}`.

**Comment by kroitor** [comment]
In case someone stumbles upon this issue later, the solution is here: https://github.com/kroitor/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py

**Comment by kroitor** [comment]
![ccxt-kraken-1m](https://user-images.githubusercontent.com/1294454/31695982-aeb38f7e-b3b6-11e7-8792-d61abccf5a6d.gif)

**Comment by and-rewsmith** [comment]
@kroitor What is the point of fetching the data sequentially if kraken always returns 720 candles and that is the MAXIMUM number of candles in the past available?

If I have a misconception please correct me.

Here is a quote from you that explains the basis for my question:

> I tried the 5-minute timeframe with the same starting date (1st of January 2017), and it returned data starting like two days ago. So the greater the timeframe, the further in the past you will get, but, in the end, Kraken only serves last 720 candles of any timeframe max. They don't allow you to go beyond that fixed range.

**Comment by kroitor** [comment]
@and-rewsmith 

> What is the point of fetching the data sequentially if kraken always returns 720 candles and that is the MAXIMUM number of candles in the past available?

That was an example showing a general approach for sequential fetching + kraken has updated their limits since then. So, a straight answer to your question is: you're getting it correctly, there's no point in fetching sequentially, when the max history length is limited to 720 candles in the past. However, with other exchanges there's no such limit, so the example is ok, just need to switch to another exchange.

For Kraken you will need regular polling instead of sequential fetching, of course.

**Comment by and-rewsmith** [comment]
@kroitor Thanks for the response. Do you know what exchanges have no limit to their candle fetching?

**Comment by and-rewsmith** [comment]
For anyone reading this: bitfinix.

**Comment by canercak** [comment]
use freqtrade to collect data

**Comment by alireza-saberi** [comment]
Hi 
I am on running the suggested solution with Python and on windows 11 for timeframes of 5 min
start time is at 16th Jan 2022. It is extremally slow, I dont know why


        binance = ccxt.binance({
            'enableRateLimit': True,
            'rateLimit': 10000,  # unified exchange property
            'apiKey': self.binance_api_key,
            'secret': self.binance_secret_key,
            'recvWindow': 10000000
        })

       from_datetime = '2022-01-16 00:00:00'
       from_timestamp = bn.parse8601(from_datetime)
       now = bn.milliseconds()

       while from_timestamp < now:
            print('Fetching candles starting from', bn.iso8601(from_timestamp))
            ohlcvs = bn.fetch_ohlcv('BTC/USDT', '5m', from_timestamp)
            time.sleep(bn.rateLimit / 1000)
            from_timestamp += len(ohlcvs) * 300000
            print(ohlcvs)

Current time is ~2:10am UTC, I got response after 2 mins. 
Is 2 mins resealable? or there is a missing configuration at my end?

**Comment by kroitor** [comment]
@alireza-saberi 

> Hi I am on running the suggested solution with Python and on windows 11 for timeframes of 5 min start time is at 16th Jan 2022. It is extremally slow, I dont know why
> Current time is ~2:10am UTC, I got response after 2 mins. Is 2 mins resealable? or there is a missing configuration at my end?

Your code is wrong, you should not `sleep` and should not change `rateLimit` if you are not exactly sure what it does.

```Python
exchange = ccxt.binance()
print(exchange.iso8601(exchange.milliseconds()), 'Loading markets')
markets = exchange.load_markets()
print(exchange.iso8601(exchange.milliseconds()), 'Markets loaded')

from_timestamp = exchange.parse8601 ('2022-01-16T00:00:00Z')
now = exchange.milliseconds()
timeframe = '5m'
while from_timestamp < now:
    print('Fetching candles starting from', exchange.iso8601(from_timestamp))
    ohlcvs = exchange.fetch_ohlcv('BTC/USDT', timeframe, from_timestamp)
    if not len(ohlcvs):
        break
    from_timestamp = ohlcvs[-1][0] + exchange.parse_timeframe(timeframe) * 1000
    print(exchange.iso8601(exchange.milliseconds()), ohlcvs)
```

**Comment by alireza-saberi** [comment]
@kroitor you are genius!

**Comment by dawadam** [comment]
> ```python
> markets = exchange.load_markets()
> ```

@kroitor why load markets ?

**Comment by JeoCrypto** [comment]
exchange = ccxt.binance()
print(exchange.iso8601(exchange.milliseconds()), 'Loading markets')
markets = exchange.load_markets()
print(exchange.iso8601(exchange.milliseconds()), 'Markets loaded')

from_timestamp = exchange.parse8601('2022-01-01T00:00:00Z')


def get_data_from_exchange(coin, timestamp, filename):
    df = pd.DataFrame()
    from_timestamp = timestamp
    now = exchange.milliseconds()
    timeframe = '1h'
    while from_timestamp < now:
        print('Fetching data starting from: ', exchange.iso8601(from_timestamp))
        ohlcvs = exchange.fetch_ohlcv(coin, timeframe, from_timestamp)
        if not len(ohlcvs):
            break
        from_timestamp = ohlcvs[-1][0] + exchange.parse_timeframe(timeframe) * 1000
        print(exchange.iso8601(exchange.milliseconds()), ohlcvs)
        df = df.append(ohlcvs, ignore_index=True)
    df.to_csv(filename)
    return df


def clean_data(df,filename):
    data = pd.DataFrame(df)
    df = pd.DataFrame(data)
    df.columns = (["Time", "Open", "High", "Low", "Close", "Volume"])

    def parse_dates(ts):
        return datetime.datetime.fromtimestamp(ts / 1000.0)

    df["Time"] = df["Time"].apply(parse_dates)
    # set index to Date Time
    df.set_index("Time", inplace=True)
    df['Close'] = df['Close'].astype(float)
    df['Open'] = df['Open'].astype(float)
    df['High'] = df['High'].astype(float)
    df['Low'] = df['Low'].astype(float)
    df['Volume'] = df['Volume'].astype(float)
    df.dropna()
    df.to_csv(filename)
    print("Data exported to " + filename)
    return df

**Comment by mifth** [comment]
@kroitor I think I've found a bug. I'm trying to fetch 5 and 6 days of candles. But I get almost the same amount of candles when I use "1m" candle type.

My tests:
```
candles = fetch_candles(exchange, symbol, tf, days=5, limit_per_call=500)  # 5 days
candles = fetch_candles(exchange, symbol, tf, days=6, limit_per_call=500)  # 6 days

```

LOG (5 days and 6 days):
Fetching 1m candles for BTC/USDC:USDC over 5 days...
1m: Retrieved 5055 candles.

Fetching 1m candles for BTC/USDC:USDC over 6 days...
1m: Retrieved 5055 candles.


Here is my script:
import ccxt
import time
from datetime import datetime, timedelta

# Define timeframes and their minute equivalents
TIMEFRAMES = {
    '1m': 1,
    '5m': 5,
    '15m': 15,
    '30m': 30,
    '1h': 60,
    '4h': 240,
    '1d': 1440
}

# Fetch all candles for a given timeframe over N days
```
def fetch_candles(exchange: ccxt.Exchange, symbol, timeframe, days=3, limit_per_call=500):
    print(f"\nFetching {timeframe} candles for {symbol} over {days} days...")

    msec:float = 1000
    tf_minutes = TIMEFRAMES[timeframe]
    now = datetime.now()
    now_as_num = exchange.parse8601(now.isoformat())
    original_since = exchange.parse8601((now - timedelta(days=days)).isoformat())
    # print(now_as_num, original_since)
    since = original_since

    all_candles = []

    while since <= now_as_num:
        time.sleep((exchange.rateLimit / msec) * 1.1)

        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since=since, limit=limit_per_call)

        # Check
        if not ohlcv:
            break

        last_timestamp = ohlcv[-1][0]
        since = last_timestamp + 1

        all_candles += ohlcv

    return all_candles
    

# Main script
def main():
    exchange = ccxt.hyperliquid({
        'enableRateLimit': True,
    })

    symbol = 'BTC/USDC:USDC'

    for tf in TIMEFRAMES:
        candles = fetch_candles(exchange, symbol, tf, days=6, limit_per_call=500)
        print(f"{tf}: Retrieved {len(candles)} candles.")

if __name__ == "__main__":
    main()

```

**Comment by mifth** [comment]
Update:
Copilot says that there can be days limits in some exchanges:

Exchange API Limitations
Some exchanges only allow fetching data for the last X days or a maximum number of candles.

**Comment by mifth** [comment]
Update:
For Hyperliquid I can get only 3 days with of "1m" candles.
