### ISSUE TITLE
okex should support BCC/BTC LTC/BTC ETH/BTC ETC/BTC

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#216]
https://www.okex.com/spot/trade/index.do

**Comment by kroitor** [comment]
Hi! thx! Adding those right away ;)

**Comment by kroitor** [comment]
We added the missing symbols and cleaned up the OKCoin/OKex family implementation a little, it should be working in 1.7.66+. Let us know if you have any difficulties with it. Thx!
