### ISSUE TITLE
Support bithumb API

### ISSUE THREAD

**Issue by jokester01au** [kroitor/ccxt#217]
Hi, FIrstly thanks for an outstanding piece of software. This is brilliant.

I would love to be able to use this against the bithumb api.

Do you have any documentation about adding support for exchanges? I would be happy to implement bithumb support and feed it back to you.

Otherwise, my current need is only the order book, is there any chance of hacking together a quick implementation of this for me?

Regards,
Joseph.

**Comment by kroitor** [comment]
Hi! Thx for your feedback and for the proposal! Here's the doc: https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md. A PR from you would be awesome! If you have any difficulty implementing bithumb, let us know. Thx again!

**Comment by kroitor** [comment]
Actually, you know what... Just don't bother, we will add it in several hours anyway ) We would really appreciate it if you could help us with yet-not-implemented unified methods for some of the exchanges... Here's a list of our pending tasks: https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#pending-tasks

**Comment by kroitor** [comment]
We have added the support for Bithumb API. It will be available as of version 1.7.67+. Currently only their public API is supported (including the orderbooks), support for their private API is on the way.

**Comment by jokester01au** [comment]
Magic! Thanks so much. I'll contribute unified methods as I get the chance. Unfortunately this isn't my day job so I struggle for time.
