### ISSUE TITLE
Issue with 'crypto' Module

### ISSUE THREAD

**Issue by PolybitSol** [kroitor/ccxt#23]
Hey,

I'm currently using the ccxt library with a Meteor application I'm developing - it's a brilliant library and has been a great help, so thank you! The issue is the use of Node's _crypto_ module, which causes confusion with NPM over an old, deprecated package of the same name, from what I gather. As a result I get a conflict error when compiling my app.

`Uncaught Error: Cannot find module 'crypto'`

I can bypass the issue during development by simply deleting the deprecated crypto module from my node_modules folder, however when I go to deploy I don't have control over this. Do you know anyway around this, or would it be possible to implement another cryptographic module like crypto-js? Or is the only option to fork & make the ammendment myself?

Thanks for any advice you can offer.

**Comment by kroitor** [comment]
Hi! First of all, thank you for your feedback! I will investigate and report on this issue asap (may take a few hours). I'm sure we can find a workaround.

**Comment by PolybitSol** [comment]
Great, thanks for looking into it, look forward to hearing back from you.

**Comment by kroitor** [comment]
Yeah, I think I will rewrite the Node.js HMAC/hash code to crypto-js (aka CryptoJS). It is already used for browser-specific ccxt implementation, so I will also switch to it under Node as well. I'll update you on the progress, should be ready by tomorrow (if nothing extraordinary comes up).

**Comment by PolybitSol** [comment]
That's great to hear, thanks again - really digging the project.

**Comment by kroitor** [comment]
Still working on, a fix is on the way, sorry for the long wait.

**Comment by kroitor** [comment]
Sorry for a long wait. We have finally switched from `crypto` to `crypto-js` and tested it, so you can now use ccxt and deploy it anywhere you want safely ) Thank you very much for your feedback! Feel free to contact us if you have any questions.

Also, we are very interested and would like to know more about the Meteor project that you mentioned. We would be happy to learn more about it! Can you send us a link to the Meteor project homepage?

**Comment by PolybitSol** [comment]
You're welcome, and than you too for the update! 

I'm currently tweaking the landing page, which conveys most of the information, so I will link that as soon as it's fit for release. The general gist of the project, is an all-in-one cryptocurrency trading, analysis and portfolio management platform - so I'm sure you can see why this project has been a great help in streamlining the process!

**Comment by kroitor** [comment]
Great! Can't wait to see your project released! We are interested in all projects that use the ccxt library, so, if you don't mind, we would like to exchange links with you. Please send us a message when/if you feel like it's time, we will add a link to your project to our docs and we also hope to get a backlink from you! Good luck Meteor!

**Comment by kroitor** [comment]
I wonder if [this](https://github.com/meteor/meteor) is your Meteor  )

**Comment by kroitor** [comment]
We had to turn crypto back on, because CryptoJS doesn't wan't to work properly under Node for Kraken. This is a temporary measure, until we find a less clumsy solution to this problem. See issue #52.

**Comment by kroitor** [comment]
Ok, we have found a solution to this, and we will remove module `crypto` alltogether in one of upcoming releases. Thanks!

**Comment by kroitor** [comment]
We have finally integrated an adequate solution for Kraken, and removed that ugly workaround! ) Module crypto is now removed from dependencies completely!

**Comment by meteorplus** [comment]
indeed well done and module crypto is ugly!
