### ISSUE TITLE
Liqui issues

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#29]
```python
krk = ccxt.liqui()
pair = "GNO/USDT"
print (pair in krk.load_products())
krk.fetch_order_book(pair)
```

```
True
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-ab12fbccc45f> in <module>()
      2 pair = "GNO/USDT"
      3 print (pair in krk.load_products())
----> 4 krk.fetch_order_book(pair)

/usr/lib/python3.6/site-packages/ccxt/__init__.py in fetch_order_book(self, product)
   3410             'pair': p['id'],
   3411         })
-> 3412         orderbook = response[p['id']]
   3413         timestamp = self.milliseconds ()
   3414         result = {

KeyError: 'gno_usdt'
```

**Comment by kroitor** [comment]
Rarely traded pairs have np data... Uh...  Will fix this in general soon.

**Comment by nmiculinic** [comment]
All previous errors might be due to rate limiter...But I expect such exception being thrown out. 

https://i.imgur.com/oXfdS4n.png

Huh it appears working now, possible rate limiter hit though. Btw can you derive all your exceptions from same base class?

```python
class CcxtException(Exception):
    pass

class DDoSProtectionError (CcxtException):
    pass
```

which allows me differentiating ordinary exceptions with bug inducing ones

**Comment by kroitor** [comment]
Ok, will change exception inheritance hierarchy.

**Comment by kroitor** [comment]
> All previous errors might be due to rate limiter...But I expect such exception being thrown out.

The problem with Kraken was not connected with the rate limiter, though. It was a darkpool pair. The don't have order books. Will throw exception in these cases (soon).

**Comment by kroitor** [comment]
Added the following hierarchy of exceptions:
```
class CCXTError (Exception):
    pass

class DDoSProtectionError (CCXTError):
    pass

class AuthenticationError (CCXTError):
    pass

class NotAvailableError (CCXTError):
    pass

class MarketNotAvailaibleError (NotAvailableError):
    pass

class OrderBookNotAvailableError (NotAvailableError):
    pass

class TickerNotAvailableError (NotAvailableError):
    pass
```

A market like Kraken will now throw `*NotAvailableError` for darkpool pairs.

**Comment by kroitor** [comment]
Will throw an `OrderBookNotAvailableError` from now on. Closing this issue.
