### ISSUE TITLE
Cex issue

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#31]
Same thing unfortunately.
Private api for cex.io

```
   response = self.request(command, type='private', method='POST')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 4647, in request
    'signature': self.hmac (self.encode (auth), self.secret).upper (),
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\ccxt\__init__.py", line 389, in hmac
    h = hmac.new (secret, request, algorithm)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "C:\Program Files (x86)\Python36-32\lib\hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by kroitor** [comment]
Should work now. Thanks!

**Comment by marinsokol5** [comment]
Yea it does,thank you.

**Comment by marinsokol5** [comment]
I have a problem with signature in cex.
Not sure from which side is it.Mine or yours.
Im testing for method:  get_myfee/ in cex
This is what i get as a response
{'e': 'get_myfee', 'error': 'Invalid signature', 'ok': 'error'}
Api key and secret should be correctly inputed.I have checked.Might be a problem with computing the signature?

**Comment by kroitor** [comment]
Yes, it can be a problem with the signature. Investigating further...

**Comment by kroitor** [comment]
You probably forgot to set the `uid`. Cex requires that. See [API Keys Setup](https://github.com/kroitor/ccxt/wiki/Manual#api-keys-setup) section in the manual.

To test if this is the case with uid, try the following code:
```Python
import ccxt
cex = ccxt.cex ({
    'apiKey': 'eqCv267WySlu577JnFbGK2RQzIs', # this is standard
    'secret': 'pZnbuNEm5eE4W1VRuFQvZEiFCA', # this is also standard
    'uid': 'up105393824', # you should set uid as string
	
})
cex.fetch_balance ()
```

**Comment by kroitor** [comment]
Please, test the code above, then try your credentials and report if everything is ok or not. Thank you very much! Appreciate your help!
