### ISSUE TITLE
Calling unified methods

### ISSUE THREAD

**Issue by poogoo** [kroitor/ccxt#36]
Would it be possible to get a the consistent format when getting the result of unified methods such as
`fetchOrderBook (symbol)`
or
`fetchBalance ()`

At the moment a few orderbooks still include timestamps (e.g. from kraken) with each order, and the result of calling fetchBalance() is obviously very different between exchanges; I'm guessing it would be a big task to change this?

**Comment by kroitor** [comment]
> Would it be possible to get a the consistent format when getting the result of unified methods such as
> fetchOrderBook (symbol)

They're unified, but have extra fields if provided by market API. Do you experience any difficulty with a third element being present in each order (consider carefully)? If you confirm, we will then remove that element from there. And if you find any inconsistencies with one market or another, we will be thankful, if you could list them here or by opening another issue. If you want us to remove  timestamps from the orderbook, we will do that for Kraken and all other exchanges.

> or
> fetchBalance ()

Sure, we're actually working on this right now, along with many other cool new features.

> At the moment a few orderbooks still include timestamps (e.g. from kraken) with each order, and the result of calling fetchBalance() is obviously very different between exchanges; I'm guessing it would be a big task to change this?

We've anticipated your request ) And we are already implementing this, balance unification will be ready very soon ) Will let you know. Thanks for your feedback!

**Comment by poogoo** [comment]
Nah, the extra timestamp thing isn't a big problem. Excited for your future updates, thanks!

**Comment by kroitor** [comment]
The work on this issue has seen a good progress in past few days, we are in the middle of reworking the unified balances now, half of markets have been unified already. The other half is coming soon, will update the docs and let you know as soon as possible! Keep in touch! )

**Comment by kroitor** [comment]
Ok, we have finished unifying balances, and now all markets return a common balance structure, [as described in the Manual](https://github.com/kroitor/ccxt/wiki/Manual#querying-account-balance):

```
{
    'BTC': {             // three-letter currency code
        'free': 321.00   // float, money available for trading
        'used': 234.00,  // float, money on hold, locked, frozen or pending
        'total': 555.00, // float, total balance (free + used)
    },
    'USD': {
        'free': 123.00   // ...
        'used': 456.00,  
        'total': 579.00, 
    },
    ...
}
```

Therefore I am closing this, if you experience any difficulties with balances with any particular market, feel free to open a new issue. Thanks for your help!
