### ISSUE TITLE
Bitfinex nonce

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#39]
Trying to get balances on btifinex.
```command = 'balances'
   response = self.request(command, type='private', method='POST')
```
```
bitfinex POST https://api.bitfinex.com/v1/balances 400 Bad Request b'{"message":"Nonce is too small."}
```

Might be a problem from my end.
Any ideas?

**Comment by kroitor** [comment]
I've already answered [a similar question about it here](https://github.com/kroitor/ccxt/issues/21). Did you read [Overriding The Nonce](https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce) section in the Manual?
```Python
# A: milliseconds nonce
class MyBitfinex (ccxt.bitfinex):
    def nonce (self):
        return self.milliseconds ()

# B: your nonce
class MyBitfinex2 (ccxt.bitfinex):
    i = 1234567890 # any number
    def nonce (self):
        i = i + 1
        return i

bitfinex = MyBitfinex ()
bitfinex2 = MyBitfinex2 ()
```
It's definitely a problem on your end. Try resetting your API keys or choose milliseconds/custom nonce.

**Comment by marinsokol5** [comment]
Yea it was a problem on my end.Thank you.

**Comment by kroitor** [comment]
This may also be a rate-limiting problem, if you call that request more frequently than once per second – you should definitely use a smaller (milliseconds) nonce. No problem, thanks for reporting this anyway. I will try to make it explained in a cleaner way in the Manual.
