### ISSUE TITLE
Inconsistent naming across exchange markets

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#4]
HitBTC exchange has both DASH/BTC and DSH/BTC pairs with different prices. I'd expect naming pair would be consistent across various markers, however following code proves me otherwise:

```
import ccxt
h = ccxt.bitfinex()
h.load_products()
pp.pprint(h.fetch_ticker("DSH/BTC"))

k = ccxt.hitbtc()
k.load_products()
pp.pprint(k.fetch_ticker("DSH/BTC"))
```
Output:
```
{'ask': 0.081222,
 'average': 0.080965,
 'baseVolume': None,
 'bid': 0.080708,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T15:21:00.000Z',
 'first': None,
 'high': 0.087383,
 'info': {'ask': '0.081222',
          'bid': '0.080708',
          'high': '0.087383',
          'last_price': '0.080573',
          'low': '0.07499',
          'mid': '0.080965',
          'timestamp': '1499354460.27357124',
          'volume': '11299.25037405'},
 'last': 0.080573,
 'low': 0.07499,
 'open': None,
 'percentage': None,
 'quoteVolume': 11299.25037405,
 'timestamp': 1499354460273.5713,
 'vwap': None}
{'ask': 1.2085e-05,
 'average': None,
 'baseVolume': 11216.0,
 'bid': 1.2023e-05,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T15:21:00.000Z',
 'first': None,
 'high': 1.2999e-05,
 'info': {'ask': '0.000012085',
          'bid': '0.000012023',
          'high': '0.000012999',
          'last': '0.000012085',
          'low': '0.000012023',
          'open': '0.000012015',
          'timestamp': 1499354460429,
          'volume': '11216',
          'volume_quote': '0.000000000'},
 'last': 1.2085e-05,
 'low': 1.2023e-05,
 'open': 1.2015e-05,
 'percentage': None,
 'quoteVolume': 0.0,
 'timestamp': 1499354460429,
 'vwap': None}
```

Also with HitBTC I get a lot of internal server errors when querying their API via this library.

**Comment by kroitor** [comment]
This is not inconsistency actually, DSH and DASH are not the same currency/token. You should probably google it first,  but if you do, you are likely to find mixed information about both in one search query.

As written here: 
https://minergate.com/blog/dashcoin-and-dash/

These are two totally different currencies with similar names. Dash was launched as XCoin in January 18, 2014, and 10 days later was rebranded as Darkcoin. On March 26, 2015 Darkcoin was renamed to Dash. Partly in order to gain over Dashcoin users and partly to expand the brand, and that was the time when this confusion began.

Dash (DASH) is a coin based on X11 algorithm. It’s a system which consists of 11 chain hashing algorithms for the-proof-of-work. Another feature of Dash is Darksend, a special scheme which allows you to always stay anonymous. Dash is designed for powerful CPUs.

**How to distinguish**

- Pay attention to the logo.

    dashcoin:

    ![dashcoin-150x150](https://user-images.githubusercontent.com/1294454/27919292-f10bd8e2-6279-11e7-91ca-f719ace7c40e.png)

    Dash:

    ![dash-150x150](https://user-images.githubusercontent.com/1294454/27919297-f4e9f106-6279-11e7-9bae-a89662f08d42.png)

-  Mind the initial letter of a wallet address. A Dashcoin wallet always starts with the letter ’d’, while a Dash one starts with an ‘x ‘, which is the legacy of its first title XCoin.
- Notice the ticker, an abbreviated cryptocurrency name. Dashcoin is referred to as DSH, whereas Dash is known as DASH. It’s pretty simple: the longest name has the shortest ticker.
- Finally, you may explore the currencies’ official websites and accounts in social media.

**Comment by kroitor** [comment]
Official Dashcoin website http://dashcoin.info/
Official Dash website https://www.dash.org/

**Comment by nmiculinic** [comment]
Nevertheless, I expect that naming scheme be consistent under different markets, that is if I ask for DSH/BTC pair in one market, I'll get same pair on other markets too.

**Comment by nmiculinic** [comment]
It's not in issue whether there exist DASH and DSH, but the naming consistency across markets.

**Comment by nmiculinic** [comment]
There's also reverse pair naming in different markets with similar ask/bid/last price:
```
import ccxt
h = ccxt.kraken()
h.load_products()
pp.pprint(h.fetch_ticker("ETH/BTC"))

k = ccxt.bittrex()
k.load_products()
pp.pprint(k.fetch_ticker("BTC/ETH"))
```

Output:
```
{'ask': 0.102895,
 'average': None,
 'baseVolume': None,
 'bid': 0.102745,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T15:57:31.000Z',
 'first': None,
 'high': 0.105472,
 'info': {'a': ['0.102895', '3', '3.000'],
          'b': ['0.102745', '30', '30.000'],
          'c': ['0.102896', '1.50000000'],
          'h': ['0.105472', '0.105472'],
          'l': ['0.100500', '0.099300'],
          'o': '0.102000',
          'p': ['0.103227', '0.100233'],
          't': [4984, 8575],
          'v': ['18455.17522042', '30599.50119370']},
 'last': 0.102896,
 'low': 0.0993,
 'open': 0.102,
 'percentage': None,
 'quoteVolume': 30599.5011937,
 'timestamp': 1499356650937,
 'vwap': 0.100233}
{'ask': 0.10309993,
 'average': None,
 'baseVolume': None,
 'bid': 0.10300001,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T15:53:59.000Z',
 'first': None,
 'high': 0.1055,
 'info': {'Ask': 0.10309993,
          'BaseVolume': 3300.39366237,
          'Bid': 0.10300001,
          'Created': '2015-08-14T09:02:24.817',
          'High': 0.1055,
          'Last': 0.10300001,
          'Low': 0.099485,
          'MarketName': 'BTC-ETH',
          'OpenBuyOrders': 5491,
          'OpenSellOrders': 11723,
          'PrevDay': 0.10000201,
          'TimeStamp': '2017-07-06T15:53:59.59',
          'Volume': 32130.16436321},
 'last': 0.10300001,
 'low': 0.099485,
 'open': None,
 'percentage': None,
 'quoteVolume': 32130.16436321,
 'timestamp': 1499356439000,
 'vwap': None}
```

If I reverse the arguments under any market it screams with some exceptions, depending on where it breaks.

**Comment by kroitor** [comment]
When you ask for DSH/BTC from Bitfinex and then ask DSH/BTC from HitBTC, you are getting the same pair. But notice that the HitBTC DSH volume is 0.0, meaning that the price for DSH/BTC may be outdated there (this is what their API gives). Whereas on Bitfinex the price is up to date.

As for reverse pair naming – I will fix that for bittrex, thank you for noting that!

**Comment by kroitor** [comment]
You cannot reverse pairs manually, and should only be using the keys of `market.products` array.

```
import ccxt

kraken = ccxt.kraken()
kraken.load_products ()
print (list (kraken.products.keys ())) # use these symbols only

bittrex = ccxt.bittrex ()
bittrex.load_products ()
print (list (bittrex.products.keys ())) # use these symbols only
```

Thank you for your report, I will investigate further into the reversed pairs to fix that for more consistency across markets.

**Comment by nmiculinic** [comment]
> When you ask for DSH/BTC from Bitfinex and then ask DSH/BTC from HitBTC, you are getting the same pair. But notice that the HitBTC DSH volume is 0.0, meaning that the price for DSH/BTC may be outdated there (this is what their APIs return). Whereas on Bitfinex the price is up to date.

I'm not really following you here. From Bitfinex I'm getting DASH/BTC pair instead of DSH/BTC(which IIRC doesn't exist on that exchange). Prices match approximately.

> Thank you for your report, I will investigate further into the reversed pairs to fix that for more consistency across markets.

```
import ccxt
h = ccxt.poloniex()
h.load_products()
pp.pprint(h.fetch_ticker("BTC/ETH"))

k = ccxt.gdax()
k.load_products()
pp.pprint(k.fetch_ticker("ETH/BTC"))
```

There are more markets where they have internal inconsistencies. Those are ones I found for now, though I haven't been looking too hard.

**Comment by nmiculinic** [comment]
Oh yeah, and there's this market API/consistency gem:

```
import ccxt
h = ccxt.btce()
h.load_products()
pp.pprint(h.fetch_ticker("ETH/LTC"))

k = ccxt.bittrex()
k.load_products()
pp.pprint(k.fetch_ticker("ETH/LTC"))
```

```
{'ask': 5.262,
 'average': 5.23501,
 'baseVolume': 6538.3599,
 'bid': 5.28339,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T16:25:01.000Z',
 'first': None,
 'high': 5.52,
 'info': {'avg': 5.23501,
          'buy': 5.28339,
          'high': 5.52,
          'last': 5.262,
          'low': 4.95002,
          'sell': 5.262,
          'updated': 1499358301,
          'vol': 34721.04192,
          'vol_cur': 6538.3599},
 'last': 5.262,
 'low': 4.95002,
 'open': None,
 'percentage': None,
 'quoteVolume': 34721.04192,
 'timestamp': 1499358301000,
 'vwap': None}
{'ask': 0.19299995,
 'average': None,
 'baseVolume': None,
 'bid': 0.19,
 'change': None,
 'close': None,
 'datetime': '2017-07-06T16:24:54.000Z',
 'first': None,
 'high': 0.20499999,
 'info': {'Ask': 0.19299995,
          'BaseVolume': 1658.76170155,
          'Bid': 0.19,
          'Created': '2017-06-25T03:06:46.83',
          'High': 0.20499999,
          'Last': 0.19,
          'Low': 0.18341639,
          'MarketName': 'ETH-LTC',
          'OpenBuyOrders': 173,
          'OpenSellOrders': 98,
          'PrevDay': 0.19999979,
          'TimeStamp': '2017-07-06T16:24:54.123',
          'Volume': 8434.69400369},
 'last': 0.19,
 'low': 0.18341639,
 'open': None,
 'percentage': None,
 'quoteVolume': 8434.69400369,
 'timestamp': 1499358294000,
 'vwap': None}
```

I check on their webpages, https://i.imgur.com/WyeOSQu.png  and it's ok from API perspective. Those numbers are reciprocal as if they reversed the pairing but not the names

**Comment by kroitor** [comment]
> I'm not really following you here. From Bitfinex I'm getting DASH/BTC pair instead of DSH/BTC(which IIRC doesn't exist on that exchange). Prices match approximately.
Oh, I see. The Bitfinex lists Dash as `DSH`, instead of `DASH`.
I will fix that too. Appreciate your help!

**Comment by kroitor** [comment]
> Oh yeah, and there's this market API/consistency gem:

Bittrex seems to have reverse pair naming, I will fix that. Thanks!

**Comment by kroitor** [comment]
Bittrex pairs are now fixed (reversed the way they should be, consistent with the other markets). Working on Bitfinex (DSH) and other issues you mentioned... Will let you know when it's done.

**Comment by kroitor** [comment]
Fixed Bitfinex DSH → DASH inconsistency. Investigating Poloniex vs GDAX now.

**Comment by kroitor** [comment]
Poloniex is also fixed now with proper pair ordering. Thank you for reporting this!
