### ISSUE TITLE
DASH on hitbtc

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#42]
In class hitbtc and in its method fetch_products()
``` if base == 'DSH':
                base = 'DASH'
``` 
I dont understand this two lines.
DASH is DASH and DSH is DASHCOIN they are two separate coins I've double checked.

**Comment by kroitor** [comment]
Hey!

Please, check these two issues: 
1. [Consistency issues](#12)
2. [Inconsistent naming across exchange markets](#4)

Also, there's [a dedicated section on this](https://github.com/kroitor/ccxt/wiki/Manual#naming-consistency) conversion from DSH to DASH in the [Manual](https://github.com/kroitor/ccxt/wiki/Manual). I suggest you read entire Manual from the very beginning to the end very carefully )

**Comment by kroitor** [comment]
In short: you're right, these are two separate coins, but some markets have them confused (call them DSH instead of DASH). So, the lines you're looking at are fixing for that for those markets, that got it wrong.
