### ISSUE TITLE
Load products

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#46]
I was testing some exhanges and i found some inconsistencies.

When you call `poloniex.fetchProducts()` you get products with symbols such as BTC/DASH and when you call `hitbtc.fetchProducts()` the same product has symbol  DASH/BTC .

**Comment by kroitor** [comment]
Hi! Thanks for posting this! Yeah, some markets may have them reversed, I will check for that very soon.

**Comment by kroitor** [comment]
I've been busy with other issues and bugs, don't worry, I'll get back to you on this issue. Thanks for your patience!

**Comment by kroitor** [comment]
We fixed it, poloniex should now have proper pairs. Thanks for reporting!

**Comment by kroitor** [comment]
It will ba available as of version 1.1.94

**Comment by kroitor** [comment]
Ok, poloniex now has proper pairs, version 1.1.94 is available for downloading.

<img width="499" alt="screen shot 2017-07-27 at 22 22 57" src="https://user-images.githubusercontent.com/1294454/28688398-72469a9a-731a-11e7-9938-1c8f2dad3efb.png">

**Comment by kroitor** [comment]
<img width="764" alt="screen shot 2017-07-27 at 22 32 19" src="https://user-images.githubusercontent.com/1294454/28688718-7f57cee2-731b-11e7-9185-a252eeadfabf.png">
