### ISSUE TITLE
Issue about data type casting in ANXPRO python code 

### ISSUE THREAD

**Issue by cftang0827** [kroitor/ccxt#5]
Hello~

When I was using python fetch ticket from ANXPRO, I faced a problem

In [31]: anxpro.fetch_ticker('BTC/USD')
TypeError                                 Traceback (most recent call last)
<ipython-input-31-e956fe623222> in <module>()
----> 1 anxpro.fetch_ticker('BTC/USD')

C:\Users\***\Desktop\ccxt\ccxt\__init__.pyc in fetch_ticker(self, product)

    811         ticker = response['data']
    *812        timestamp = int (ticker['dataUpdateTime'] / 1000)
    813         return {
    814             'timestamp': timestamp,

TypeError: unsupported operand type(s) for /: 'unicode' and 'int'

There was an error in line 812

It seemed like there's some problem in casting. Therefore, I had checked the source code __init__.py
and I think I found the bug.

*original version

`812    timestamp = int (ticker['dataUpdateTime'] / 1000)`
                                                                         
*modified version

`812     timestamp = int (ticker['dataUpdateTime']) / 1000
`                                                                  

Besides, there's still a bug in line 819

    817             'low': float (ticker['low']['value']),
    818             'bid': float (ticker['buy']['value']),
    *819             'ask': float (ticker['sell'])['value'],
    820             'vwap': float (ticker['vwap']['value']),
    821             'open': None,

Original version
`'ask': float (ticker['sell'])['value']
`                                  
modified version
`'ask': float (ticker['sell']['value'])
`                                              

The problem wave solved after I remove these two bugs.

Thank you very much :)

**Comment by kroitor** [comment]
Thank you for reporting that! I fixed it with your help!
