### ISSUE TITLE
Support for chbtc & yunbi

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#50]
need support for:
https://www.chbtc.com/
https://yunbi.com/
thanks !

**Comment by kroitor** [comment]
Got it! ) Thanks! These APIs be available in one of releases in nearest future. Will update you on that.

**Comment by 86chenjie** [comment]
wonderful !

**Comment by kroitor** [comment]
CHBTC will be available in 30-40 minutes in version 1.1.77. Thanks! Will update soon on Yunbi.

**Comment by 86chenjie** [comment]
You guys are so productive!  👍

**Comment by kroitor** [comment]
Thanks! An update on Yunbi is coming soon.

**Comment by kroitor** [comment]
Yunbi should be available within the next release (version 1.1.79). Please report if you have any problems with it. It should appear in the docs very soon, the testing should be over in 30-40 mins. You can watch live test progress here: https://travis-ci.org/kroitor/ccxt/builds/. Thanks!
