### ISSUE TITLE
Problems with fetchBalances() for Three Out of Five Exchanges

### ISSUE THREAD

**Issue by cklester** [kroitor/ccxt#53]
I'm attempting to use five exchanges right now, all of which work fine except for Poloniex, Bitfinex, and Kraken when it comes to fetchBalances(). I get these errors:

`poloniex: Error: poloniex POST https://poloniex.com/tradingApi 422 Unprocessable Entity`
`bitfinex: Error: bitfinex POST https://api.bitfinex.com/v1/balances 400 Bad Request Possible reasons: invalid API keys, market down or offline, on maintenance, DDoS protection, rate-limiting in effect`
`kraken: TypeError: Cannot convert undefined or null to object`

They all return loadProducts() just fine, and I know have the correct credentials. Is there something special about these exchanges I might be missing when it comes to fetching balances? So far, GDAX and Bitstamp work fine.

**Comment by kroitor** [comment]
Hi!
Thanks for posting this!
We now have a fix for this issue, it should be available in version 1.1.81 already. The Kraken exchange should also work normally. We made a special case for the beast, that is until we find a more elegant solution to this problem. 

Code for testing:
```JavaScript
const ccxt = require ('ccxt')
const kraken = new ccxt.kraken ({
    apiKey: 'CGAra4mIwKxgV3uYB4XZI4nVVmjXyIpER+5bFUuXGlIQ4MJFKLQfTJWK',
    secret: 'wrkstzsrwdj9pJlUGjj+wOTQgYAaO8MankKJPhASNGEY7hbFAtumQ45C7K/2SwCSgL8WcusUuTgarP5mmqo1uQ=='
})
(async () => {
    await kraken.loadProducts ()
    console.log (await kraken.fetchBalance ())
}) ()
```

This snippet should output the following:

```bash
{ info: {} } # no error, just an empty balance
```

Can you test it in your console and report if you have any errors? You didn't mention the language you're using, so, I written it here in JS, but here's a Python version of the same snippet just in case:

```Python
import ccxt
kraken = ccxt.kraken ({
    'apiKey': 'CGAra4mIwKxgV3uYB4XZI4nVVmjXyIpER+5bFUuXGlIQ4MJFKLQfTJWK',
    'secret': 'wrkstzsrwdj9pJlUGjj+wOTQgYAaO8MankKJPhASNGEY7hbFAtumQ45C7K/2SwCSgL8WcusUuTgarP5mmqo1uQ=='
})
kraken.load_products ()
kraken.fetch_balance ()
```

**Comment by kroitor** [comment]
Also, note, that you have to update ccxt to version 1.1.80+ for this to work.

**Comment by cklester** [comment]
Hi, kroitor. I am using the latest version under Node.js. I updated it after the prior issue was completed. Here is the console output for when I run your test code:

`$ node test_kraken.js
C:\Users\c.k.lester\Documents\repos\csx\test_kraken.js:6
(async () => {
^

TypeError: (intermediate value) is not a function
    at Object.<anonymous> (C:\Users\c.k.lester\Documents\repos\csx\test_kraken.js:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3`

Is there a command I can run to get the version of the module I'm using?

I'm using node 8.1.4 and npm 5.0.3.

**Comment by cklester** [comment]
I confirmed I'm using ccxt 1.1.83.

**Comment by kroitor** [comment]
After we debug your Kraken connection, then we will move to see what's wrong with your Poloniex and Bitfinex, may be nonce issues, but we should debug Kraken first, as it should work normally after recent updates.

**Comment by kroitor** [comment]
Please report if/when you have Kraken up and running normally. That snippet should output an empty balance.

**Comment by cklester** [comment]
The test from a file worked. I didn't try from the command line. I didn't even know about that! :-)

**Comment by kroitor** [comment]
Ok, I'm going to post testing snippets for Poloniex and Bitfinex now, to see what you get in response. Give me a sec, I'll get back to you very soon!

**Comment by cklester** [comment]
When I tried with my credentials, I got this output:

`$ node test_kraken.js
(node:4476) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: request timed out
(node:4476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

That could just be timeout issues with Kraken.

**Comment by kroitor** [comment]
No, it might be a nonce issue. Did you use your credentials previously with other software? Can you try a new fresh keypair?

**Comment by cklester** [comment]
I generated a new keypair, and it worked for me!

**Comment by kroitor** [comment]
Ok! Good to know that, but hold on a little )
If you experience such problems in future, you don't need to regenerate your keypairs, you may be fine with the nonce overrided. Here's how it's done:
And in a file:
```JavaScript
let ccxt = require ('.ccxt')
let kraken = new ccxt.kraken ({
    apiKey: 'YOUR_OLD_API_KEY_THAT_DIDNT_WORK',
    secret: 'YOUR_OLD_SECRET_THAT_DIDNT_WORK',
    nonce: Date.now, // ← this line added, overrides the nonce
})
async function test () => {
    await kraken.loadProducts ()
    console.log (await kraken.fetchBalance ())
}
test ()
```
You can test it with your old keypair to see if this helps. Now I'm going for Poloniex and Bitfinex test samples, one sec.

**Comment by cklester** [comment]
I tried the old creds with the nonce override, and it still came back with errors. I think maybe the old creds got spoiled...?

**Comment by kroitor** [comment]
Could be even bigger nonce used already with your old credentials. That may be called 'spoiling' :)
At least, we know that the problem is not with Kraken support in the library, but a problem with your old credentials. Now that it's gone with a new keypair, we will debug your Poloniex and Bitfinex, I'll post examples. Also, I would highly recommend reading [the Manual](https://github.com/kroitor/ccx/wiki) very carefully from the beginning to the very end )
I'll get back to you in a couple of minutes.

**Comment by cklester** [comment]
Well, I'm wondering if a new keypair for Poloniex and Bitfinex will clear things up as well. :-D

**Comment by kroitor** [comment]
```JavaScript
"use strict";

let ccxt = require ('./ccxt')
let bitfinex = new ccxt.bitfinex ({ 
	"apiKey": "5A1VikyEtDpmFkrzX4e52LsaVgCxXyMnY9JElqvNMxo", 
	"secret": "Rgxxw1BGnq6NLTLq1hn0oQ5FBDRLYFFVRzyEKYbz1io",
})

async function test () {
    await bitfinex.loadProducts ()
    console.log (await bitfinex.fetchBalance ())
}

test ()
```

Does this work for you?

**Comment by cklester** [comment]
Here's the output:

`$ node test_bitfinex.js
{ info:
   [ { type: 'exchange',
       currency: 'btc',
       amount: '0.0051689',
       available: '0.0051689' },
     { type: 'exchange',
       currency: 'usd',
       amount: '0.0',
       available: '0.0' } ],
  BTC: { free: 0.0051689, used: 0, total: 0.0051689 },
  LTC: { free: undefined, used: undefined, total: undefined },
  ETH: { free: undefined, used: undefined, total: undefined },
  ETC: { free: undefined, used: undefined, total: undefined },
  RRT: { free: undefined, used: undefined, total: undefined },
  ZEC: { free: undefined, used: undefined, total: undefined },
  XMR: { free: undefined, used: undefined, total: undefined },
  DASH: { free: undefined, used: undefined, total: undefined },
  BCC: { free: undefined, used: undefined, total: undefined },
  BCU: { free: undefined, used: undefined, total: undefined },
  XRP: { free: undefined, used: undefined, total: undefined },
  IOT: { free: undefined, used: undefined, total: undefined },
  EOS: { free: undefined, used: undefined, total: undefined },
  SAN: { free: undefined, used: undefined, total: undefined },
  OMG: { free: undefined, used: undefined, total: undefined },
  USD: { free: 0, used: 0, total: 0 } }`

**Comment by kroitor** [comment]
Well, with a new keypair Bitfinex should also work normally then. Can you try a new one?

**Comment by kroitor** [comment]
This is for Poloniex:
```JavaScript
"use strict";

let ccxt = require ('./ccxt')
let poloniex = new ccxt.poloniex ({ 
	"apiKey": "BLWC235I-69P3AOOG-9K2PIH6N-HGZPOXAQ", 
	"secret": "34ebd79b4400df54114c5d3e2b339b27d28eccc747766c78c0d42826ebc3d2a21bb4c9870f2168dcc6d9437dc08e6253f5949fe85b4b73e30b7e56e879624f8d"
})

async function test () {
    await poloniex.loadProducts ()
    console.log (await poloniex.fetchBalance ())
}

test ()
```

Standing by for your report.

**Comment by kroitor** [comment]
https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting
Worth reading )

**Comment by cklester** [comment]
Sorry! I missed that troubleshooting section. Good info. Thank you!

**Comment by kroitor** [comment]
Do you have any problems remaining?

**Comment by cklester** [comment]
Your test code for Bitfinex and Poloniex come back fine with your credentials, but they are having problems with my credentials. I'm going to get new credentials for both and continue testing.

**Comment by kroitor** [comment]
We will try to state in a more clear way in the error reporting from the library, so that users would not be confused with this anymore. In the meantime, waiting for your status. 
I suppose, that's five of five, so give me five, man! ;) I'm closing it, please reopen if you still have problems with new keypairs. Thanks for your involvement!

**Comment by cklester** [comment]
Will do! Thank you!
