### ISSUE TITLE
Interface for Gatecoin

### ISSUE THREAD

**Issue by cklester** [kroitor/ccxt#54]
Do you guys have plans to integrate Gatecoin?

**Comment by kroitor** [comment]
We have it implemented already, should be available very soon)

**Comment by cklester** [comment]
Awesome! You rock!

**Comment by cklester** [comment]
Oops. I don't know if I'm supposed to close issues or not. Sorry!

**Comment by kroitor** [comment]
No problem ) We will update you on Gatecoin in a matter of a day or two. Thanks!

**Comment by kroitor** [comment]
Hey, @cklester , would you mind if we ask you to help us debug the gatecoin here? Their exchange is regulated, and they have a strict admission policy. We have delays with obtaining a pair of keys for gatecoin (on verification). If you will be so kind to send us a new unused keypair for testing - it will speed things up significantly. Gatecoin would be available within a few hours then. 

If you're ok with it, better send it by email, switch off all permissions, we don't need your balance or your info, we only need to test if the authentication is correct, our goal is to deliver a stable gatecoin integration to you and other users asap. Thanks! We'll still be ok if you don't, we'll obtain a keypair sooner or later anyways. But if you do, it could help a lot.

**Comment by cklester** [comment]
@kroitor Yes! I'd be glad to help. I will email those to you shortly.

**Comment by kroitor** [comment]
Thanks so much!

**Comment by kroitor** [comment]
You wanted it? You got it! Gatecoin is now available since version 1.1.95! Special thanks to @cklester for being very helpful to us.
