### ISSUE TITLE
yunbi private api not work

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#55]
yunbi public api is fine. private api not work.

const yunbi =  new ccxt.yunbi ({
    apiKey: 'xxx',
    secret: 'xxx',
    verbose: true
})
// var info2 = await yunbi.privateGetMembersMe()
var info2 = await yunbi.privateGetOrders()
private api give 401
yunbi https://yunbi.com/api/v2/orders.json?access_key=8NnHFhLaXt42CqnquZCfCtdkQUq1bfeu89bhj3jm&tonce=1501038669&signature=6e2347aeaa6bb7a5e44161ef408747f41d875b2ad86cce2af9aa2123fefed385 { method: 'GET',
  headers: { 'User-Agent': 'ccxt/1.1.83 (+https://github.com/kroitor/ccxt) Node.js/7.10.0 (JavaScript)' },
  body: undefined }
catch... { Error: yunbi GET https://yunbi.com/api/v2/orders.json?access_key=8NnHFhLaXt42CqnquZCfCtdkQUq1bfeu89bhj3jm&tonce=1501038669&signature=6e2347aeaa6bb7a5e44161ef408747f41d875b2ad86cce2af9aa2123fefed385 401 Unauthorized
    at AuthenticationError.CCXTError (/mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.83@ccxt/ccxt.js:13:27)
    at new AuthenticationError (/mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.83@ccxt/ccxt.js:41:27)
    at /mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.83@ccxt/ccxt.js:422:27
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) constructor: [Function: AuthenticationError] }

i double checked my key/secret to make sure they are correct.
do you have a test case to check ?

**Comment by kroitor** [comment]
Did you use the keys before elsewhere (in other software maybe)?

**Comment by kroitor** [comment]
Also, have you read and tried the steps from the [Troubleshooting](https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting) section of the manual?

**Comment by 86chenjie** [comment]
i just generate a new pair key/secret. still 401.  can you run the same code, i just posted. if it worked in your side, then it must be my problem.

**Comment by kroitor** [comment]
For private yunbi.privateGetOrders () you need to specify a 'market' param like so:
```JavaScript
// ...

// orders by product symbol
await yunbi.privateGetOrders ({ market: market.products['BTC/CNY']['id'] })

// or

// orders by product id
await yunbi.privateGetOrders ({ market: 'btccny' })

// ...
```

This method is not a part of the unified ccxt API, it is a method of the custom Yunbi API, therefore it may need some params. Please, test it and report, standing by for updates from you.

**Comment by 86chenjie** [comment]
var info2 = await yunbi.privateGetMembersMe()
this api don't need any params, right?
can you run this line in your localhost? if it works, then it must be my problem.

**Comment by kroitor** [comment]
I'm not able to test their private API from where I am now, so we will have to test and return back to it a little later. It may be a bug in the library. Meanwhile, do not use their private API until we fix it. We're still waiting for them to resolve our verification, because we're not citizens of China. 

It would be very helpful, if you could send us a pair of keys for testing (if you can, remove all permissions, we only need to test the authentication with Yunbi, we don't need your balance, or anything else whatsoever). This way we could then test and help quicker (a fix would be ready in a couple of hours then).

**Comment by 86chenjie** [comment]
const yunbi =  new ccxt.yunbi ({
    // apiKey: '8NnHFhLaXt42CqnquZCfCtdkQUq1bfeu89bhj3jm',
    // secret: '2rDJ7K7him971O83J7OvJUM2FsxB5Tgz7yzZ0NJy',
    apiKey: 'jroBF8uJmFgHi3YKrYeRxSCeL3qtbLabaxcXxzoa',
    secret: '7LjTck795Axt1lzLxxbz5qAnbkDxVEVm5wGt8rgp',
    verbose: true
})
those 2 pairs are both valid. you can use them as you wish. 👍

**Comment by kroitor** [comment]
Thanks! We will get back to you shortly, will fix it asap.

**Comment by kroitor** [comment]
We're still debugging this, had to contact Yunbi support for their comment. No matter what we do with it, it still does not want to authenticate. Yet I'm sure it's a very basic problem and we will solve it as quickly as possible. Digging deeper now. Will update you on the progress.

**Comment by 86chenjie** [comment]
👍

**Comment by kroitor** [comment]
Ok, we found the problem at last. Get ready for an update. Yunbi will be working since version 1.1.84+. It will be available withing 30-40 minutes. Thank you very much for your help!

**Comment by kroitor** [comment]
I will post code for testing in several minutes here.

**Comment by 86chenjie** [comment]
Great! 💯

**Comment by kroitor** [comment]
Ok, Yunbi is now available again with version 1.1.84+.
We tested it with both of your keypairs (thanks again for that!) :

```JavaScript
"use strict";

let ccxt = require ('./ccxt')
let yunbi = ccxt.yunbi ({
	"apiKey": "8NnHFhLaXt42CqnquZCfCtdkQUq1bfeu89bhj3jm",
	"secret": "2rDJ7K7him971O83J7OvJUM2FsxB5Tgz7yzZ0NJy",

	// your keys need this
	// if you don't want to redefine nonce, then
	// just generate a new keypair and you should be fine now
	nonce: function () { return this.milliseconds (); }
})

let yunbi2 = ccxt.yunbi ({
	"apiKey": "jroBF8uJmFgHi3YKrYeRxSCeL3qtbLabaxcXxzoa",
	"secret": "7LjTck795Axt1lzLxxbz5qAnbkDxVEVm5wGt8rgp",

	// an alternative way to have milliseconds nonce
	nonce: Date.now,
})


async function test () {
	await yunbi.loadProducts ()
	console.log (await yunbi.fetchBalance ())
	await yunbi2.loadProducts ()
	console.log (await yunbi2.fetchBalance ())
}

test ()
```

We fixed an internal problem in the library, and you also need to override the nonce, if you want to continue using these keys. Please report after you test it, if everything is ok on your side now. Thanks!

**Comment by 86chenjie** [comment]
New version work great for me. Thanks very much! :)

**Comment by kroitor** [comment]
Thank you! Respect!
