### ISSUE TITLE
Bittrex fetchBalance() fails

### ISSUE THREAD

**Issue by dpyro** [kroitor/ccxt#57]
Using a fresh API key pair:

```typescript
const balance = await market.fetchBalance()
```

produces

```
bittrex https://bittrex.com/api/v1.1/account/getbalances?nonce=1501049737&apikey=[redacted] { method: 'GET',
  headers:
   { 'User-Agent': 'ccxt/1.1.83 (+https://github.com/kroitor/ccxt) Node.js/8.1.4 (JavaScript)',
     apisign: [redacted] },
  body: undefined }
(node:22773) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of undefined
(node:22773) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kroitor** [comment]
Check if you forgot to load products prior to calling other methods. Here's a sample for testing:

```
"use strict";

let ccxt = require ('./ccxt')
let bittrex = ccxt.bittrex ({
	"apiKey": "60f38a5818934fc08308778f94d3d8c4",
	"secret": "9d294ddb5b944403b58e5298653720c1",
})

async function test () {
	// as stated in the manual, the next line of code is mandatory
	// load your products prior to all other calls, don't forget it
	await bittrex.loadProducts () 
	console.log (await bittrex.fetchBalance ())
}

test ()
```

Please report, if this solves your issue. Thanks!

**Comment by dpyro** [comment]
This works. Odd that its required for Bittrex, but not Kraken. Thanks!

**Comment by kroitor** [comment]
> This works. Odd that its required for Bittrex, but not Kraken. Thanks!

Thanks for reporting! This is required for all markets, but may work without preloading products with some of them. The Manual clearly states, that you should load them prior to all other calls. Have a good day!

**Comment by kroitor** [comment]
P.S. we will implement an auto-detection mechanism to preload products automatically, very soon, in one of the upcoming releases.

**Comment by kroitor** [comment]
<img width="822" alt="screen shot 2017-07-26 at 09 55 28" src="https://user-images.githubusercontent.com/1294454/28608324-9c0c163a-71e8-11e7-8efd-65ca2c141875.png">

https://github.com/kroitor/ccxt/wiki/Manual#loading-products

The link is here for those who might encounter the same problem.

**Comment by flavioespinoza** [comment]
Is it true that
```javascript
loadProducts( )
```
has been renamed to
```javascript
loadMarkets( ) 
```
???  

### If so this is still not working.

```javascript 

"use strict";

require('babel-polyfill');

const ccxt = require ('ccxt');

(async function getBalances () {

  let bittrex = ccxt.bittrex ({
    'apikey' : 'foo',
    'apisecret' : 'bar'
  });

  let bittrexMarkets = await bittrex.loadMarkets ()

  try {

    let bittrexBalance = await bittrex.fetchBalance ()
    console.log('bittrexBalance', bittrexBalance);

  }
  catch(err) {

    console.log('bittrexBalance error__________________');
    console.log('err', err);

  }

}) ()

```

console error
```console

bittrexBalance error__________________
err TypeError: Cannot read property 'sigBytes' of undefined
    at Object.init (/Users/Flavor/Documents/Projects/es6/node-seed/node_modules/crypto-js/hmac.js:53:21)
    at Object.HmacSHA512 (/Users/Flavor/Documents/Projects/es6/node-seed/node_modules/crypto-js/core.js:744:25)
    at Exchange.hmac (/Users/Flavor/Documents/Projects/es6/node-seed/node_modules/ccxt/ccxt.es5.js:16:603)
    at /Users/Flavor/Documents/Projects/es6/node-seed/node_modules/ccxt/ccxt.es5.js:60:7637
    at process._tickCallback (internal/process/next_tick.js:103:7)

Process finished with exit code 0

```

**Comment by flavioespinoza** [comment]
However, these all work fine :)

```javascript
/**
 * Created by Flavor on 8/9/17.
 */
"use strict";

require('babel-polyfill');
require ('ansicolor').nice;

const ccxt      = require ('ccxt')
const asTable   = require ('as-table')
const log       = require ('ololog').configure ({ locate: false })
const _         = require('lodash')

(async function getBalances () {

  /** KRAKEN */
  let kraken = new ccxt.kraken ({
    'apiKey': 'foo',
    'secret': 'bar',
  })

  /** GDAX */
  let gdax = new ccxt.gdax  ({
    'apiKey': 'foo',
    'secret': 'bar',
    'password': 'balls', /** Required for gdax */
  })

  /** GEMINI */
  let gemini = new ccxt.gemini ({
    'apiKey': 'foo',
    'secret': 'bar',
  })

  /** BITFINEX */
  let bitfinex = new ccxt.bitfinex ({
    'apiKey': 'foo',
    'secret': 'bar',
  })

  try {

    // fetch balance
    let krakenBalance = await kraken.fetchBalance ()
    log (kraken.name.white, 'balance', krakenBalance)

    // fetch account balance from the exchange
    let gdaxBalance = await gdax.fetchBalance ()
    log (gdax.name.magenta, 'balance', gdaxBalance)

    // fetch balance
    let bitfinexBalance = await bitfinex.fetchBalance ()
    log (bitfinex.name.green, 'balance', bitfinexBalance)

    // fetch balance
    let geminiBalance = await gemini.fetchBalance ()
    log (gemini.name.blue, 'balance', geminiBalance)

  } catch (e) {

    if (e instanceof ccxt.DDoSProtection || e.message.includes ('ECONNRESET')) {
      log.bright.yellow ('[DDoS Protection] ' + e.message)
    } else if (e instanceof ccxt.RequestTimeout) {
      log.bright.yellow ('[Request Timeout] ' + e.message)
    } else if (e instanceof ccxt.AuthenticationError) {
      log.bright.yellow ('[Authentication Error] ' + e.message)
    } else if (e instanceof ccxt.ExchangeNotAvailable) {
      log.bright.yellow ('[Exchange Not Available Error] ' + e.message)
    } else if (e instanceof ccxt.ExchangeError) {
      log.bright.yellow ('[Exchange Error] ' + e.message)
    } else if (e instanceof ccxt.NetworkError) {
      log.bright.yellow ('[NetwBork Error] ' + e.message)
    } else {
      throw e;
    }
  }

}) ()
```
### Awesome project BTW!

**Comment by kroitor** [comment]
> Is it true that loadProducts () has been renamed to loadMarkets () ?

Yes )

@flavioespinoza 

In your first example, you named the credentials `apikey` and `apisecret`. Should be `apiKey` (uppercase `K`) and `secret` (without `api`). This one works:
```
"use strict";

let ccxt = require ('ccxt');

async function getBalances () {

  let bittrex = ccxt.bittrex ({
    'apiKey' : '60f38a5818934fc08308778f94d3d8c4',
    'secret' : '9d294ddb5b944403b58e5298653720c1',
    'nonce': function () { return this.milliseconds () },
  });

  let bittrexMarkets = await bittrex.loadMarkets ()

  try {

    let bittrexBalance = await bittrex.fetchBalance ()
    console.log('bittrexBalance', bittrexBalance);

  }
  catch(err) {

    console.log('bittrexBalance error__________________');
    console.log('err', err);

  }
}

getBalances ()
```

**Comment by Nilotaviano** [comment]
fetchBalance works for me.

**Comment by kroitor** [comment]
@flavioespinoza does the above snipper solve your issue? )

**Comment by flavioespinoza** [comment]
Ugggg,  I'm an idiot!!! --- Thanks for getting back to me.  

Again, Awesome project!

**Comment by kroitor** [comment]
@flavioespinoza thx!

BTW, you don't have to loadMarkets () manually anymore, it is done automatically on your first call to fetchBalance (), so... It's all updated in the Manual ) If you have any questions, don't hesitate to ask, I know it can be frustrating sometimes, so we might help if you have difficulties )

**Comment by kroitor** [comment]
@flavioespinoza I will add more readabable exceptions in cases if credentials are not set up right, and users will not have this problem anymore. Thanks for your feedback, it's very helpful!

**Comment by flavioespinoza** [comment]
Thanks, Igor!

BTW is there a way to refresh the order-book with the latest data. Like a
ticker?

**Comment by kroitor** [comment]
@flavioespinoza yep, you just fetch it again, and voila – you now have it refreshed ) If you mean streaming – it's not available yet, though we are working on it already. Will let you know when it's done. )

**Comment by slidenerd** [comment]
OMG i was gonna build an all exchange library, i cant believe someone made such an INSANE library, how long you been building this

**Comment by kroitor** [comment]
@slidenerd it has been under active development for about a month up till now. It's all in our public commit history ;)

**Comment by koubeissy-ibrahim** [comment]
hello 

i'm trying to access the balance on bittrex 
i tried all the above but still having this error 

Request header field apisign is not allowed by Access-Control-Allow-Headers in preflight response. 

![image](https://user-images.githubusercontent.com/4479939/30834872-d4c485f2-a25d-11e7-98dc-bcc6f84b3107.png)

can anyone help plz

**Comment by kroitor** [comment]
Hi, @koubeissy-ibrahim !

You should set a [CORS proxy](https://github.com/kroitor/ccxt/wiki/Install#cors-access-control-allow-origin) to avoid that issue:

![wiki-cors](https://user-images.githubusercontent.com/1294454/30834998-749e394c-a25e-11e7-9c8f-729afd82de34.jpg)

Read more about it here:

- https://github.com/ccxt-dev/ccxt/wiki
- https://github.com/kroitor/ccxt/wiki/Install#cors-access-control-allow-origin 
- [Issue #225](https://github.com/ccxt-dev/ccxt/issues/225)

**Quickfix:**

When initializing bittrex, pass a CORS-proxy parameter to it, like so:

```JavaScript
async function test () {

    let bittrex = new ccxt.bittrex ({

        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',

        'proxy': 'https://cors-anywhere.herokuapp.com/', // mind the last slash!
        // or
        // 'proxy': 'https://crossorigin.me/', // mind the last slash!
    })

    console.log (await bittrex.fetchBalance ())
}

await test ()
```

**Comment by koubeissy-ibrahim** [comment]
thanks a lot
works like a charm

**Comment by kroitor** [comment]
@koubeissy-ibrahim ok, but please note, that adding a proxy, is like putting and intermediary between you and the exchange, so instead of travelling directly back and forth, your data will have to move from you to your proxy, then to the exchange, then back to the proxy, and then to you. So it effectively doubles the round-trip time, lag and latency. If you have a time-critical application, like a large-scale trading operation, intermediaries are not desired. But if you just want to show recent prices or if you only trade with long timeframes and don't need to be very reactive – it's ok to use a proxy.

**Comment by koubeissy-ibrahim** [comment]
Yeh totally understand, for the time being all the functionalities of my app are read only and also I’ll be using the proxy for testing only
