### ISSUE TITLE
Easily select all implemented markets in python

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#6]
I don't have the reliable method to select implemented APIs in python. 

Suggestion: Can you implement function/constant which returns all available APIs. Something like:
```
import ccxt
ccxt.available_APIs()
# Returns ['kraken', 'gdax', ...
# Then this should work
eval('ccxt.kraken()')  # This gives me kraken API implementation from ccxt
```

Btw, your python module is missing ```__all__``` marker which modules should be imported with * import.  

https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

**Comment by kroitor** [comment]
Yes, I will add such a function and the import marker as well! Will be ready soon.
Thank you for feedback!

**Comment by kroitor** [comment]
That feature will be documented soon.

**Comment by nmiculinic** [comment]
Awesome, thank you!
