### ISSUE TITLE
Kraken market bug in fetch_balance

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#60]
Kraken market, fetch_balance :  the balance will always be none for these not in zcode and xcode 

![image](https://user-images.githubusercontent.com/2209077/28660215-b5da5250-72e4-11e7-9699-fc6fbc69940a.png)

**Comment by kroitor** [comment]
This is not a bug. It is intentional. Kraken doesn't return values if they are empty, therefore undefined is ok there.

**Comment by kroitor** [comment]
Sorry, please ignore my previous comment.

**Comment by kroitor** [comment]
Ok, I fixed it, should be ready in 30-40 minutes in version 1.1.92. Thanks!

**Comment by kroitor** [comment]
Version 1.1.92 is available now, thanks for your report!
