### ISSUE TITLE
chbtc createLimitBuyOrder fail

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#62]
let chbtcProducts = await chbtc.loadProducts()
var product = chbtcProducts['BTS/CNY']
var buyPrice = 0.96
var orderResult1 = await chbtc.createLimitBuyOrder(product, 1, buyPrice)
console.log(orderResult1)

chbtc https://trade.chbtc.com/api/order?method=order&accesskey=7c566473-a14e-4cc3-9e60-65d0e7b108ceprice=0.96&amount=11&currency=bts_cny&sign=f7ffc3ca0a67326c0cd89fb56ca410a2&reqTime=1501234889199 { method: 'POST',
  headers: { 'User-Agent': 'ccxt/1.1.84 (+https://github.com/kroitor/ccxt) Node.js/7.10.0 (JavaScript)' },
  body: undefined }
{ code: 1003, message: '验证不通过' }

the chinese mean verify failed.
And the posted url's price query param shoud have a '&' before it.
I tried add a '&' before price query param, and still verify failed.

**Comment by kroitor** [comment]
Hi! Thanks for posting this issue! I will upload the fix in 20 minutes.

**Comment by 86chenjie** [comment]
👍

**Comment by kroitor** [comment]
I uploaded the fix, the tests will take about 15 minutes and it will work in version 1.1.111 (will be available as soon as the tests pass)
You can watch build progress here: https://travis-ci.org/kroitor/ccxt/builds/

**Comment by kroitor** [comment]
Thanks!

**Comment by kroitor** [comment]
Ok, the fix is ready and available in version 1.1.111 ) Thank you and our apologies for a long waiting time. Also, it would be very helpful if you report whether everything now works normally with chbtc on your side. Thanks again!

**Comment by 86chenjie** [comment]
test both buy/sell api, both works.
thanks!  :)
