### ISSUE TITLE
yunbi createLimitBuyOrder fail

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#63]
var orderResult1 = await yunbi.createLimitBuyOrder(product, 1, buyPrice)

yunbi https://yunbi.com/api/v2/orders.json { method: 'POST',
  headers:
   { 'User-Agent': 'ccxt/1.1.111 (+https://github.com/kroitor/ccxt) Node.js/7.10.0 (JavaScript)',
     'Content-Type': 'application/x-www-form-urlencoded',
     'Content-Length': 193 },
  body: 'access_key=ObX7PGOEl0TWG6Y8KeElIWCY0UxsI2MxDDJWdV9l&market=btscny&ord_type=limit&side=buy&tonce=1501245725205&volume=1&signature=a71a85ce6563524155aeac7c08371d6507b50be086ff16353ee7516c14a32041' }
catch... { Error: yunbi POST https://yunbi.com/api/v2/orders.json 400 Bad Request (possible reasons: invalid API keys, bad or old nonce, market down or offline, on maintenance, DDoS protection, rate-limiting in effect)
    at MarketNotAvailableError.CCXTError (/mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.111@ccxt/ccxt.js:24:27)
    at MarketNotAvailableError.NotAvailableError (/mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.111@ccxt/ccxt.js:61:27)
    at new MarketNotAvailableError (/mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.111@ccxt/ccxt.js:70:27)
    at /mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.111@ccxt/ccxt.js:442:27
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) constructor: [Function: MarketNotAvailableError] }
^C

do you need key/secret pair to debug?

**Comment by kroitor** [comment]
Yes, if you can send us a keypair, we will fix it, thanks for your help!

**Comment by 86chenjie** [comment]
apiKey: 'ObX7PGOEl0TWG6Y8KeElIWCY0UxsI2MxDDJWdV9l',
 secret: '4XTRqkdAaZlPBdxITehiVVriCfjEmrXzGcv1UbDQ',

there are about 100 cny in the account, you can use it to test buy/sell.
thanks!

**Comment by kroitor** [comment]
Thanks ) We will try to leave your balance intact. Your help is much appreciated!

**Comment by kroitor** [comment]
We need some more time for this, to make Yunbi stable. Working on it. Hope to finish soon. Thanks for patience!

**Comment by kroitor** [comment]
Ok, I think we found the bug and fixed it.
@86chenjie if you can, please, update the ccxt to the most recent version 1.1.112 and run this code:

```
"use strict";

let ccxt = require ('ccxt')
async function test () {
    let yunbi = new ccxt.yunbi ({
        "apiKey": "ObX7PGOEl0TWG6Y8KeElIWCY0UxsI2MxDDJWdV9l",
        "secret": "4XTRqkdAaZlPBdxITehiVVriCfjEmrXzGcv1UbDQ",
        "nonce": Date.now,
        "verbose": true,
    })
	await yunbi.loadProducts () 
	let symbol = yunbi.products['BTC/CNY']['symbol'];
    console.log (await yunbi.createLimitBuyOrder (symbol, 100, 100))
}

test ()
```

When I run this code now with version 1.1.112 on my side, it replies with 'insufficient balance, cannot lock the amount' message, as we expect.
We added more verbose error reasoning, and we also fixed a bug with limit orders, so everything should work normally now. Can you, please, confirm that everything works on your side? If not, we will continue working on this issue. We've tested it and everything seems to work from our perspective.

**Comment by 86chenjie** [comment]
i tested with createLimitBuyOrder/createLimitSellOrder with latest version. both works.
yunbi https://yunbi.com/api/v2/orders.json { method: 'POST',
  headers:
   { 'User-Agent': 'ccxt/1.1.112 (+https://github.com/kroitor/ccxt) Node.js/7.10.0 (JavaScript)',
     'Content-Type': 'application/x-www-form-urlencoded',
     'Content-Length': 205 },
  body: 'access_key=ObX7PGOEl0TWG6Y8KeElIWCY0UxsI2MxDDJWdV9l&market=btscny&ord_type=limit&price=0.87&side=sell&tonce=1501252629038&volume=1&signature=c4e29368b6c37a15b5afec19033ae7d96bbb53bef2e71a1769cd4443b642e558' }
catch... Error: yunbi POST https://yunbi.com/api/v2/orders.json 201 Created {"id":464921865,"side":"sell","ord_type":"limit","price":"0.87","avg_price":"0.0","state":"wait","market":"btscny","created_at":"2017-07-28T14:37:06Z","volume":"1.0","remaining_volume":"1.0","executed_volume":"0.0","trades_count":0}
    at /mnt/d/workspace/bts-arbitrage/node_modules/_ccxt@1.1.112@ccxt/ccxt.js:440:27
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

probably the error is just for debug, right?

**Comment by kroitor** [comment]
Thanks! Just one more tweak left and we're done with this issue. Thanks for you patience, we're really sorry for the inconvenience. The error will go away in next version, of course, we will silence it, because it's not an error )

**Comment by kroitor** [comment]
Ok Yunbi is now fixed. There should be no errors and order should work normally, and everything else with Yunbi as well. Thanks for helping us! P.S. Don't forget to update to newest version 1.1.113
