### ISSUE TITLE
yunbi market api parameter is 'symbol', not market 

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#64]
most of the code in yunbi market to get data from yunbi server is error, 

 e.g. 

error code
``
orderbook = self.publicGetDepth ({
            'market': p['id'],
        })
``
the correct code is 
``
orderbook = self.publicGetDepth ({
            'symbol': p['id'],
        })
``

**Comment by kroitor** [comment]
Thanks for posting this! We're working on Yunbi right now to solve issue #63 as well.

**Comment by HaoH** [comment]
sorry, I made a mistake

**Comment by kroitor** [comment]
No problem, I make them too from time to time. Can I close this?

**Comment by kroitor** [comment]
@HaoH , do you still need this issue open? Is it ok if I close it (if you don't have questions with yunbi)?

**Comment by HaoH** [comment]
ok, please close it.

**Comment by kroitor** [comment]
Thanks for your involvement, anyway! You're very helpful!

**Comment by kroitor** [comment]
Ok Yunbi is now fixed. There should be no errors and order should work normally, and everything else with Yunbi as well. Thanks for helping us!

**Comment by kroitor** [comment]
P.S. don't forget to update your version to the newest 1.1.113

**Comment by HaoH** [comment]
thank you
