### ISSUE TITLE
py examples

### ISSUE THREAD

**Issue by doctord919** [kroitor/ccxt#65]
balances.py, markets.py, symbols.py,tickers.py - python examples in folder examples/py contains error(opechatka):
"except ccxt.MarketNotAvailaibleError as e:"
right:
"except ccxt.MarketNotAvailableError as e:"

**Comment by kroitor** [comment]
Thank you! Already fixing them!

**Comment by kroitor** [comment]
Fixed! Thanks again for your attention to details!
