### ISSUE TITLE
poloniex.createOrder

### ISSUE THREAD

**Issue by incompletude** [kroitor/ccxt#66]
Hey guys, again, quite impressive. Trying to use unifed api, but createOrder returns this[method] is not a function for poloniex. Not sure what is going on here. poloniex.createOrder is a function and poloniex.privatePostBuy works just ok.

poloniex.createOrder('BTC_DOGE', 'buy', '30000.00000000', '0.00000001')
        .then(data => {
            console.log(data)
        })
        .catch(function(e) {
            console.log(e)
        })

Okay, just found the problem.

createOrder (symbol, side, amount[, price[, params]]) at https://github.com/kroitor/ccxt/wiki/Manual is wrong. There is a type parameter.

**Comment by kroitor** [comment]
Hi! Thanks for reporting this! We'll take a look and fix it very shortly.

**Comment by kroitor** [comment]
We edited the docs. Actually, we're going to restructure the docs and add some missing detail very soon. So, thank you for posting this issue. It is now fixed in text (temporarily), so, I am closing this down, if you don't mind.
