### ISSUE TITLE
could you make 'user-agent' as a parameter in  Market.fetch

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#67]
I just found some platform , e.g. huobi pro, will forbid the current user-agent ‘ccxt/1.1.111 (+https://github.com/kroitor/ccxt) Python/3.6.1’ .

maybe it's better to give user-agent a default value if user doesn't specify any ua.

**Comment by kroitor** [comment]
Thanks for opening this issue! We will make it optional, very soon.

**Comment by kroitor** [comment]
This feature is on the way, building and testing now. Should be ready in 20-30 minutes.

**Comment by kroitor** [comment]
Ok, this fix is ready now and available in the most recent version of the ccxt library. It will still set the User-Agent, but you can turn it off now, or redefine it as you wish. It is now optional.

@HaoH , I know you're using Python, therefore you need to update to version 1.1.126 from PyPI and after that you can change your User-Agent [as written in the Manual](https://github.com/kroitor/ccxt/wiki/Manual#market-properties):

```Python
import ccxt

huobi = ccxt.huobi ({
    'verbose': True,     # to see if a User-Agent is present or not
    'userAgent': False,  # False, None or an empty string '' to turn off
})

huobi2 = ccxt.huobi ({
    'verbose': True,     # to see if a User-Agent is present or not
    'userAgent': 'HaoH', # a non-empty string to redefine the default User-Agent
})
```

We would be thankful if you test and report here, whether this fix helped you or not.
I am closing this for now. If you still have problems connecting to Huobi even with the User-Agent switched off, then feel free to reopen this issue or open a new one. Thanks for your feedback!
