### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Munkeynutz** [kroitor/ccxt#69]
```
File "myb.py", line 40, in <module>
    bittrexBalance = bittrex.fetch_balance()
  File "build\bdist.win-amd64\egg\ccxt\__init__.py", line 3286, in fetch_balance
  File "build\bdist.win-amd64\egg\ccxt\__init__.py", line 331, in index_by
TypeError: 'NoneType' object is not iterable
```

Just testing basic bittrex get balance.

The code lines its referring to in __Init__ is : 
```Python
    def fetch_balance (self):
        response = self.accountGetBalances ()
        balances = response['result']
        result = { 'info': balances }
        indexed = self.index_by (balances, 'Currency')
        for c in range (0, len (self.currencies)):
            currency = self.currencies[c]
            account = {
                'free': None,
                'used': None,
                'total': None,
            }
            if currency in indexed:
                balance = indexed[currency]
                account['free'] = balance['Available']
                account['used'] = balance['Pending']
                account['total'] = balance['Balance']
            result[currency] = account
        return result
```
I'm assuming this is intended to drop any empty balances....how best to recode this, or is there a better work around?

I did a get products as another test and it worked fine but it still throws this error even if I dump the products first.

**Comment by kroitor** [comment]
Can you show your code from instantiation of the market to the point of fetching a balance? From what you say, it looks like you forgot to load the products, though it's explicitly [stated in the Manual](https://github.com/kroitor/ccxt/wiki/Manual#loading-products):

<img width="913" alt="screen shot 2017-07-29 at 20 32 56" src="https://user-images.githubusercontent.com/1294454/28747476-e0e824c6-74a7-11e7-833c-b7eb512c5528.png">

To test if this is the case, please, run the following code snippet:
```Python
import ccxt
bittrex = ccxt.bittrex ({
	"apiKey": "60f38a5818934fc08308778f94d3d8c4",
	"secret": "9d294ddb5b944403b58e5298653720c1",
        "verbose": True,
})
bittrex.load_products () # this line is critical without it you will have exceptions!
print (bittrex.fetch_balance ())
```

What output do you get from this script?

**Comment by kroitor** [comment]
Should work, if you loaded products previously. I will definitely make a silent auto-preload in the next version, so that nobody ever forgets to load them and for this issue to go away forever )

**Comment by kroitor** [comment]
Does my answer resolve your issue? If so, can I close it?

**Comment by kroitor** [comment]
Also, check out the neighbouring issue #68. We automated product preloading (update to latest version), so you will never forget to preload products again )

**Comment by Munkeynutz** [comment]
Ahhh....dammit man....I'm an idiot....I actually copied my api info with extra characters.
I was loading products, well not at first....but yeah.
Please close this quickly.
Thank you.

**Comment by kroitor** [comment]
Thanks for your feedback anyway. As I wrote earlier, you should not have that problem anymore with auto-preloading )
