### ISSUE TITLE
improper return in productId function

### ISSUE THREAD

**Issue by incompletude** [kroitor/ccxt#70]
let btcusdId = market.productId ('ABC/DEF')  // returns 'ABC/DEF'

Not sure if this is intended, but I think the return should be undefined.

**Comment by kroitor** [comment]
This is intented, because if it does not find a product id, it returns the string untouched.

**Comment by kroitor** [comment]
Can I ask, why would you use that function?
You can do it in a more simple way and preserve your 'not found' key exceptions as well, like so:
```
let btcusdId = market.products['ABC/DEF']['id'] // throws exception as intended
let btcusdId = market.products['BTC/USD']['id'] // does not raise exceptions
```

So you can use standard language syntax and catch exceptions if symbol was not found. Therefore you can ignore the productId function completely.

**Comment by incompletude** [comment]
I tought it could be. 

market.products['BTC/USDT'] achieves the desirable result, invalid pair.

**Comment by kroitor** [comment]
Yes, exactly, we posted simultaneously )

**Comment by kroitor** [comment]
So, if you don't need this issue anymore, I will close it. And if you have any other questions, feel free to open a new issue, or reopen this one. Thanks for your involvement!

**Comment by incompletude** [comment]
Please, thank you very much. Sorry for the trouble.

**Comment by kroitor** [comment]
No trouble, your curiosity is welcome )

**Comment by kroitor** [comment]
Oh, by the way, forgot to tell you: we now have automatic products preloading, so you will never forget to load them anymore )

**Comment by incompletude** [comment]
Where is it?

**Comment by kroitor** [comment]
Yes, here you go: [The Manual](https://github.com/kroitor/ccxt/wik)! )

**Comment by incompletude** [comment]
That is very useful. Way less ifs. Thank you.

**Comment by kroitor** [comment]
You're welcome!)
