### ISSUE TITLE
miss parsing 'last' in poloniex market 'ticker' response

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#75]
poloniex will return 'last' price in 'ticker' response. but the code in ccxt 'poloniex' class doesn't parse it. 

here is the  poloniex document.

https://poloniex.com/support/api/  

> 

Ticker
In order to receive ticker updates, subscribe to "ticker". Updates will be in the following format:
Appropriate labels for these data are, in order: currencyPair,  **_last_**, lowestAsk, highestBid, percentChange, baseVolume, quoteVolume, isFrozen, 24hrHigh, 24hrLow

>

**Comment by kroitor** [comment]
Will add it very soon!

**Comment by kroitor** [comment]
This now works since version 1.1.149! Thanks!

**Comment by mahmutbedir** [comment]
24hrLow and 24hrHigh doesn't work.

**Comment by kroitor** [comment]
@mahmutbedir what's your language? Ah, here's 2 of 3:

```JavaScript
// JavaScript
(async function test () => {
    const ccxt = require ('ccxt')
    const polo = new ccxt.poloniex ()
    const ticker = await poloniex.fetchTicker ('BTC/USDT')
    console.log ('high:', ticker['high'], 'low:', ticker['low']) // 24-hour high / low
})
```

```Python
# Python
import ccxt
poloniex = ccxt.poloniex()
ticker = poloniex.fetch_ticker('BTC/USDT')
print('high:', ticker['high'], 'low:', ticker['low'])
```

Should be floats. Take a look here:
https://github.com/ccxt-dev/ccxt/blob/master/examples/py/tickers.py
https://github.com/ccxt-dev/ccxt/blob/master/examples/js/tickers.js
