### ISSUE TITLE
Python asyncio

### ISSUE THREAD

**Issue by davidpodrebarac** [kroitor/ccxt#78]
Hi, thanks for all the hard work you guys are doing. 
Have you considered integrating asyncio library in python for API methods? Aiohttp python library supports asyncio and can make asynchronous calls. I think that it would be a great feature to have and it would make monitoring multiple exchanges less resource heavy.

**Comment by kroitor** [comment]
Hi! Thanks for your interest in our work! Yes, we will be integrating asyncio, as in issue #7. We hope to finish that work soon. Will update you on this, meanwhile, if you don't mind, I am closing this issue as duplicate.

**Comment by davidpodrebarac** [comment]
Oh, sorry. I didn't notice that asyncio was in that issue.

**Comment by kroitor** [comment]
No problem, thank you anyway!
