### ISSUE TITLE
Kraken Issue with XDASH

### ISSUE THREAD

**Issue by cklester** [kroitor/ccxt#79]
Getting this when instantiating Kraken:

```
TypeError: Cannot use 'in' operator to search for 'XDASH' in undefined
    at ccxt.es5.js:11856:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by kroitor** [comment]
Hi! Can you show your instantiation code?

**Comment by kroitor** [comment]
Also, if you can, turn on verbose mode, and paste a little more, as written in [Troubleshooting](https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting). Thanks!

**Comment by cklester** [comment]
OK, I'll try the verbose mode first and report back.

**Comment by cklester** [comment]
Here's the request/response for Gatecoin "Balances:"

```
gatecoin GET https://api.gatecoin.com/Balance/Balances
Request:
 { method: 'GET',
  headers:
   { 'User-Agent': 'ccxt/1.1.150 (+https://github.com/kroitor/ccxt) Node.js/8.1.4 (JavaScript)',
     API_PUBLIC_KEY: 'REMOVED',
     API_REQUEST_SIGNATURE: 'REMOVED',
     API_REQUEST_DATE: 1501536494 },
  body: 'nonce=1501536494' }
{ Error: gatecoin GET https://api.gatecoin.com/Balance/Balances  Request with GET/HEAD method cannot have body
    at MarketNotAvailableError.CCXTError (ccxt.es5.js:39:116)
    at MarketNotAvailableError.MarketError (ccxt.es5.js:109:121)
    at new MarketNotAvailableError (ccxt.es5.js:126:145)
    at ccxt.es5.js:493:27
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) constructor: [Function: MarketNotAvailableError] }
```

Looks like the nonce can't be in the body for the Balance GET?

**Comment by cklester** [comment]
Ha! I posted in the wrong thread...

**Comment by kroitor** [comment]
No problem, for gatecoin, please, check out updates in #80.
As for this issue with Kraken, we will be waiting for more verbose info from you.

**Comment by cklester** [comment]
The Kraken issue was a nonce error. You can disregard if you want.

Thank you!

**Comment by kroitor** [comment]
Ok, so you can redefine your nonce to milliseconds and continue using Kraken, right?

**Comment by cklester** [comment]
Yes, that's what I did. Works fine now.

**Comment by kroitor** [comment]
Thanks!
