### ISSUE TITLE
Additional crypto exchanges

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#8]
> If you don't find a cryptocurrency exchange market in the list above and/or want another market to be added, post or send us a link to it by opening an issue here on GitHub or via email.

* Liqui https://liqui.io/api
* LiveCoin https://www.livecoin.net/api?lang=en
* Bter https://bter.com/api2  (They have some bugs on my browser, upon scrolling down api documentation is visible

**Comment by kroitor** [comment]
Yep, thanks! I will add their implementations in a matter of several hours.

**Comment by kroitor** [comment]
Liqui turned out to be the same API as BTCe, just had to switch URLs in schema and that's it )

**Comment by nmiculinic** [comment]
Awesome, thank you!
