### ISSUE TITLE
Logos repository

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#81]
Are the logo's referenced in the `LogoUrl`, e.g. https://i.imgur.com/RoM9XUq.png, stored in a repository somewhere? If not, can they be stored in a repository so I can place them on my own static server? I'd rather not use an external url and I'd like to have the opportunity to inspect these files.

**Comment by kroitor** [comment]
The logos are currently stored in GitHub CDN. Because the library avoids referencing the disk at all costs, if you want to serve them from your static server, you will have to download them all with a webpage-downloader, or save the page with your browser to your hard disk and rewrite the urls to serve from your static path programmatically. Serving the logos is actually beyond the scope of the library itself.

**Comment by kroitor** [comment]
![screen-shot-2017-08-01-at-14 23 441](https://user-images.githubusercontent.com/1294454/28823280-75527e4e-76c5-11e7-814c-48f09bc357bc.jpg)

**Comment by kroitor** [comment]
Does that answer your question? Above is an example of how you can save all logos to your disk  with Chrome, easily.

**Comment by thijstriemstra** [comment]
Can you not place them in the `gh-pages` branch, e.g. https://github.com/kroitor/ccxt/tree/gh-pages, so we can checkout the files that way and you can still serve them using github cdn.

**Comment by kroitor** [comment]
I'm not placing them in a branch, actually. They're in GitHub CDN, independent of the repository.

**Comment by thijstriemstra** [comment]
> Above is an example of how you can save all logos to your disk with Chrome, easily.

Instead of having to download them myself manually one by one, why not have them in a repository so I can run a virus-scanner on it etc.

**Comment by kroitor** [comment]
You don't have to download them manually one by one, you just download the whole GitHub page with Chrome to your disk in one click basically. Have you tried saving a webpage in Chrome before?

**Comment by thijstriemstra** [comment]
> Have you tried saving a webpage in Chrome before?

hehe, check my github profile if you have any doubts about that ;)

It's just that I'm using an opensource API here and I'd like to have control over all aspects including the images, for all I know the image file can be malicious. Or am I weird for thinking that? ;)

**Comment by kroitor** [comment]
All you have to do is to navigate to https://github.com/kroitor/ccxt with chrome or any other browser, click the page with your right mouse button or in file menu select 'save as' or 'save page as' and choose a destination on your disk, and voila, it will download and save all logos there. Then you can check them all with your antivirus software in one go.

**Comment by kroitor** [comment]
If those images are malicious, I would crack your browser, because your Chrome did download them to show them to you when you opened the library page on GitHub. So, if you're afraid of being cracked by a jpeg on the internet – (if that is possible at all) - you were hacked already by simply visiting the page, that contains those JPEGs.

**Comment by thijstriemstra** [comment]
If I'm going to download them perhaps an option to specify the base url for the logoUrl would be useful, e.g. http://localhost/vGwurP0.png instead of https://i.imgur.com/vGwurP0.png.

**Comment by kroitor** [comment]
You can rewrite the base url for the logos with a very basic regexp. Is that a problem?

**Comment by thijstriemstra** [comment]
No I guess not. Thanks for your feedback.

**Comment by kroitor** [comment]
Ok, I'm sorry for not being very helpful here, but the task of optimizing the logo delivery is indeed beyond the purpose of the library itself.

**Comment by kroitor** [comment]
```JavaScript
let logo = market.logo
let path = logo.split ('/')
let filename = path[path.length - 1]
let your_static_url = 'https://YOUR_BASE_PATH/path/to/' + filename
```

**Comment by kroitor** [comment]
```Python
# Python
logo = market.logo
path = logo.split ('/')
filename = path[len (path) - 1];
your_static_url = 'https://YOUR_BASE_PATH/path/to' + filename
```
