### ISSUE TITLE
Kraken BTC balance

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#82]
There seems to be an issue surrounding Kraken BTC balance
Upon calling 
```
print(kraken.fetch_balance()['info'])
```
I get
```
{'ZUSD': '0.4271', 'XXBT': '0.0013420000', 'XETH': '0.0093000000', 'BCH': '0.0000020000'}
```
And upon calling 
```
print(market.fetch_balance()['BTC'])
```
I get 
``` 
{'free': None, 'used': None, 'total': None}
```

Methods for obtaining the eth and usd balance work great.

**Comment by kroitor** [comment]
Thanks! Will fix it asap!

**Comment by kroitor** [comment]
Ok, this should work as of next version, 1.2.37 (should be available for downloading very soon). Please, if you can, update and report if Kraken BTC balance works normally after that. Thanks!

**Comment by kroitor** [comment]
Ok, version 1.2.37 is now available, don't forget to update your package with pip)

**Comment by marinsokol5** [comment]
Yeah works now properly.
Much obliged.
