### ISSUE TITLE
need a unified get depth api

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#84]
1. some exchange may has limit/merge param
2. format the original result to the same json format.

**Comment by kroitor** [comment]
Hi! Sorry, can you please explain this a little more? We already have the order books (market depth) unified.

**Comment by kroitor** [comment]
I mean, here: [Manual: Order Books / Market Depth](https://github.com/kroitor/ccxt/wiki/Manual#order-book--market-depth) – did you mean something different?

**Comment by 86chenjie** [comment]
sorry, i didn't notice that api. 
just one small question, some api have extra params like limit & merge. but the unified api seems don't support extra params.

**Comment by kroitor** [comment]
> just one small question, some api have extra params like limit & merge. but the unified api seems don't support extra params.

We will add that where applicable, very soon. Thanks!

**Comment by kroitor** [comment]
P.S. Currently it fetches the most deep version possible. But we will add support for extra params if you need more control over the depth.

**Comment by 86chenjie** [comment]
some times, the depth has too many bids/asks, so need to merge to make the bids/asks small.

**Comment by kroitor** [comment]
> so need to merge to make the bids/asks small.

You will have it soon (probably, a day or two) ) We will update you on this.

**Comment by 86chenjie** [comment]
👍  thanks

**Comment by 86chenjie** [comment]
besides, the order book should be all parsed to float, some api return string.
and the asks/bids should be sort in the same way.

**Comment by kroitor** [comment]
Should be floats everywhere already, and with sorted bidasks already ) If you find an inconsisteny, please write the exchange id, and we will fix it )

**Comment by kroitor** [comment]
![screen shot 2017-08-04 at 06 54 10](https://user-images.githubusercontent.com/1294454/28953594-d5979ee2-78e1-11e7-910b-0d07edd886ed.png)

**Comment by 86chenjie** [comment]
👍   just what i want!

**Comment by kroitor** [comment]
> just what i want!

Cool! ) Keep in touch for updates on extra params! )

**Comment by kroitor** [comment]
Ok, you can now have it in version 1.2.53 )

Pass your extra-params like so:

```JavaScript
"use strict";

let ccxt = require ('./ccxt')
let yunbi = ccxt.yunbi ()
let chbtc = ccxt.chbtc ()

async function test () {
	await yunbi.loadProducts ()
	await chbtc.loadProducts ()
	console.log (await yunbi.fetchOrderBook (yunbi.symbols[0], { 'limit': 10 }))
	console.log (await chbtc.fetchOrderBook (chbtc.symbols[0], { 'size': 20 }))
}

test ()
```

Please, report if everything is working for you and close this issue )

**Comment by kroitor** [comment]
@86chenjie does the above fix work for you?

**Comment by kroitor** [comment]
@86chenjie if you don't mind, I'm closing this, please, if you can, report on your status and reopen if needed, thanks!
