### ISSUE TITLE
Help for installation

### ISSUE THREAD

**Issue by senisende** [kroitor/ccxt#85]
Hi,

I need help for installation. I didnt install web-browser script.

**Comment by kroitor** [comment]
Hello, senisende! Can you please be more specific for us to be able to help you? What kind of an error or bug behaviour do you have?

**Comment by kroitor** [comment]
@senisende , I am afraid, if you don't know programming in any of three supported languages and if you don't reply, I will not be able to help you... I'll wait a little more and close this, if you don't show up.

**Comment by senisende** [comment]
@kroitor sorry late reply. I dont know programming. I think i cant install it witout help. I send u message to your gmail. You can close this. Thanks.

**Comment by kroitor** [comment]
Thanks!
