### ISSUE TITLE
Output not formatted/colored

### ISSUE THREAD

**Issue by irthomasthomas** [kroitor/ccxt#87]
Hi, I'm just running test.py and in my windows cmd console instead of the colored text I get ←[92mSYMBOL: BTC/USD←[0m
etc

I'm running python 2.7.

Thanks!

**Comment by kroitor** [comment]
Thanks! Will fix the colors under windows cmd soon )

**Comment by irthomasthomas** [comment]
colorama seems to work nicely.
https://pypi.python.org/pypi/colorama

**Comment by kroitor** [comment]
I've turned python test output colors off temporarily, but we will be adding it back again with colorama when we are ready to announce websocket/async patches and split py2/py3. I will close this issue for now, but I will update you on the progress.
