### ISSUE TITLE
create_order in hitbtc market error with 'bad price' response 

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#88]
I placed a order in hitbtc market and get error message 'bad price'.
maybe you should use 'decimal' type instead of float in order price parameter.

if the price is very small, e.g. 0.00003, 'str(price)' will get '3e-05', but hitbtc server cannot recognize scientific notation.

look at the following image, this error not found in hitbtc market.

![image](https://user-images.githubusercontent.com/2209077/29005020-0bd75806-7b05-11e7-9d22-5f416c2b1df9.png)

**Comment by kroitor** [comment]
Thanks! Will fix it in several minutes!

**Comment by kroitor** [comment]
You can work around this, if you pass a price as string, basically doing the decimal conversion yourself. But I will add a fix to it soon.

**Comment by HaoH** [comment]
ok, pass a price as string could temporarily resolve the problem. But as "create_order" is an unified interface, it's better to make the type of price parameter clearly.

**Comment by kroitor** [comment]
I've uploaded a fix to this, should be ready and available in version 1.2.87 in a couple of minutes.

**Comment by kroitor** [comment]
Please, report if the fix is working normally for you, and close this issue, if everything is fine.

**Comment by HaoH** [comment]
File "/usr/local/var/pyenv/versions/fintech/lib/python3.6/site-packages/ccxt/__init__.py", line 605, in create_limit_buy_order
    return self.create_order (product, 'limit', 'buy', amount, price, params)
  File "/usr/local/var/pyenv/versions/fintech/lib/python3.6/site-packages/ccxt/__init__.py", line 8677, in create_order
    order['price'] = self.decimal (price)
  File "/usr/local/var/pyenv/versions/fintech/lib/python3.6/site-packages/ccxt/__init__.py", line 316, in decimal
    return str (decimal.Decimal (str (number)))
NameError: name 'decimal' is not defined

**Comment by kroitor** [comment]
Forgot to import, it's fixed in next version 1.2.88, sorry for the inconvenience.

**Comment by kroitor** [comment]
It's available now. Thanks again!

**Comment by HaoH** [comment]
ok, it has passed the trading test here .  thanks.
