### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by Sixzero** [kroitor/ccxt#89]
I am a beginner in the field of cryptocurrencies, but don't you guys feel like the lib has quite bad naming conventions?
In the lib "Markets" means the Exchanges (like "bittrex").
In the lib "Products" means what we call markets (like 'ETH/BTC', etc.).
Symbols are symbols, which is a good point.

Before the lib gets more fame, I think it would be a good idea to refactor these things. 
An another reason for doing so is, that in the "Readme" and "manuals" everything follows the right naming conventions, so why not keep naming conventions to be consistent in the whole project.  

So I suggest refactoring in the lib:
Market -> Exchange
Product -> Market

I think that is all for now, would like to hear your opinions on it.
And keep up the good work! I like your lib! ;)

**Comment by kroitor** [comment]
Hi! Yep, we have been thinking about this, actually...  We will probably introduce this in 1.3.x

Markets → Exchanges: we think like renaming this, yes
Products → Markets: we don't think *'markets'* is a good name for traded valuables. Most exchanges call them *pairs* or *symbols*, and only a few of exchanges call them *markets*. We thought of calling them *pairs*, but there are some traded valuables which are not pairs of currencies. But we will consider this also, anyway.

Thanks!

**Comment by Sixzero** [comment]
Good points on the side of product naming convention.

I don't know which exchange calls it "pairs" or "symbols", (maybe I have seen the "pairs" once or twice) 
I would say on a market you can trade 2 products/a pair of products, that is why market/pairs feels trivial. But still market seems to be better then pairs.

Product could be "bitcoin" which really is a "product" and symbol is the short form of a product like "BTC".

Anyhow both solution is fine for me. 
Just wanted to make these decisions double fixed from the start.

**Comment by kroitor** [comment]
For example, on bitmex, they have the following:
```
mbp:ccxt igorkroitor$ node examples/js/symbols.js bitmex
Instantiating bitmex exchange market (printSymbols @ symbols.js:24)
bitmex has 14 symbols: XMRU17, DASHU17, XRPU17, ZECU17, QTUMU17, XTZZ17, B_BLOCKSZ17, B_SEGWITZ17, BTC/USD, XBTU17, XBJU17, ETHU17, ETC7D, LTCU17 (printSymbols @ symbols.js:33)
id          | symbol      | base | quote | info           
----------------------------------------------------------
XMRU17      | XMRU17      | XMR  | BTC   | [object Object]
DASHU17     | DASHU17     | DASH | BTC   | [object Object]
XRPU17      | XRPU17      | XRP  | BTC   | [object Object]
ZECU17      | ZECU17      | ZEC  | BTC   | [object Object]
QTUMU17     | QTUMU17     | QTUM | BTC   | [object Object]
XTZZ17      | XTZZ17      | XTZ  | BTC   | [object Object]
B_BLOCKSZ17 | B_BLOCKSZ17 | BTC  | XXX   | [object Object]
B_SEGWITZ17 | B_SEGWITZ17 | BTC  | XXX   | [object Object]
XBTUSD      | BTC/USD     | BTC  | USD   | [object Object]
XBTU17      | XBTU17      | BTC  | USD   | [object Object]
XBJU17      | XBJU17      | BTC  | JPY   | [object Object]
ETHU17      | ETHU17      | ETH  | BTC   | [object Object]
ETC7D       | ETC7D       | ETC  | BTC   | [object Object]
LTCU17      | LTCU17      | LTC  | BTC   | [object Object]
```

I wonder if B_BLOCKSZ17 is a market, a pair, or a symbol ) But, it's definitely a product of some sort )

**Comment by kroitor** [comment]
We hope to announce version 1.3.1 in several hours.

**Comment by Sixzero** [comment]
Wow! You are really working fast. 
That is what I call fast adaptation! 

I am gonna check it out ASAP! ;)

**Comment by kroitor** [comment]
Ok, the major renaming has been performed, version 1.3.1 is now available for downloading and testing. Please, report any inconsistencies left, that you notice. Thank you!
