### ISSUE TITLE
Make certain unified API methods private/delete them

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#9]
I'm looking at unified API and see many ways to shoot yourself in the foot using it. This is the current approach:

```
order (symbol, side, amount[, price[, params]])
trade (symbol, side, amount[, price[, params]])
buy (symbol, amount[, price[, params]])
sell (symbol, amount[, price[, params]])
createOrder (symbol, side, amount[, price[, params]])
createBuyOrder (symbol, amount[, price[, params]])
createSellOrder (symbol, amount[, price[, params]])
createLimitOrder (symbol, side, amount, price, params])
createMarketOrder (symbol, side, amount[, params])
createLimitBuyOrder (symbol, amount, price[, params])
createLimitSellOrder (symbol, amount, price[, params])
createMarketBuyOrder (symbol, amount[, params])
createMarketSellOrder (symbol, amount[, params])
```

I instead recommend the following:
```
createLimitBuyOrder (symbol, amount, price[, params])
createLimitSellOrder (symbol, amount, price[, params])
createMarketBuyOrder (symbol, amount[, params])
createMarketSellOrder (symbol, amount[, params])
```
Everything else should be private or non-existing (in python private methods begin with single _ ; Double underscore __ are also private but not inherited IIRC, since I remember having a bug with those)

It's explicit in what it's doing and does one single thing well. (SRP -- single responsibility principle) 

What's the difference between this two?
```
order (symbol, side, amount[, price[, params]])
trade (symbol, side, amount[, price[, params]])
```

Eventually, keep those (or one of these..not sure what's the difference)

Also is there any reason for keeping camelCase in python, instead of using only underscores? PEP8 standard defines how python code should look like, and I assume your users are using it; it's trivial converting camelCase to underscore in the head; much less trivial if there's a typo somewhere and you accidentally call the wrong function.

**Comment by nmiculinic** [comment]
And yeah, lack of price isn't clear enough to make it market order; this is a bug waiting to happen. Instead, have parameter type='market' or type='limit' to differentiate between those two.

**Comment by kroitor** [comment]
The reason for having a huge variety of method signatures was to ease the integration into existing projects, where other libraries may have existed previously with all their different flavours and syntaxes. That load of methods was added to allow code hot-swapping in existing logic. This way it would not require too much in-place rewriting to plug this library into a paper trading strategy or into a fast prototype of a bot.

Yet still, I agree completely, there's a potential pitfall for those who are not careful enough. I will remove excessive methods to minimize that. 

> What's the difference between this two?
> 
> ```
> order (symbol, side, amount[, price[, params]])
> trade (symbol, side, amount[, price[, params]])
> ```

There's no difference, it's an alias, legacy, for same reasons, mentioned above. There are 3 methods with same signature but different names: `createOrder == order == trade`. I will clean it up, of course.

> Also is there any reason for keeping camelCase in python, instead of using only underscores? PEP8 standard defines how python code should look like, and I assume your users are using it; it's trivial converting camelCase to underscore in the head; much less trivial if there's a typo somewhere and you accidentally call the wrong function.

The reason for keeping both camelCaseNames and names_with_underscores is cross-compatibility, the ability to copy-paste between languages (or close to that, without too many significant changes). This helps interoperability among the community of the users of the library, who prefer different languages, but would still be able to understand each other. 

The JS → Py/PHP transpiler currently does not convert internal public/private API calls to underscore-style inside method bodies. But I will finish the name conversion stage and all Python names will conform to PEP standards really soon, I hope.

> And yeah, lack of price isn't clear enough to make it market order; this is a bug waiting to happen. 

I'll make the price/order type more explicit and restrict the set of methods, thanks for pointing that out.

**Comment by kroitor** [comment]
Ok, I cleaned up the set of methods leaving only the following:

```
### Market Orders

Market price orders are also known as *spot price orders*, *instant orders* or simply *market orders*. A market order gets executed immediately. The matching engine of the exchange closes the order (fulfills it) with one or more transactions from the top of the order book stack. 

The exchange will close your market order for the best price available. You are not guaranteed though, that the order will be executed for the price you observe prior to placing your order. There can be a slight change of the price for the traded product while your order is being executed, also known as `price slippage`. The price can slip because of networking roundtrip latency, high loads on the exchange, price volatility and other factors. When placing a market order you don't need to specify the price of the order.

Note, that some exchanges will not accept market orders (they allow limit orders only).

```Python
// Python
market.create_market_buy_order (symbol, amount[, params])
market.create_market_sell_order (symbol, amount[, params])
market.create_limit_buy_order (symbol, amount, price[, params])
market.create_limit_sell_order (symbol, amount, price[, params])
```

... and their camelCase aliases. Everything else is gone from now on, no typo-mistakes anymore )

I also left in place just one single generic create_order () method, but I will explicitly mention the risks of using it in the docs.
