### ISSUE TITLE
fetch_balance parse error in 'bittrex' exchange, 'used' = 'balance' - 'availabel'

### ISSUE THREAD

**Issue by HaoH** [kroitor/ccxt#91]
balance['used'] in bittrex is not in response, but could be calculate using   `balance['Balance'] - balance['Available']  `  , not balance['Pending'],  'Pending' in bittrex is 'deposit pending', not balance blocked in orders.  

look at the following pic.

![image](https://user-images.githubusercontent.com/2209077/29079042-a8962476-7c8e-11e7-9cb5-0314f8fe5f1c.png)

**Comment by kroitor** [comment]
Thanks! Will fix it right now!

**Comment by kroitor** [comment]
Fixed in version 1.3.6. Thanks again!
