### ISSUE TITLE
Unified createOrder return

### ISSUE THREAD

**Issue by Nilotaviano** [kroitor/ccxt#94]
createOrder returns the raw JSON response. Having at least the order uuid returned uniformly is necessary.

**Comment by kroitor** [comment]
Yep, I agree ;)

**Comment by kroitor** [comment]
I'd like to discuss that a little with you, namely, the following:
1. Is it better to convert all order ids to strings for consistency across exchanges ?
2. ... or should we just leave them as they are (mixed ints and strings)?

**Comment by Nilotaviano** [comment]
Sorry for the wait. I think they should be converted to strings, for consistency.

**Comment by kroitor** [comment]
Ok, will do that as well ) Thx!

**Comment by kroitor** [comment]
Ok, the createOrder return is now unified. We updated the section on [Placing Orders](https://github.com/kroitor/ccxt/wiki/Manual#placing-orders) in the Manual to include the description of the returned value. Thanks for your feedback and for helping us with this!
