### ISSUE TITLE
set proxy

### ISSUE THREAD

**Issue by Naigel56** [kroitor/ccxt#95]
I have to use ccxt passing through a proxy, so according to the Wiki I set up the `proxy` variable but it doesn't seem to work as expected.

    const ccxt = require('ccxt');
    var poloniex = new ccxt.poloniex();
    poloniex.proxy = "http://172.16.251.1:8080/";
    poloniex.load_markets();

The request is rejected and I get this message

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: poloniex GET http://172.16.251.1:8080/https://
poloniex.com/public?command=returnTicker 400 Bad Request

Am I missing something or is `proxy` parameter not working as expected?

**Comment by kroitor** [comment]
The proxy parameter works, but it only supports proxies that can parse the appended URL, like so: 

```
https://cors-anywhere.herokuapp.com/https://your_url_here or
https://crossorigin.me/https://you_url_here
```

Try these two proxies first to see if they work for you.

The manual says it clearly:

The absolute exchange endpoint URL is appended to proxy string before HTTP request is sent to exchange. The proxy setting is an empty string '' by default. Below are examples of a non-empty proxy string (last slash is mandatory!):
Try the following:

```JavaScript
poloniex.proxy = 'https://crossorigin.me/' // last slash is critical
// or
poloniex.proxy = 'https://cors-anywhere.herokuapp.com/' // last slash is critical
```

Other proxies are not supported (yet).

**Comment by kroitor** [comment]
@Naigel56 does the above post answer your question? If so, please, close this issue. We will update you when we deliver a full-featured proxy support in ccxt. Thanks!

**Comment by kroitor** [comment]
@Naigel56 you can also you use a local proxy to forward your requests to a remote proxy, which can be easily setup with nginx/Apache or any other adequate HTTP server.

**Comment by Naigel56** [comment]
@kroitor yes thank you for the answer, a better proxy support would be great. As soon as I have a bit of free time I'll look at the code and try to figure out how to improve it.

**Comment by kroitor** [comment]
@Naigel56 thank you very much! We will also try to deliver it asap!
